packages:
  - "frontend"
  - "backend"
  - "config"
linkWorkspacePackages: true
blockExoticSubdeps: false
minimumReleaseAge: 0
allowBuilds:
  esbuild: true
  sharp: true
  "@ariga/atlas": true
  "{{PROJECT_NAME}}-config": true

