-- Recorded by scripts/record-project-snapshot.mts from @rebasepro/server-postgres v0.13.0.
-- Do not hand-edit: this is a record of a database that shipped, and editing it to make
-- a test pass un-tests every upgrade path through it.

CREATE SCHEMA auth;

CREATE SCHEMA rebase;

CREATE SCHEMA shop;

CREATE TYPE public.products_status AS ENUM (
    'draft',
    'published',
    'archived'
);

CREATE FUNCTION auth.jwt() RETURNS jsonb
    LANGUAGE sql STABLE
    AS $$
                    SELECT COALESCE(
                        NULLIF(current_setting('app.jwt', true), ''),
                        '{}'
                    )::jsonb;
                $$;

CREATE FUNCTION auth.roles() RETURNS text
    LANGUAGE sql STABLE
    AS $$
                    SELECT COALESCE(NULLIF(current_setting('app.user_roles', true), ''), '');
                $$;

CREATE FUNCTION auth.uid() RETURNS text
    LANGUAGE sql STABLE
    AS $$
                    SELECT COALESCE(
                        NULLIF(current_setting('app.uid', true), ''),
                        NULLIF(current_setting('app.user_id', true), '')
                    );
                $$;

CREATE FUNCTION rebase.sync_uid_user_id() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
            BEGIN
                IF NEW.uid IS NULL AND NEW.user_id IS NOT NULL THEN
                    NEW.uid := NEW.user_id;
                ELSIF NEW.user_id IS NULL AND NEW.uid IS NOT NULL THEN
                    NEW.user_id := NEW.uid;
                END IF;
                RETURN NEW;
            END $$;

CREATE TABLE public.addresses (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    street text
);

CREATE TABLE public.categories (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text
);

CREATE TABLE public.categories_products (
    product_id uuid NOT NULL,
    category_id uuid NOT NULL
);

CREATE TABLE public.children (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    nickname text
);

CREATE TABLE public.extremely_long_collection_slug_for_identifier_truncation (
    id uuid DEFAULT gen_random_uuid() CONSTRAINT extremely_long_collection_slug_for_identifier_trunc_id_not_null NOT NULL,
    corresponding_organizational_unit_id uuid
);

CREATE TABLE public.pinned_names (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    explicit_column_name text,
    explicit_category_key uuid
);

CREATE TABLE public.products (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    title text,
    created_by text,
    status public.products_status,
    primary_category_id uuid,
    supplier uuid
);

CREATE TABLE public.products_statuses (
    product_id uuid NOT NULL,
    status_id integer NOT NULL
);

CREATE TABLE public.products_tags (
    product_id uuid NOT NULL,
    tag_id integer NOT NULL
);

CREATE TABLE public.statuses (
    id integer NOT NULL,
    label text
);

ALTER TABLE public.statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.suppliers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text
);

CREATE TABLE public.tags (
    id integer NOT NULL,
    label text
);

ALTER TABLE public.tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.urls (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    href text
);

CREATE TABLE rebase.app_config (
    key text NOT NULL,
    value jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE rebase.magic_link_tokens (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid text NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE rebase.mfa_challenges (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    factor_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    verified_at timestamp with time zone,
    ip_address text,
    expires_at timestamp with time zone NOT NULL
);

CREATE TABLE rebase.mfa_factors (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid text NOT NULL,
    factor_type text DEFAULT 'totp'::text NOT NULL,
    secret_encrypted text NOT NULL,
    friendly_name text,
    verified boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE rebase.password_reset_tokens (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid text NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE rebase.recovery_codes (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid text NOT NULL,
    code_hash text NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE rebase.refresh_tokens (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid text NOT NULL,
    session_id text DEFAULT (gen_random_uuid())::text NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked boolean DEFAULT false NOT NULL,
    rotated_at timestamp with time zone,
    session_started_at timestamp with time zone DEFAULT now() NOT NULL,
    user_agent text,
    ip_address text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE rebase.schema_meta (
    key text NOT NULL,
    value text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE rebase.user_identities (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid text NOT NULL,
    provider text NOT NULL,
    provider_id text NOT NULL,
    profile_data jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE rebase.users (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    email text NOT NULL,
    display_name text,
    photo_url text,
    roles text[] DEFAULT '{}'::text[] NOT NULL,
    password_hash text,
    email_verified boolean DEFAULT false NOT NULL,
    email_verification_token text,
    email_verification_sent_at timestamp with time zone,
    is_anonymous boolean DEFAULT false NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    tokens_valid_after timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT users_email_length_check CHECK ((length(email) <= 320))
);

CREATE TABLE shop.inventory_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    sku text
);

INSERT INTO public.addresses VALUES ('cad7e14e-24b9-475c-8593-1b41cfea1db8', 'addresses-seed-1');
INSERT INTO public.addresses VALUES ('302da64a-d549-4fcf-989c-089931302059', 'addresses-seed-2');

INSERT INTO public.categories VALUES ('d2a41566-8509-4dc3-83d1-a0ca1659c38b', 'categories-seed-1');
INSERT INTO public.categories VALUES ('255c0d62-2b7a-4757-b3e2-9ac46e11b999', 'categories-seed-2');

INSERT INTO public.categories_products VALUES ('170e1442-582f-4e63-96a2-0b208e4bb346', '255c0d62-2b7a-4757-b3e2-9ac46e11b999');

INSERT INTO public.children VALUES ('ed9e3d23-f89c-42b7-9704-e4042b9ed03e', 'children-seed-1');
INSERT INTO public.children VALUES ('03ee5f34-12af-4ddb-97d7-2c141c8f13ff', 'children-seed-2');

INSERT INTO public.extremely_long_collection_slug_for_identifier_truncation VALUES ('c26c910d-f866-4c34-9a32-361ef6ba57d2', '255c0d62-2b7a-4757-b3e2-9ac46e11b999');
INSERT INTO public.extremely_long_collection_slug_for_identifier_truncation VALUES ('de56e773-bf11-4c40-9555-9a9791b6b5d4', '255c0d62-2b7a-4757-b3e2-9ac46e11b999');

INSERT INTO public.pinned_names VALUES ('a6608f4f-2f9b-4b6b-a2e1-c9fbc4524319', 'pinned_names-seed-1', '255c0d62-2b7a-4757-b3e2-9ac46e11b999');
INSERT INTO public.pinned_names VALUES ('7020607f-0b42-40c6-afdc-342a9e45cfb8', 'pinned_names-seed-2', '255c0d62-2b7a-4757-b3e2-9ac46e11b999');

INSERT INTO public.products VALUES ('170e1442-582f-4e63-96a2-0b208e4bb346', 'products-seed-1', 'products-seed-1', 'draft', '255c0d62-2b7a-4757-b3e2-9ac46e11b999', '3b6659b1-7260-4c10-be99-efb1cda6977c');
INSERT INTO public.products VALUES ('9387d8d7-5d03-48c4-b13a-b0231dfd08d9', 'products-seed-2', 'products-seed-2', 'draft', '255c0d62-2b7a-4757-b3e2-9ac46e11b999', '3b6659b1-7260-4c10-be99-efb1cda6977c');

INSERT INTO public.products_statuses VALUES ('170e1442-582f-4e63-96a2-0b208e4bb346', 1);

INSERT INTO public.products_tags VALUES ('170e1442-582f-4e63-96a2-0b208e4bb346', 1);

INSERT INTO public.statuses VALUES (1, 'statuses-seed-1');
INSERT INTO public.statuses VALUES (2, 'statuses-seed-2');

INSERT INTO public.suppliers VALUES ('cf5165d3-6755-4d88-b4ea-53fc8145624b', 'suppliers-seed-1');
INSERT INTO public.suppliers VALUES ('3b6659b1-7260-4c10-be99-efb1cda6977c', 'suppliers-seed-2');

INSERT INTO public.tags VALUES (1, 'tags-seed-1');
INSERT INTO public.tags VALUES (2, 'tags-seed-2');

INSERT INTO public.urls VALUES ('ce901f06-f776-4117-9cba-96929c6e62fe', 'urls-seed-1');
INSERT INTO public.urls VALUES ('be89bad6-6277-4bd2-ba63-9c8c3b82c184', 'urls-seed-2');

INSERT INTO rebase.schema_meta VALUES ('auth_schema_version', '2', '2026-08-05 17:38:58.811591+00');

INSERT INTO shop.inventory_items VALUES ('efd1db90-fbf3-4e5c-8374-d141c0182d85', 'inventory_items-seed-1');
INSERT INTO shop.inventory_items VALUES ('6ebf7827-b30b-4aae-bb1c-9e12f5a1997e', 'inventory_items-seed-2');

SELECT pg_catalog.setval('public.statuses_id_seq', 2, true);

SELECT pg_catalog.setval('public.tags_id_seq', 2, true);

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.categories_products
    ADD CONSTRAINT categories_products_pkey PRIMARY KEY (product_id, category_id);

ALTER TABLE ONLY public.children
    ADD CONSTRAINT children_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.extremely_long_collection_slug_for_identifier_truncation
    ADD CONSTRAINT extremely_long_collection_slug_for_identifier_truncation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pinned_names
    ADD CONSTRAINT pinned_names_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.products_statuses
    ADD CONSTRAINT products_statuses_pkey PRIMARY KEY (product_id, status_id);

ALTER TABLE ONLY public.products_tags
    ADD CONSTRAINT products_tags_pkey PRIMARY KEY (product_id, tag_id);

ALTER TABLE ONLY public.statuses
    ADD CONSTRAINT statuses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.urls
    ADD CONSTRAINT urls_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rebase.app_config
    ADD CONSTRAINT app_config_pkey PRIMARY KEY (key);

ALTER TABLE ONLY rebase.magic_link_tokens
    ADD CONSTRAINT magic_link_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rebase.magic_link_tokens
    ADD CONSTRAINT magic_link_tokens_token_hash_key UNIQUE (token_hash);

ALTER TABLE ONLY rebase.mfa_challenges
    ADD CONSTRAINT mfa_challenges_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rebase.mfa_factors
    ADD CONSTRAINT mfa_factors_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rebase.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rebase.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_token_hash_key UNIQUE (token_hash);

ALTER TABLE ONLY rebase.recovery_codes
    ADD CONSTRAINT recovery_codes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rebase.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rebase.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash);

ALTER TABLE ONLY rebase.schema_meta
    ADD CONSTRAINT schema_meta_pkey PRIMARY KEY (key);

ALTER TABLE ONLY rebase.user_identities
    ADD CONSTRAINT user_identities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rebase.user_identities
    ADD CONSTRAINT user_identities_provider_provider_id_key UNIQUE (provider, provider_id);

ALTER TABLE ONLY rebase.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY shop.inventory_items
    ADD CONSTRAINT inventory_items_pkey PRIMARY KEY (id);

CREATE INDEX idx_magic_link_tokens_hash ON rebase.magic_link_tokens USING btree (token_hash);

CREATE INDEX idx_magic_link_tokens_user ON rebase.magic_link_tokens USING btree (uid);

CREATE INDEX idx_mfa_challenges_factor ON rebase.mfa_challenges USING btree (factor_id);

CREATE INDEX idx_mfa_factors_user ON rebase.mfa_factors USING btree (uid);

CREATE INDEX idx_password_reset_tokens_hash ON rebase.password_reset_tokens USING btree (token_hash);

CREATE INDEX idx_password_reset_tokens_user ON rebase.password_reset_tokens USING btree (uid);

CREATE INDEX idx_recovery_codes_user ON rebase.recovery_codes USING btree (uid);

CREATE INDEX idx_refresh_tokens_hash ON rebase.refresh_tokens USING btree (token_hash);

CREATE INDEX idx_refresh_tokens_session ON rebase.refresh_tokens USING btree (session_id);

CREATE INDEX idx_refresh_tokens_user ON rebase.refresh_tokens USING btree (uid);

CREATE INDEX idx_user_identities_user ON rebase.user_identities USING btree (uid);

CREATE UNIQUE INDEX users_email_lower_key ON rebase.users USING btree (lower(email));

CREATE INDEX users_email_verification_token_idx ON rebase.users USING btree (email_verification_token) WHERE (email_verification_token IS NOT NULL);

ALTER TABLE ONLY public.categories_products
    ADD CONSTRAINT categories_products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.categories_products
    ADD CONSTRAINT categories_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.extremely_long_collection_slug_for_identifier_truncation
    ADD CONSTRAINT extremely_long_collection_slug_for_identifier_truncation_corres FOREIGN KEY (corresponding_organizational_unit_id) REFERENCES public.categories(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.pinned_names
    ADD CONSTRAINT pinned_names_explicit_category_key_fkey FOREIGN KEY (explicit_category_key) REFERENCES public.categories(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_primary_category_id_fkey FOREIGN KEY (primary_category_id) REFERENCES public.categories(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.products_statuses
    ADD CONSTRAINT products_statuses_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.products_statuses
    ADD CONSTRAINT products_statuses_status_id_fkey FOREIGN KEY (status_id) REFERENCES public.statuses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_supplier_fkey FOREIGN KEY (supplier) REFERENCES public.suppliers(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.products_tags
    ADD CONSTRAINT products_tags_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.products_tags
    ADD CONSTRAINT products_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE;

ALTER TABLE ONLY rebase.magic_link_tokens
    ADD CONSTRAINT magic_link_tokens_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY rebase.mfa_challenges
    ADD CONSTRAINT mfa_challenges_factor_id_fkey FOREIGN KEY (factor_id) REFERENCES rebase.mfa_factors(id) ON DELETE CASCADE;

ALTER TABLE ONLY rebase.mfa_factors
    ADD CONSTRAINT mfa_factors_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY rebase.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY rebase.recovery_codes
    ADD CONSTRAINT recovery_codes_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY rebase.refresh_tokens
    ADD CONSTRAINT refresh_tokens_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY rebase.user_identities
    ADD CONSTRAINT user_identities_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;

ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;

CREATE POLICY addresses_default_admin_read ON public.addresses FOR SELECT USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY addresses_default_admin_write_delete ON public.addresses FOR DELETE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY addresses_default_admin_write_insert ON public.addresses FOR INSERT WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY addresses_default_admin_write_update ON public.addresses FOR UPDATE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY categories_default_admin_read ON public.categories FOR SELECT USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY categories_default_admin_write_delete ON public.categories FOR DELETE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY categories_default_admin_write_insert ON public.categories FOR INSERT WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY categories_default_admin_write_update ON public.categories FOR UPDATE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY categories_delete_82b8225 ON public.categories FOR DELETE USING (false);

CREATE POLICY categories_insert_29ea277 ON public.categories FOR INSERT WITH CHECK (false);

ALTER TABLE public.categories_products ENABLE ROW LEVEL SECURITY;

CREATE POLICY categories_products_default_admin_read ON public.categories_products FOR SELECT USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY categories_products_default_admin_write_delete ON public.categories_products FOR DELETE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY categories_products_default_admin_write_insert ON public.categories_products FOR INSERT WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY categories_products_default_admin_write_update ON public.categories_products FOR UPDATE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY categories_products_default_edge_read ON public.categories_products FOR SELECT USING (((EXISTS ( SELECT 1
   FROM public.products _ex0
  WHERE (_ex0.id = categories_products.product_id))) AND (EXISTS ( SELECT 1
   FROM public.categories _ex1
  WHERE (_ex1.id = categories_products.category_id)))));

CREATE POLICY categories_select_841c287 ON public.categories FOR SELECT USING (true);

CREATE POLICY categories_update_b2b72ff ON public.categories FOR UPDATE USING (false) WITH CHECK (false);

ALTER TABLE public.children ENABLE ROW LEVEL SECURITY;

CREATE POLICY children_default_admin_read ON public.children FOR SELECT USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY children_default_admin_write_delete ON public.children FOR DELETE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY children_default_admin_write_insert ON public.children FOR INSERT WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY children_default_admin_write_update ON public.children FOR UPDATE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

ALTER TABLE public.extremely_long_collection_slug_for_identifier_truncation ENABLE ROW LEVEL SECURITY;

CREATE POLICY extremely_long_collection_slug_for_identifier_truncation_defaul ON public.extremely_long_collection_slug_for_identifier_truncation FOR DELETE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

ALTER TABLE public.pinned_names ENABLE ROW LEVEL SECURITY;

CREATE POLICY pinned_names_default_admin_read ON public.pinned_names FOR SELECT USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY pinned_names_default_admin_write_delete ON public.pinned_names FOR DELETE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY pinned_names_default_admin_write_insert ON public.pinned_names FOR INSERT WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY pinned_names_default_admin_write_update ON public.pinned_names FOR UPDATE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE POLICY products_default_admin_read ON public.products FOR SELECT USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY products_default_admin_write_delete ON public.products FOR DELETE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY products_default_admin_write_insert ON public.products FOR INSERT WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY products_default_admin_write_update ON public.products FOR UPDATE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY products_delete_82b8225 ON public.products FOR DELETE USING (false);

CREATE POLICY products_insert_29ea277 ON public.products FOR INSERT WITH CHECK (false);

CREATE POLICY products_select_841c287 ON public.products FOR SELECT USING (true);

ALTER TABLE public.products_statuses ENABLE ROW LEVEL SECURITY;

CREATE POLICY products_statuses_default_admin_read ON public.products_statuses FOR SELECT USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY products_statuses_default_admin_write_delete ON public.products_statuses FOR DELETE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY products_statuses_default_admin_write_insert ON public.products_statuses FOR INSERT WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY products_statuses_default_admin_write_update ON public.products_statuses FOR UPDATE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY products_statuses_default_edge_read ON public.products_statuses FOR SELECT USING (((EXISTS ( SELECT 1
   FROM public.products _ex0
  WHERE (_ex0.id = products_statuses.product_id))) AND (EXISTS ( SELECT 1
   FROM public.statuses _ex1
  WHERE (_ex1.id = products_statuses.status_id)))));

ALTER TABLE public.products_tags ENABLE ROW LEVEL SECURITY;

CREATE POLICY products_tags_default_admin_read ON public.products_tags FOR SELECT USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY products_tags_default_admin_write_delete ON public.products_tags FOR DELETE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY products_tags_default_admin_write_insert ON public.products_tags FOR INSERT WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY products_tags_default_admin_write_update ON public.products_tags FOR UPDATE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY products_tags_default_edge_read ON public.products_tags FOR SELECT USING (((EXISTS ( SELECT 1
   FROM public.products _ex0
  WHERE (_ex0.id = products_tags.product_id))) AND (EXISTS ( SELECT 1
   FROM public.tags _ex1
  WHERE (_ex1.id = products_tags.tag_id)))));

CREATE POLICY products_update_b2b72ff ON public.products FOR UPDATE USING (false) WITH CHECK (false);

ALTER TABLE public.statuses ENABLE ROW LEVEL SECURITY;

CREATE POLICY statuses_default_admin_read ON public.statuses FOR SELECT USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY statuses_default_admin_write_delete ON public.statuses FOR DELETE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY statuses_default_admin_write_insert ON public.statuses FOR INSERT WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY statuses_default_admin_write_update ON public.statuses FOR UPDATE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;

CREATE POLICY suppliers_default_admin_read ON public.suppliers FOR SELECT USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY suppliers_default_admin_write_delete ON public.suppliers FOR DELETE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY suppliers_default_admin_write_insert ON public.suppliers FOR INSERT WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY suppliers_default_admin_write_update ON public.suppliers FOR UPDATE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;

CREATE POLICY tags_default_admin_read ON public.tags FOR SELECT USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY tags_default_admin_write_delete ON public.tags FOR DELETE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY tags_default_admin_write_insert ON public.tags FOR INSERT WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY tags_default_admin_write_update ON public.tags FOR UPDATE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

ALTER TABLE public.urls ENABLE ROW LEVEL SECURITY;

CREATE POLICY urls_default_admin_read ON public.urls FOR SELECT USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY urls_default_admin_write_delete ON public.urls FOR DELETE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY urls_default_admin_write_insert ON public.urls FOR INSERT WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY urls_default_admin_write_update ON public.urls FOR UPDATE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

ALTER TABLE shop.inventory_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY inventory_items_default_admin_read ON shop.inventory_items FOR SELECT USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY inventory_items_default_admin_write_delete ON shop.inventory_items FOR DELETE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY inventory_items_default_admin_write_insert ON shop.inventory_items FOR INSERT WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY inventory_items_default_admin_write_update ON shop.inventory_items FOR UPDATE USING (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((auth.uid() IS NULL) OR (string_to_array(auth.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY inventory_items_delete_82b8225 ON shop.inventory_items FOR DELETE USING (false);

CREATE POLICY inventory_items_insert_29ea277 ON shop.inventory_items FOR INSERT WITH CHECK (false);

CREATE POLICY inventory_items_select_841c287 ON shop.inventory_items FOR SELECT USING (true);

CREATE POLICY inventory_items_update_b2b72ff ON shop.inventory_items FOR UPDATE USING (false) WITH CHECK (false);
