/**
 * Bakes `website/public/logo.svg` into `src/data/logo.ts`.
 *
 * The mark is 64 flat-fill facets, and the intro reveals them one at a time in
 * a spatial order — so each facet needs a real centre, not the average of the
 * numbers in its `d` attribute (those include arc radii and sweep flags, which
 * put the "centroid" hundreds of units outside the artwork). `getBBox()` in a
 * real renderer is the only cheap way to get it right, hence puppeteer.
 *
 * Re-run with `node scripts/extract-logo.mjs` whenever the mark changes.
 * See memory: rebase-logo-2026-08 — copy the whole offset viewBox, never `0 0`.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import puppeteer from "puppeteer";

const here = path.dirname(fileURLToPath(import.meta.url));
const SOURCE = path.resolve(here, "../../../website/public/logo.svg");
const TARGET = path.resolve(here, "../src/data/logo.ts");

const svg = fs.readFileSync(SOURCE, "utf8");

const browser = await puppeteer.launch({ headless: true });
const page = await browser.newPage();
await page.setContent(`<html><body style="margin:0">${svg}</body></html>`);

const { viewBox, facets } = await page.evaluate(() => {
    const svgEl = document.querySelector("svg");
    return {
        viewBox: svgEl.getAttribute("viewBox"),
        facets: [...svgEl.querySelectorAll("path")].map((p) => {
            const b = p.getBBox();
            return {
                d: p.getAttribute("d"),
                fill: p.getAttribute("fill"),
                opacity: p.getAttribute("fill-opacity"),
                cx: +(b.x + b.width / 2).toFixed(2),
                cy: +(b.y + b.height / 2).toFixed(2),
            };
        }),
    };
});

await browser.close();

const body = facets
    .map((f) => {
        const opacity = f.opacity ? `, opacity: ${Number(f.opacity)}` : "";
        return `    { cx: ${f.cx}, cy: ${f.cy}, fill: "${f.fill}"${opacity}, d: "${f.d}" },`;
    })
    .join("\n");

fs.writeFileSync(
    TARGET,
    `// GENERATED by scripts/extract-logo.mjs — do not edit by hand.
// Source: website/public/logo.svg (the canonical mark).

export interface LogoFacet {
    /** Bounding-box centre in viewBox units — drives the reveal order. */
    cx: number;
    cy: number;
    fill: string;
    opacity?: number;
    d: string;
}

/** The designer's offset square box. A \`0 0 …\` box renders blank. */
export const LOGO_VIEW_BOX = "${viewBox}";

export const LOGO_FACETS: LogoFacet[] = [
${body}
];
`,
);

console.log(`wrote ${facets.length} facets to ${path.relative(process.cwd(), TARGET)}`);
