/**
 * This file was auto-generated by Rebase.
 * Do not make direct changes to the file.
 */

export interface Database {
  authors: {
    Row: {
      id: number;
      name: string;
      salary?: number | null;
      computed?: string | null;
      createdAt?: string | null;
      posts?: Array<Database["posts"]["Row"]>;
    };
    Insert: {
      id?: number;
      name: string;
      salary?: number;
      computed?: string;
      createdAt?: string;
    };
    Update: {
      name?: string;
      salary?: number;
      computed?: string;
      createdAt?: string;
    };
    Relations: {
      posts: "posts";
    };
  };
  myNotes: {
    Row: {
      id: string;
      body?: string | null;
    };
    Insert: {
      id?: string;
      body?: string;
    };
    Update: {
      body?: string;
    };
    Relations: {
    };
  };
  orderItems: {
    Row: {
      id: number;
      sku: string;
      quantity?: number | null;
    };
    Insert: {
      id?: number;
      sku: string;
      quantity?: number;
    };
    Update: {
      sku?: string;
      quantity?: number;
    };
    Relations: {
    };
  };
  posts: {
    Row: {
      id: string;
      title: string;
      subtitle?: string | null;
      status?: "draft" | "published" | null;
      views?: number | null;
      tagsList?: Array<string> | null;
      embedding?: number[] | null;
      publishedAt?: string | null;
      authorId?: number | null;
      author?: Database["authors"]["Row"];
      tags?: Array<Database["tags"]["Row"]>;
    };
    Insert: {
      id?: string;
      title: string;
      subtitle?: string;
      status?: "draft" | "published";
      views?: number;
      tagsList?: Array<string>;
      embedding?: number[];
      publishedAt?: string;
      authorId?: number;
      author?: number;
    };
    Update: {
      title?: string;
      subtitle?: string;
      status?: "draft" | "published";
      views?: number;
      tagsList?: Array<string>;
      embedding?: number[];
      publishedAt?: string;
      authorId?: number;
      author?: number;
    };
    Relations: {
      author: "authors";
      tags: "tags";
    };
  };
  tags: {
    Row: {
      id: string;
      label: string;
    };
    Insert: {
      id?: string;
      label: string;
    };
    Update: {
      label?: string;
    };
    Relations: {
    };
  };
}

export type CollectionName = keyof Database;

export const collectionsDictionary = {
  authors: "authors",
  myNotes: "my-notes",
  orderItems: "order_items",
  posts: "posts",
  tags: "tags",
} as const;

export type CollectionsDictionary = typeof collectionsDictionary;

/** Which collection each of `A`'s relations reaches. */
export type RelationsOf<A extends CollectionName> =
  Database[A] extends { Relations: infer R } ? R : Record<string, never>;

/** The names of `A`'s relations. */
export type RelationKeys<A extends CollectionName> = keyof RelationsOf<A> & string;

/** The collection a relation reaches, or `never` when it left this project. */
export type RelationTarget<A extends CollectionName, K extends RelationKeys<A>> =
  RelationsOf<A>[K] extends CollectionName ? RelationsOf<A>[K] : never;

/** Counts `IncludeFor` down; TypeScript has no arithmetic. */
type Prev = [never, 0, 1, 2, 3];

/**
 * Per-relation options, minus `include` — which `IncludeFor` supplies at
 * the next depth so the nested keys are checked against the *target's*
 * relations rather than this collection's.
 */
export interface IncludeOptionsFor<A extends CollectionName, K extends RelationKeys<A>, D extends number> {
  limit?: number;
  where?: Record<string, unknown>;
  logical?: unknown;
  orderBy?: unknown;
  fields?: string[];
  include?: RelationTarget<A, K> extends CollectionName
    ? IncludeFor<RelationTarget<A, K>, Prev[D]>
    : never;
}

/**
 * An `include` for collection `A`: its relation names, dotted paths, or the
 * parametrised tree — with every key checked against the relations that
 * actually exist, at every level.
 */
export type IncludeFor<A extends CollectionName, D extends number = 3> =
  D extends 0
    ? never
    : | readonly (RelationKeys<A> | "*")[]
      | { [K in RelationKeys<A>]?: true | IncludeOptionsFor<A, K, D> };

/** The relation names an include asks for at the top level. */
type IncludedKeys<A extends CollectionName, I> =
  I extends readonly (infer K)[]
    ? Extract<K, RelationKeys<A>>
    : Extract<keyof I, RelationKeys<A>>;

/**
 * The row a read with include `I` returns: `Row`, with every included
 * relation made **required**.
 *
 * `Row` types a relation as optional because it is absent from every read
 * that did not name it. Once a read has named it, it is there — and having
 * to write `row.author?.name` after asking for the author is the type
 * describing a possibility the query already ruled out.
 */
export type RowWith<A extends CollectionName, I> =
  Database[A]["Row"] & Required<Pick<Database[A]["Row"], IncludedKeys<A, I> & keyof Database[A]["Row"]>>;
