import { describe, expect, it } from "@jest/globals";
import { areSecretsEphemeral } from "../src/env";

/**
 * The ephemeral-secrets warning is only true on the first run.
 *
 * `rebase dev` caches the development `JWT_SECRET` and `REBASE_SERVICE_KEY` in
 * `.rebase-dev-secrets.json` precisely so a restart does not log you out of
 * your own app. The warning that follows said the opposite — "these are
 * ephemeral, existing tokens will be invalidated on restart" — on every boot,
 * including all the ones where the secrets came straight back out of that file
 * unchanged.
 *
 * Which is worse than a cosmetic wrong: it printed above the CORS warning and
 * the storage warning, both of which are real, and taught developers that the
 * block of warnings at startup is noise.
 */
describe("areSecretsEphemeral", () => {
    it("says nothing when every secret was set explicitly", () => {
        expect(areSecretsEphemeral({ autoGenerated: [], reused: [], storeUsable: true })).toBe(false);
    });

    it("warns on the first run, when the secrets did not exist before", () => {
        expect(areSecretsEphemeral({
            autoGenerated: ["JWT_SECRET", "REBASE_SERVICE_KEY"],
            reused: [],
            storeUsable: true
        })).toBe(true);
    });

    it("stays quiet on the second run, when both came out of the cache", () => {
        // The case the warning was wrong about, and by far the most common one.
        expect(areSecretsEphemeral({
            autoGenerated: ["JWT_SECRET", "REBASE_SERVICE_KEY"],
            reused: ["JWT_SECRET", "REBASE_SERVICE_KEY"],
            storeUsable: true
        })).toBe(false);
    });

    it("warns when only some of them were cached", () => {
        // A half-populated store: the new one really will change on restart.
        expect(areSecretsEphemeral({
            autoGenerated: ["JWT_SECRET", "REBASE_SERVICE_KEY"],
            reused: ["JWT_SECRET"],
            storeUsable: true
        })).toBe(true);
    });

    it("warns whenever the store cannot be written, even if it read back", () => {
        // A read-only directory, or a store that failed its first write. Nothing
        // minted here survives, so the claim is true again.
        expect(areSecretsEphemeral({
            autoGenerated: ["JWT_SECRET"],
            reused: ["JWT_SECRET"],
            storeUsable: false
        })).toBe(true);
    });
});
