#!/usr/bin/env bash
#
# Bring a self-hosted Rebase up in one command.
#
# The compose file next to this script requires four values and refuses to start
# without them, which is right for a deployment and wrong for the first thirty
# seconds of trying one. This generates them once, into `infra/docker/.env`, tells you
# it did, and then runs the compose file unchanged.
#
#   ./infra/docker/quickstart.sh        # up, attached
#   ./infra/docker/quickstart.sh -d     # any argument is passed through to compose
#
# It generates secrets rather than shipping defaults: a compose file with
# `JWT_SECRET=changeme` in it is a compose file that reaches production with
# `changeme` in it. Anything already in infra/docker/.env is kept, so this is safe to
# re-run and safe to edit afterwards.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
COMPOSE_FILE="$HERE/docker-compose.selfhost.yml"
ENV_FILE="$HERE/.env"

die() { printf '\033[31m✗\033[0m %s\n' "$1" >&2; exit 1; }
note() { printf '\033[36m›\033[0m %s\n' "$1"; }
ok()   { printf '\033[32m✓\033[0m %s\n' "$1"; }

command -v docker >/dev/null 2>&1 || die "Docker is not installed, or not on PATH."
docker compose version >/dev/null 2>&1 || die "This needs Docker Compose v2 (\`docker compose\`, not \`docker-compose\`)."

# ── The bundle ───────────────────────────────────────────────────────────────
#
# Built, not generated here: `rebase build` needs the project's own toolchain,
# takes minutes, and doing it silently inside something called quickstart would
# hide the one step the reader most needs to know about.
BUNDLE="${REBASE_BUNDLE_DIR:-$ROOT/dist-bundle}"
if [ ! -f "$BUNDLE/manifest.json" ]; then
    die "No bundle at $BUNDLE.
    Build your project first:

        rebase build

    Then run this again. (Set REBASE_BUNDLE_DIR to point somewhere else.)"
fi

# ── Secrets ──────────────────────────────────────────────────────────────────
secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    else
        # Every machine that can run this has one of the two.
        head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
    fi
}

if [ -f "$ENV_FILE" ]; then
    ok "Using the existing $(basename "$(dirname "$ENV_FILE")")/$(basename "$ENV_FILE")"
else
    note "No infra/docker/.env — generating one with fresh random secrets."
    umask 077
    cat > "$ENV_FILE" <<EOF
# Generated by infra/docker/quickstart.sh. Keep it out of version control.
#
# These are real random secrets, not placeholders. Rotating JWT_SECRET signs
# every existing session out; rotating REBASE_SERVICE_KEY invalidates anything
# authenticating with it.

POSTGRES_PASSWORD=$(secret)
JWT_SECRET=$(secret)
REBASE_SERVICE_KEY=$(secret)

# The origins your frontend is served from. Add your real domain before you put
# this in front of anyone.
CORS_ORIGINS=http://localhost:8080

# The published runtime tag to run. Change it and restart to upgrade; your
# bundle is untouched.
REBASE_VERSION=latest

# Host ports.
PORT=8080
POSTGRES_PORT=5432
# The pooled Postgres port, used only with `--profile pooler`. For serverless
# clients and anything else that cannot hold a connection; see the compose file
# for what transaction pooling changes about a connection.
PGBOUNCER_PORT=6432
EOF
    ok "Wrote infra/docker/.env (mode 600). Read it before you deploy anywhere."
fi

# `.env` next to the compose file is not loaded automatically when the file is
# passed with -f from elsewhere, so it is named explicitly rather than left to
# whichever directory the caller happens to be standing in.
note "Starting Postgres and the Rebase runtime…"
exec docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up "$@"
