/**
 * Generators for the property suites in this directory.
 *
 * These are not test data in the example-based sense. Each one describes the
 * *shape of everything valid* for its type, and the properties that consume it
 * are claims quantified over that whole set — "for all policy expressions",
 * not "for these nine". What a generator excludes is therefore part of the
 * claim, and every exclusion below is annotated with why, because an
 * unexplained exclusion is how a property comes to look stronger than it is.
 */

import fc from "fast-check";
import {
    PolicyCompareOperator,
    PolicyExpression,
    PolicyOperand,
    policy
} from "@rebasepro/types";

/**
 * Identifiers that are already snake_case, so `toSnakeCase` is the identity on
 * them.
 *
 * The compiler runs every field name through `toSnakeCase` on the way to SQL
 * (a column is snake_case even when the property is camelCase), while the JS
 * evaluator reads `entity.values[name]` with the name as written. So for a
 * camelCase field the two sides genuinely refer to different keys — by design,
 * not by defect. Generating only snake_case names removes that intended
 * asymmetry from the round-trip properties, which are about the parser and the
 * compiler rather than about the naming convention. The convention gets its own
 * property in `policy-roundtrip.property.test.ts` (`toSnakeCase` idempotence),
 * which is the part that *would* break a round-trip if it regressed.
 */
export const snakeIdentifier: fc.Arbitrary<string> = fc
    .array(fc.stringMatching(/^[a-z][a-z0-9]{0,5}$/), { minLength: 1, maxLength: 3 })
    .map(parts => parts.join("_"));

/**
 * Literal values, including strings that need SQL escaping.
 *
 * The apostrophes are deliberate and load-bearing: `quoteLiteral` doubles them
 * on the way out, so whether the parser undoubles them on the way back is
 * exactly the sort of asymmetry a hand-written example set never contains,
 * because nobody writes `O'Brien` into a fixture by accident.
 */
export const literalValue: fc.Arbitrary<string | number | boolean | null> = fc.oneof(
    fc.stringMatching(/^[a-zA-Z0-9 _.@-]{0,12}$/),
    fc.constantFrom("it's", "O'Brien", "''", "a'b'c"),
    fc.integer({ min: -1000, max: 1000 }),
    fc.boolean(),
    fc.constant(null)
);

export const compareOperator: fc.Arbitrary<PolicyCompareOperator> =
    fc.constantFrom<PolicyCompareOperator>("eq", "neq", "lt", "lte", "gt", "gte");

/**
 * Operands, minus `outerField`.
 *
 * `outerField` is only meaningful inside an `existsIn` subquery — at the top
 * level it compiles to a bare, unqualified column name and the JS evaluator
 * reports it unresolvable. It is generated by {@link innerPolicyExpression}
 * instead, where it means something.
 */
export const policyOperand: fc.Arbitrary<PolicyOperand> = fc.oneof(
    snakeIdentifier.map(name => policy.field(name)),
    literalValue.map(value => policy.literal(value)),
    fc.constant(policy.authUid()),
    fc.constant(policy.authRoles())
);

export const roleName: fc.Arbitrary<string> = fc.stringMatching(/^[a-z][a-z0-9_]{0,7}$/);

/**
 * Raw-SQL escape-hatch bodies.
 *
 * Restricted to fragments that survive being read back, because `raw` is the
 * one node with no structure to preserve: the round-trip properties can only
 * claim that a raw body is reproduced verbatim, and a body containing a
 * top-level ` AND ` is *supposed* to come back decomposed into an `and` of two
 * raws. Including such bodies would make the properties assert the parser does
 * nothing, which is the opposite of its job. The interesting adversarial cases
 * — a subquery whose `AND` sits inside parens — are generated on purpose by
 * {@link rawWithNestedAnd}.
 */
export const rawSql: fc.Arbitrary<string> = fc.constantFrom(
    "tenant_id = current_setting('app.tenant')",
    "created_at > now() - interval '7 days'",
    "status <@ ARRAY['draft','review']",
    "jsonb_exists(metadata, 'featured')",
    "octet_length(body) < 1024"
);

/**
 * Raw bodies whose `AND` / `OR` sits inside a subquery.
 *
 * This is the shape that broke: `sqlToPolicy` used to split on ` AND ` without
 * tracking paren depth, tearing an `EXISTS (... WHERE a AND b)` in half and
 * re-emitting `(EXISTS (... WHERE a)) AND (b)`, where `b`'s alias is no longer
 * in scope. Postgres rejects that outright with "missing FROM-clause entry".
 * Generating it means the fixed-point property below is aimed at the defect
 * class rather than at whatever the fix happened to make true.
 */
export const rawWithNestedAnd: fc.Arbitrary<string> = fc
    .tuple(snakeIdentifier, snakeIdentifier, snakeIdentifier)
    .map(([table, colA, colB]) =>
        `EXISTS (SELECT 1 FROM ${table} m WHERE m.${colA} = t.${colA} AND m.${colB} = rebase.uid())`);

/** Leaf expressions — everything with no `PolicyExpression` child. */
const leafExpression: fc.Arbitrary<PolicyExpression> = fc.oneof(
    fc.constant(policy.true()),
    fc.constant(policy.false()),
    fc.constant(policy.authenticated()),
    fc.constant(policy.serverContext()),
    fc.tuple(policyOperand, compareOperator, policyOperand)
        .map(([l, op, r]) => policy.compare(l, op, r)),
    fc.array(roleName, { minLength: 1, maxLength: 3 }).map(roles => policy.rolesOverlap(roles)),
    fc.array(roleName, { minLength: 1, maxLength: 3 }).map(roles => policy.rolesContain(roles)),
    rawSql.map(sql => policy.raw(sql)),
    rawWithNestedAnd.map(sql => policy.raw(sql))
);

/**
 * Arbitrary policy expressions, `existsIn` included.
 *
 * `maxDepth: 3` is not a hedge about correctness so much as an admission about
 * cost: these are trees, the compiler is recursive, and the interesting
 * interactions (a subquery inside an `or` inside a `not`) all appear by depth
 * three. Bounded-depth exhaustion is the standard small-scope hypothesis —
 * design errors that show up at all show up small.
 */
export const policyExpression: fc.Arbitrary<PolicyExpression> = fc.letrec<{
    expr: PolicyExpression;
    inner: PolicyExpression;
}>(tie => ({
    expr: fc.oneof(
        { maxDepth: 3, depthSize: "small" },
        leafExpression,
        fc.array(tie("expr"), { minLength: 0, maxLength: 3 }).map(ops => policy.and(...ops)),
        fc.array(tie("expr"), { minLength: 0, maxLength: 3 }).map(ops => policy.or(...ops)),
        tie("expr").map(op => policy.not(op)),
        fc.tuple(snakeIdentifier, tie("inner"))
            .map(([collection, where]) => policy.existsIn({ collection, where }))
    ),
    // Inside a subquery `outerField` becomes meaningful, so the inner grammar
    // is the outer one plus that operand.
    inner: fc.oneof(
        { maxDepth: 2, depthSize: "small" },
        leafExpression,
        fc.tuple(snakeIdentifier, compareOperator, policyOperand)
            .map(([name, op, r]) => policy.compare(policy.outerField(name), op, r)),
        fc.array(tie("inner"), { minLength: 1, maxLength: 2 }).map(ops => policy.and(...ops)),
        fc.array(tie("inner"), { minLength: 1, maxLength: 2 }).map(ops => policy.or(...ops))
    )
})).expr;

/** Expressions with no `existsIn` and no `outerField` — client-evaluable. */
export const innerPolicyExpression: fc.Arbitrary<PolicyExpression> = fc.letrec<{
    expr: PolicyExpression;
}>(tie => ({
    expr: fc.oneof(
        { maxDepth: 3, depthSize: "small" },
        leafExpression,
        fc.array(tie("expr"), { minLength: 0, maxLength: 3 }).map(ops => policy.and(...ops)),
        fc.array(tie("expr"), { minLength: 0, maxLength: 3 }).map(ops => policy.or(...ops)),
        tie("expr").map(op => policy.not(op))
    )
})).expr;

/**
 * Evaluation contexts spanning every branch the evaluator distinguishes:
 * signed in, anonymous (both spellings rebase has ever reported), and the
 * no-uid case a client presents. `entity: null` is included because
 * collection-level gating really does evaluate with no row in hand, and that is
 * where `field` operands go unresolvable.
 */
export const evalContext = fc.record({
    uid: fc.oneof(
        fc.constantFrom("user-1", "user-2"),
        fc.constantFrom("anonymous", "anon"),
        fc.constant(null),
        fc.constant(undefined)
    ),
    roles: fc.array(roleName, { maxLength: 3 }),
    entity: fc.oneof(
        fc.constant(null),
        fc.dictionary(snakeIdentifier, literalValue, { maxKeys: 4 })
            .map(values => ({ id: "e1", path: "things", values } as never))
    )
});
