export * from "./icon_keys";
export * from "./cool_icon_keys";
export * from "./Icon";
export * from "./GitHubIcon";
export * from "./HandleIcon";

// Re-export types from lucide-react. Types only: the full `icons` map used to
// be re-exported here as `lucideIcons`, and because that map holds a reference
// to every icon in the library, exporting it defeated tree-shaking outright —
// 822 kB of icon components in the entry chunk, preloaded before login. Name
// lookups go through `LucideIconByName` / `loadLucideIcons` now, which fetch
// the map on first use.
export type { LucideProps, LucideIcon } from "lucide-react";
export * from "./LucideIconByName";

// Re-export individual icon components used across the monorepo.
// Sub-packages import these from @rebasepro/ui instead of declaring a direct
// lucide-react dependency.  When a new icon is needed, add it here.
export {
    AlertCircleIcon,
    AlertTriangleIcon,
    AlignLeftIcon,
    AppWindow,
    ArrowDownIcon,
    ArrowDownToLineIcon,
    ArrowLeftIcon,
    ArrowRightFromLineIcon,
    ArrowRightIcon,
    ArrowRightLeftIcon,
    ArrowRightToLineIcon,
    ArrowUpDownIcon,
    ArrowUpIcon,
    ArrowUpToLineIcon,
    BoldIcon,
    BookOpenIcon,
    CalendarIcon,
    CheckCircle2Icon,
    CheckCircleIcon,
    CheckIcon,
    CheckSquareIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    ChevronsLeftIcon,
    ChevronsRightIcon,
    ChevronsUpDownIcon,
    CircleDotIcon,
    CircleIcon,
    CircleUserIcon,
    CodeIcon,
    ColumnsIcon,
    CopyIcon,
    DatabaseIcon,
    DollarSignIcon,
    DownloadIcon,
    ExternalLinkIcon,
    EyeIcon,
    EyeOffIcon,
    FileIcon,
    FileSearchIcon,
    FileTextIcon,
    FilterIcon,
    FilterXIcon,
    FlagIcon,
    FolderIcon,
    FolderKanbanIcon,
    FolderPlusIcon,
    FolderUpIcon,
    FunctionSquareIcon,
    GitBranchIcon,
    GlobeIcon,
    HashIcon,
    Heading1Icon,
    Heading2Icon,
    Heading3Icon,
    HelpCircleIcon,
    HistoryIcon,
    HomeIcon,
    ImageIcon,
    ImageOffIcon,
    InfoIcon,
    ItalicIcon,
    KanbanIcon,
    KeyIcon,
    KeyRoundIcon,
    LanguagesIcon,
    LayoutGridIcon,
    LinkIcon,
    Link2Icon,
    Unlink2Icon,
    ListIcon,
    LockIcon,
    ListOrderedIcon,
    ListPlusIcon,
    ListTodoIcon,
    LoaderIcon,
    LogOutIcon,
    MailIcon,
    Maximize2Icon,
    MenuIcon,
    MessageCircleIcon,
    MinusCircleIcon,
    MinusIcon,
    MoonIcon,
    MoreVerticalIcon,
    Music2Icon,
    PanelLeftCloseIcon,
    PanelLeftIcon,
    PanelLeftOpenIcon,
    PauseIcon,
    PenLineIcon,
    PencilIcon,
    PhoneIcon,
    PinIcon,
    PlayIcon,
    PlusIcon,
    QuoteIcon,
    RefreshCcwIcon,
    RefreshCwIcon,
    RepeatIcon,
    Rows3Icon,
    SaveIcon,
    SearchIcon,
    SendIcon,
    SettingsIcon,
    ShieldIcon,
    ShoppingCartIcon,
    SlidersHorizontalIcon,
    SquareIcon,
    StarIcon,
    StickyNoteIcon,
    StrikethroughIcon,
    SunIcon,
    SunMoonIcon,
    TableIcon,
    TagIcon,
    TerminalIcon,
    TextIcon,
    Trash2Icon,
    TrendingUpIcon,
    TypeIcon,
    UnderlineIcon,
    UndoIcon,
    UploadCloudIcon,
    UploadIcon,
    UserCheckIcon,
    UserIcon,
    UserPlus,
    UsersIcon,
    VideoIcon,
    VoteIcon,
    Wand2Icon,
    WrenchIcon,
    XCircleIcon,
    XIcon
} from "lucide-react";
