-- A Rebase scaffold's database, exactly as the runtime provisions it at boot.
--
-- NOT hand-written. This is `pg_dump -s` of a database that
-- `packages/cli/templates/template/config/collections/*` was booted against —
-- the four scaffold collections (posts, authors, tags, and the `rebase.users`
-- auth collection), the `posts_tags` junction the many-to-many derives, the
-- auth tables `ensureAuthTablesExist` creates, the `rebase.uid()` / `rebase.roles()`
-- helpers the policies call, and the `rebase_user` role with the DML grants
-- `ensureAppRole` makes. It exists so `scaffold-baseline.e2e.test.ts` can assert
-- what `rls-check` says about a stock Rebase project on day one: the baseline is
-- a product decision (the scaffold's `defaultSecurityRules` grant unfiltered
-- reads on purpose), and a scanner that quietly starts saying something else
-- about it — in either direction — is a regression in one of the two.
--
-- To re-record after a change to the scaffold's collections or to boot-time
-- provisioning:
--
--   1. start an empty Postgres;
--   2. run `ensureAuthTablesExist`, `ensureCollectionTables`, `ensureAppRole`
--      and `ensureCollectionPolicies` (the boot order of
--      `packages/server-postgres/test/e2e/managed-boot-acceptance.test.ts`)
--      against it, with the template's collections and its
--      `defaultSecurityRules` applied by `applyCollectionDefaults`;
--   3. `pg_dump -s`, then drop the pg_dump preamble (comments, `SET`,
--      `set_config`, `\restrict`), the `OWNER TO` lines and the `FOR ROLE
--      <owner>` of the default-privilege grants, so the file applies as
--      whoever runs it.
--
-- Recorded 2026-09-06 against main@c3456d4d2 (package version 0.17.3),
-- PostgreSQL 18.6.

-- `ensureAppRole` creates this; it is a cluster object, so `pg_dump` of one
-- database does not carry it.
CREATE ROLE rebase_user NOLOGIN NOSUPERUSER NOBYPASSRLS NOINHERIT;

CREATE SCHEMA rebase;
CREATE TYPE public.posts_status AS ENUM (
    'draft',
    'review',
    'published'
);
CREATE FUNCTION rebase.is_anonymous() RETURNS boolean
    LANGUAGE sql STABLE
    AS $$
    SELECT COALESCE(NULLIF(current_setting('app.is_anonymous', true), ''), 'false')::boolean;
$$;
CREATE FUNCTION rebase.jwt() RETURNS jsonb
    LANGUAGE sql STABLE
    AS $$
    SELECT COALESCE(
        NULLIF(current_setting('app.jwt', true), ''),
        '{}'
    )::jsonb;
$$;
CREATE FUNCTION rebase.roles() RETURNS text
    LANGUAGE sql STABLE
    AS $$
    SELECT COALESCE(NULLIF(current_setting('app.user_roles', true), ''), '');
$$;
CREATE FUNCTION rebase.uid() RETURNS text
    LANGUAGE sql STABLE
    AS $$
    SELECT COALESCE(
        NULLIF(current_setting('app.uid', true), ''),
        NULLIF(current_setting('app.user_id', true), '')
    );
$$;
CREATE TABLE public.authors (
    id integer NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    picture text
);
ALTER TABLE public.authors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.posts (
    id integer NOT NULL,
    title text NOT NULL,
    content text,
    status public.posts_status,
    author_id integer
);
ALTER TABLE public.posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.posts_tags (
    post_id integer NOT NULL,
    tag_id integer NOT NULL
);
CREATE TABLE public.tags (
    id integer NOT NULL,
    name text NOT NULL
);
ALTER TABLE public.tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE rebase.app_config (
    key text NOT NULL,
    value jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);
CREATE TABLE rebase.magic_link_tokens (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid text NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);
CREATE TABLE rebase.mfa_challenges (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    factor_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    verified_at timestamp with time zone,
    ip_address text,
    attempts integer DEFAULT 0 NOT NULL,
    expires_at timestamp with time zone NOT NULL
);
CREATE TABLE rebase.mfa_factors (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid text NOT NULL,
    factor_type text DEFAULT 'totp'::text NOT NULL,
    secret_encrypted text NOT NULL,
    friendly_name text,
    verified boolean DEFAULT false,
    last_used_counter bigint,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
CREATE TABLE rebase.password_reset_tokens (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid text NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);
CREATE TABLE rebase.recovery_codes (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid text NOT NULL,
    code_hash text NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);
CREATE TABLE rebase.refresh_tokens (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid text NOT NULL,
    session_id text DEFAULT (gen_random_uuid())::text NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked boolean DEFAULT false NOT NULL,
    rotated_at timestamp with time zone,
    session_started_at timestamp with time zone DEFAULT now() NOT NULL,
    user_agent text,
    ip_address text,
    created_at timestamp with time zone DEFAULT now(),
    aal text
);
CREATE TABLE rebase.schema_meta (
    key text NOT NULL,
    value text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE rebase.user_identities (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid text NOT NULL,
    provider text NOT NULL,
    provider_id text NOT NULL,
    profile_data jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
CREATE TABLE rebase.users (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    email text NOT NULL,
    display_name text,
    photo_url text,
    roles text[] DEFAULT '{}'::text[] NOT NULL,
    password_hash text,
    email_verified boolean DEFAULT false NOT NULL,
    email_verification_token text,
    email_verification_sent_at timestamp with time zone,
    is_anonymous boolean DEFAULT false NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    tokens_valid_after timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT users_email_length_check CHECK ((length(email) <= 320))
);
ALTER TABLE ONLY public.authors
    ADD CONSTRAINT authors_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.posts_tags
    ADD CONSTRAINT posts_tags_pkey PRIMARY KEY (post_id, tag_id);
ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);
ALTER TABLE ONLY rebase.app_config
    ADD CONSTRAINT app_config_pkey PRIMARY KEY (key);
ALTER TABLE ONLY rebase.magic_link_tokens
    ADD CONSTRAINT magic_link_tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY rebase.magic_link_tokens
    ADD CONSTRAINT magic_link_tokens_token_hash_key UNIQUE (token_hash);
ALTER TABLE ONLY rebase.mfa_challenges
    ADD CONSTRAINT mfa_challenges_pkey PRIMARY KEY (id);
ALTER TABLE ONLY rebase.mfa_factors
    ADD CONSTRAINT mfa_factors_pkey PRIMARY KEY (id);
ALTER TABLE ONLY rebase.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY rebase.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_token_hash_key UNIQUE (token_hash);
ALTER TABLE ONLY rebase.recovery_codes
    ADD CONSTRAINT recovery_codes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY rebase.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY rebase.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash);
ALTER TABLE ONLY rebase.schema_meta
    ADD CONSTRAINT schema_meta_pkey PRIMARY KEY (key);
ALTER TABLE ONLY rebase.user_identities
    ADD CONSTRAINT user_identities_pkey PRIMARY KEY (id);
ALTER TABLE ONLY rebase.user_identities
    ADD CONSTRAINT user_identities_provider_provider_id_key UNIQUE (provider, provider_id);
ALTER TABLE ONLY rebase.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
CREATE INDEX idx_magic_link_tokens_hash ON rebase.magic_link_tokens USING btree (token_hash);
CREATE INDEX idx_magic_link_tokens_user ON rebase.magic_link_tokens USING btree (uid);
CREATE INDEX idx_mfa_challenges_factor ON rebase.mfa_challenges USING btree (factor_id);
CREATE INDEX idx_mfa_factors_user ON rebase.mfa_factors USING btree (uid);
CREATE INDEX idx_password_reset_tokens_hash ON rebase.password_reset_tokens USING btree (token_hash);
CREATE INDEX idx_password_reset_tokens_user ON rebase.password_reset_tokens USING btree (uid);
CREATE INDEX idx_recovery_codes_user ON rebase.recovery_codes USING btree (uid);
CREATE INDEX idx_refresh_tokens_hash ON rebase.refresh_tokens USING btree (token_hash);
CREATE INDEX idx_refresh_tokens_session ON rebase.refresh_tokens USING btree (session_id);
CREATE INDEX idx_refresh_tokens_user ON rebase.refresh_tokens USING btree (uid);
CREATE INDEX idx_user_identities_user ON rebase.user_identities USING btree (uid);
CREATE UNIQUE INDEX users_email_lower_key ON rebase.users USING btree (lower(email));
CREATE INDEX users_email_verification_token_idx ON rebase.users USING btree (email_verification_token) WHERE (email_verification_token IS NOT NULL);
ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.authors(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.posts_tags
    ADD CONSTRAINT posts_tags_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.posts_tags
    ADD CONSTRAINT posts_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE;
ALTER TABLE ONLY rebase.magic_link_tokens
    ADD CONSTRAINT magic_link_tokens_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY rebase.mfa_challenges
    ADD CONSTRAINT mfa_challenges_factor_id_fkey FOREIGN KEY (factor_id) REFERENCES rebase.mfa_factors(id) ON DELETE CASCADE;
ALTER TABLE ONLY rebase.mfa_factors
    ADD CONSTRAINT mfa_factors_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY rebase.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY rebase.recovery_codes
    ADD CONSTRAINT recovery_codes_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY rebase.refresh_tokens
    ADD CONSTRAINT refresh_tokens_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY rebase.user_identities
    ADD CONSTRAINT user_identities_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;
ALTER TABLE public.authors ENABLE ROW LEVEL SECURITY;
CREATE POLICY authors_default_admin_read ON public.authors FOR SELECT USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY authors_default_admin_write_delete ON public.authors FOR DELETE USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY authors_default_admin_write_insert ON public.authors FOR INSERT WITH CHECK (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY authors_default_admin_write_update ON public.authors FOR UPDATE USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY authors_delete_3561e70_2 ON public.authors FOR DELETE USING ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]));
CREATE POLICY authors_insert_3561e70_0 ON public.authors FOR INSERT WITH CHECK ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]));
CREATE POLICY authors_select_841c287 ON public.authors FOR SELECT USING (true);
CREATE POLICY authors_update_3561e70_1 ON public.authors FOR UPDATE USING ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])) WITH CHECK ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]));
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY posts_default_admin_read ON public.posts FOR SELECT USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY posts_default_admin_write_delete ON public.posts FOR DELETE USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY posts_default_admin_write_insert ON public.posts FOR INSERT WITH CHECK (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY posts_default_admin_write_update ON public.posts FOR UPDATE USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY posts_delete_3561e70_2 ON public.posts FOR DELETE USING ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]));
CREATE POLICY posts_insert_3561e70_0 ON public.posts FOR INSERT WITH CHECK ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]));
CREATE POLICY posts_select_841c287 ON public.posts FOR SELECT USING (true);
ALTER TABLE public.posts_tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY posts_tags_default_admin_read ON public.posts_tags FOR SELECT USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY posts_tags_default_admin_write_delete ON public.posts_tags FOR DELETE USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY posts_tags_default_admin_write_insert ON public.posts_tags FOR INSERT WITH CHECK (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY posts_tags_default_admin_write_update ON public.posts_tags FOR UPDATE USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY posts_tags_default_edge_read ON public.posts_tags FOR SELECT USING (((EXISTS ( SELECT 1
   FROM public.posts _ex0
  WHERE (_ex0.id = posts_tags.post_id))) AND (EXISTS ( SELECT 1
   FROM public.tags _ex1
  WHERE (_ex1.id = posts_tags.tag_id)))));
CREATE POLICY posts_tags_default_edge_write_delete ON public.posts_tags FOR DELETE USING ((EXISTS ( SELECT 1
   FROM public.posts _ex0
  WHERE ((_ex0.id = posts_tags.post_id) AND (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])))));
CREATE POLICY posts_tags_default_edge_write_insert ON public.posts_tags FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM public.posts _ex0
  WHERE ((_ex0.id = posts_tags.post_id) AND (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])))));
CREATE POLICY posts_tags_default_edge_write_update ON public.posts_tags FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM public.posts _ex0
  WHERE ((_ex0.id = posts_tags.post_id) AND (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM public.posts _ex0
  WHERE ((_ex0.id = posts_tags.post_id) AND (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])))));
CREATE POLICY posts_update_3561e70_1 ON public.posts FOR UPDATE USING ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])) WITH CHECK ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]));
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY tags_default_admin_read ON public.tags FOR SELECT USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY tags_default_admin_write_delete ON public.tags FOR DELETE USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY tags_default_admin_write_insert ON public.tags FOR INSERT WITH CHECK (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY tags_default_admin_write_update ON public.tags FOR UPDATE USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY tags_delete_3561e70_2 ON public.tags FOR DELETE USING ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]));
CREATE POLICY tags_insert_3561e70_0 ON public.tags FOR INSERT WITH CHECK ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]));
CREATE POLICY tags_select_841c287 ON public.tags FOR SELECT USING (true);
CREATE POLICY tags_update_3561e70_1 ON public.tags FOR UPDATE USING ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])) WITH CHECK ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]));
ALTER TABLE rebase.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY users_default_admin_read ON rebase.users FOR SELECT USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY users_default_admin_write_delete ON rebase.users FOR DELETE USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY users_default_admin_write_insert ON rebase.users FOR INSERT WITH CHECK (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY users_default_admin_write_update ON rebase.users FOR UPDATE USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY users_default_self_read ON rebase.users FOR SELECT USING ((id = rebase.uid()));
CREATE POLICY users_delete_3561e70_2 ON rebase.users FOR DELETE USING ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]));
CREATE POLICY users_insert_3561e70_0 ON rebase.users FOR INSERT WITH CHECK ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]));
CREATE POLICY users_require_admin_write_delete ON rebase.users AS RESTRICTIVE FOR DELETE USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY users_require_admin_write_insert ON rebase.users AS RESTRICTIVE FOR INSERT WITH CHECK (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY users_require_admin_write_update ON rebase.users AS RESTRICTIVE FOR UPDATE USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));
CREATE POLICY users_select_5f32f06 ON rebase.users FOR SELECT USING ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]));
CREATE POLICY users_update_3561e70_1 ON rebase.users FOR UPDATE USING ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])) WITH CHECK ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]));
GRANT USAGE ON SCHEMA public TO rebase_user;
GRANT USAGE ON SCHEMA rebase TO rebase_user;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.authors TO rebase_user;
GRANT SELECT,USAGE ON SEQUENCE public.authors_id_seq TO rebase_user;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.posts TO rebase_user;
GRANT SELECT,USAGE ON SEQUENCE public.posts_id_seq TO rebase_user;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.posts_tags TO rebase_user;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tags TO rebase_user;
GRANT SELECT,USAGE ON SEQUENCE public.tags_id_seq TO rebase_user;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE rebase.users TO rebase_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT,USAGE ON SEQUENCES TO rebase_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO rebase_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA rebase GRANT SELECT,USAGE ON SEQUENCES TO rebase_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA rebase GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO rebase_user;
