import { describe, expect, it } from "@jest/globals";
import type { CollectionConfig } from "@rebasepro/types";
import { columnTypeDriftMessage, typeFamily, typesAgree } from "./column-type-drift";
import { planCollectionSchemaEnsure, type ExistingSchema } from "./ensure-collection-tables";

describe("reducing a type to its family", () => {
    it("reads both spellings of the same type as one family", () => {
        // The generators emit SQL; `information_schema` reports `udt_name`.
        expect(typeFamily("TIMESTAMP WITH TIME ZONE")).toBe(typeFamily("timestamptz"));
        expect(typeFamily("BOOLEAN")).toBe(typeFamily("bool"));
        expect(typeFamily("DOUBLE PRECISION")).toBe(typeFamily("float8"));
    });

    it("reads both spellings of an array as one family, element-wise", () => {
        expect(typeFamily("NUMERIC[]")).toBe("array:number");
        expect(typeFamily("_numeric")).toBe("array:number");
        expect(typeFamily("TEXT[]")).toBe("array:text");
        expect(typeFamily("_text")).toBe("array:text");
    });

    it("ignores a width, which limits a family rather than being one", () => {
        expect(typeFamily("VARCHAR(255)")).toBe(typeFamily("TEXT"));
        expect(typeFamily("NUMERIC(10, 2)")).toBe(typeFamily("NUMERIC"));
        expect(typeFamily("VECTOR(384)")).toBe("vector");
    });

    it("ignores an identity clause, which is a default and not a type", () => {
        expect(typeFamily("INTEGER GENERATED BY DEFAULT AS IDENTITY")).toBe(typeFamily("int4"));
    });

    it("has no opinion about a type identified by name", () => {
        // An enum, a domain, a PostGIS geometry. Two different names say nothing
        // about whether the values are compatible, so the answer is silence.
        expect(typeFamily('"public"."posts_status"')).toBeNull();
        expect(typeFamily("geometry")).toBeNull();
        expect(typeFamily("")).toBeNull();
        expect(typeFamily(undefined)).toBeNull();
    });
});

describe("deciding whether two types agree", () => {
    /**
     * The noise cases. Every one of these was a plausible drift report that
     * would have fired on a healthy database — an adopted schema with `int4`
     * where `type: "number"` generates `NUMERIC`, a `varchar(255)` from a
     * previous generation of the generator. A boot that warns every time is a
     * boot whose warnings nobody reads.
     */
    it.each([
        ["NUMERIC", "int4"],
        ["INTEGER", "numeric"],
        ["NUMERIC", "float8"],
        ["TEXT", "varchar"],
        ["VARCHAR(255)", "text"],
        ["TEXT", "bpchar"],
        ["NUMERIC[]", "_int4"]
    ])("%s and %s agree", (declared, actual) => {
        expect(typesAgree(declared, actual)).toBe(true);
    });

    it("agrees with anything when either side is unrecognised", () => {
        expect(typesAgree("JSONB", "geometry")).toBe(true);
        expect(typesAgree('"public"."posts_status"', "text")).toBe(true);
    });

    /**
     * The case this exists for, exactly as it was met: a property declared
     * `columnType: "jsonb"` over a column the first deploy created as
     * `numeric[]`. Every write of the declared shape was rejected by Postgres,
     * every write of the Postgres shape was rejected by the API's own validator
     * first, and the deploy that caused it reported success.
     */
    it.each([
        ["JSONB", "_numeric"],
        ["NUMERIC[]", "jsonb"],
        ["JSONB", "text"],
        ["TEXT[]", "_numeric"],
        ["JSONB", "json"],
        ["VECTOR(384)", "_numeric"],
        ["TIMESTAMP WITH TIME ZONE", "date"],
        ["UUID", "text"]
    ])("%s and %s do not agree", (declared, actual) => {
        expect(typesAgree(declared, actual)).toBe(false);
    });
});

describe("the plan reporting a drifted column", () => {
    const observations = {
        name: "Listing observations",
        slug: "listing_observations",
        properties: {
            id: { name: "ID", type: "string", isId: "uuid" },
            descriptionEmbedding: { name: "Embedding", type: "map", properties: {} }
        }
    } as unknown as CollectionConfig;

    /** The table as the FIRST deploy created it: an array, not a document. */
    const asDeployed = (): ExistingSchema => ({
        tables: new Map([["public.listing_observations", new Set(["id", "description_embedding"])]]),
        enums: new Set(),
        columnTypes: new Map([
            ["public.listing_observations.id", "uuid"],
            ["public.listing_observations.description_embedding", "_numeric"]
        ])
    });

    it("names the column, both types, and plans nothing", () => {
        const plan = planCollectionSchemaEnsure([observations], asDeployed());

        expect(plan.columnTypeDrift).toHaveLength(1);
        expect(plan.columnTypeDrift[0]).toMatchObject({
            table: "public.listing_observations",
            column: "description_embedding",
            declared: "JSONB",
            actual: "_numeric"
        });
        // Reported, not acted on: no statement in the plan touches the type.
        expect(plan.statements.some(s => /ALTER COLUMN .* TYPE/i.test(s))).toBe(false);
    });

    it("says nothing when the database agrees with the declaration", () => {
        const agreeing = asDeployed();
        agreeing.columnTypes!.set("public.listing_observations.description_embedding", "jsonb");

        expect(planCollectionSchemaEnsure([observations], agreeing).columnTypeDrift).toEqual([]);
    });

    it("says nothing about a column it is creating, which cannot have drifted", () => {
        const plan = planCollectionSchemaEnsure([observations], {
            tables: new Map(),
            enums: new Set()
        });
        expect(plan.columnTypeDrift).toEqual([]);
    });

    it("says nothing when the live types were never read", () => {
        // `columnTypes` absent means "unknown", and unknown must not report.
        const blind = asDeployed();
        delete blind.columnTypes;
        expect(planCollectionSchemaEnsure([observations], blind).columnTypeDrift).toEqual([]);
    });

    it("hands the operator a statement they can run", () => {
        const message = columnTypeDriftMessage({
            table: "public.listing_observations",
            column: "description_embedding",
            declared: "JSONB",
            actual: "_numeric"
        });

        expect(message).toContain("is _numeric in the database");
        expect(message).toContain("declares JSONB");
        expect(message).toContain(
            'ALTER TABLE "public"."listing_observations" ALTER COLUMN "description_embedding" TYPE JSONB'
        );
    });
});
