/**
 * A column whose type in the database is not the type the collection declares.
 *
 * The boot ensure is additive: it creates tables, columns, enum values and
 * indexes, and it never changes an existing column's type. That is the right
 * default — an automatic `ALTER COLUMN … TYPE` against customer data, decided
 * by a process nobody is watching, is not a thing to do quietly.
 *
 * What was wrong is that it happened *silently*. A property's `columnType`
 * changed after the first deploy, the deploy reported success, the column stayed
 * as it was, and the divergence surfaced later as writes failing:
 *
 *     Invalid data format in "listing_observations":
 *       malformed array literal: "[0,0,0.0755,…]"
 *
 * ...after a 10,690-row import, from a deployment that had said "success". The
 * two ends disagreed about the schema, so no value satisfied both: the declared
 * shape was rejected by Postgres and the Postgres shape was rejected by the
 * API's own validator, first. There is no encoding out of that, only a report.
 *
 * ## Why the comparison is deliberately blunt
 *
 * A drift report that cries wolf is worse than none, because the boot that says
 * it every time is the boot nobody reads. So types are compared by *family*, and
 * a family is only split from another when the difference changes what the
 * column can hold:
 *
 *  - every numeric type is one family. `int4`, `numeric` and `float8` all arrive
 *    as JavaScript numbers and accept each other's values; a database adopted
 *    from an existing schema legitimately has `int4` where `type: "number"`
 *    generates `NUMERIC`, and that is not news.
 *  - every character type is one family, for the same reason: `text`,
 *    `varchar(255)` and `char(3)` differ in what they *reject*, not in shape.
 *  - `jsonb` and an array are different families, and that is the case this
 *    exists for.
 *
 * Anything this module does not recognise — an enum type, a domain, a PostGIS
 * geometry, an extension type it has never met — returns `null` and is compared
 * with nothing. Silence on an unknown type is the deliberate choice: the cost of
 * a missed report is a question somebody asks once, and the cost of a false one
 * is a warning everybody learns to skip.
 */

/** A column whose live type and declared type are in different families. */
export interface ColumnTypeDrift {
    /** `schema.table`. */
    table: string;
    /** The column name as it exists in the database. */
    column: string;
    /** What the collection says the column should be, e.g. `JSONB`. */
    declared: string;
    /** What the database actually has, as `udt_name` reports it, e.g. `_numeric`. */
    actual: string;
}

/**
 * Types that mean the same thing to everything above the driver.
 *
 * Keyed by every spelling either side can produce: `information_schema` reports
 * `udt_name` (`int4`, `_numeric`, `bpchar`), while the generators emit SQL
 * (`INTEGER`, `NUMERIC[]`, `CHAR(3)`). Both are normalised through here.
 */
const FAMILIES: Record<string, string> = {
    // Numbers. One family on purpose — see the note above.
    int2: "number", smallint: "number",
    int4: "number", int: "number", integer: "number",
    int8: "number", bigint: "number",
    numeric: "number", decimal: "number",
    float4: "number", real: "number",
    float8: "number", "double precision": "number",
    money: "number",

    // Characters. Also one family: the differences are limits, not shapes.
    text: "text", varchar: "text", "character varying": "text",
    bpchar: "text", char: "text", character: "text", citext: "text",

    bool: "boolean", boolean: "boolean",

    json: "json",
    jsonb: "jsonb",

    uuid: "uuid",
    bytea: "bytea",

    date: "date",
    time: "time", "time without time zone": "time",
    timetz: "time", "time with time zone": "time",
    timestamp: "timestamp", "timestamp without time zone": "timestamp",
    timestamptz: "timestamptz", "timestamp with time zone": "timestamptz",
    interval: "interval",

    tsvector: "tsvector",
    vector: "vector",
    halfvec: "halfvec",
    sparsevec: "sparsevec"
};

/**
 * One SQL or `udt_name` spelling reduced to its family, or `null` when this
 * module has no opinion about it.
 *
 * `null` is not a failure. It is the answer for an enum type, a domain, a
 * PostGIS column, a quoted qualified name — everything whose identity is a
 * *name* rather than a shape, where two spellings being different says nothing
 * about whether the values are compatible.
 */
export function typeFamily(raw: string | undefined | null): string | null {
    if (!raw) return null;
    let type = raw.trim().toLowerCase();
    if (!type) return null;

    // `"public"."posts_status"` — an enum, identified by name. Not comparable.
    if (type.startsWith("\"")) return null;

    // `INTEGER GENERATED BY DEFAULT AS IDENTITY` is an `int4` with a default
    // attached; the identity clause is not part of the type.
    const generated = type.indexOf(" generated ");
    if (generated > 0) type = type.slice(0, generated).trim();

    // Arrays, in both spellings: `NUMERIC[]` from the generators, `_numeric`
    // from `udt_name`. Compared element-wise, so `text[]` and `numeric[]` are
    // different and `int4[]` and `numeric[]` are not.
    if (type.endsWith("[]")) {
        const element = typeFamily(type.slice(0, -2));
        return element && `array:${element}`;
    }
    if (type.startsWith("_")) {
        const element = typeFamily(type.slice(1));
        return element && `array:${element}`;
    }

    // `VARCHAR(255)`, `VECTOR(384)`, `NUMERIC(10, 2)` — the width is a limit on
    // a family, not a family. A vector whose *dimensions* changed is a separate
    // concern with its own handling in the ensure.
    const paren = type.indexOf("(");
    if (paren > 0) type = type.slice(0, paren).trim();

    return FAMILIES[type] ?? null;
}

/**
 * Do these two spellings describe columns that hold the same kind of value?
 *
 * `true` whenever the answer is not confidently "no" — an unrecognised type on
 * either side agrees with everything, because a report needs evidence and an
 * unknown type is the absence of it.
 */
export function typesAgree(declared: string, actual: string): boolean {
    const a = typeFamily(declared);
    const b = typeFamily(actual);
    if (a === null || b === null) return true;
    return a === b;
}

/**
 * The sentence a boot log says about one drifted column.
 *
 * Written to be actionable in the place it is read, which is a runtime log with
 * no way to run a migration from it: it names both types, says which surface
 * will break first, and gives the statement that resolves it.
 */
export function columnTypeDriftMessage(drift: ColumnTypeDrift): string {
    const [schema, table] = drift.table.split(".");
    return (
        `Column "${drift.table}"."${drift.column}" is ${drift.actual} in the database, but this ` +
        `collection declares ${drift.declared}. Boot does not change an existing column's type, so ` +
        "the database keeps what it has and writes that match the declaration will be rejected by " +
        "Postgres. Change it deliberately, when you can watch it:\n" +
        `    ALTER TABLE "${schema}"."${table}" ALTER COLUMN "${drift.column}" ` +
        `TYPE ${drift.declared} USING "${drift.column}"::${drift.declared};`
    );
}
