/**
 * rls-check's own output, verbatim — captured from `@rebasepro/rls-check`
 * 0.18.1 run against a PostgreSQL 18 database built to the story's shape
 * (nine tables, granted to anon/authenticated, owned by a login role), on a
 * 72-column terminal. BEFORE is the database as the agent left it: no
 * row-level security anywhere. AFTER is the same database after `db push`
 * applied the generated `drizzle/policies.sql`, then FORCE ROW LEVEL
 * SECURITY on every table (see the note on that in Hook.tsx).
 *
 * Nothing is edited. The lines after the exit code — the timestamp and the
 * footer — are left off the end because the window is bottom-anchored and
 * the exit code is the line the story needs in view.
 */
export const SCAN_BEFORE: string[] = [
    "rls-check 0.18.1  ·  read-only Row-Level Security audit",
    "────────────────────────────────────────────────────────────────────────",
    "",
    "Database  localhost:5432/acme",
    "Server    PostgreSQL 18.4 (Homebrew)",
    "Platform  Rebase",
    "Exposed   PUBLIC, anon, authenticated, rebase_user (add yours with --role)",
    "Scanned   2 schemas · 9 tables · 0 policies · 15 checks",
    "",
    "Note  This scan connected as a role that row-level security cannot",
    "      constrain — a superuser, a table owner, or a role with",
    "      BYPASSRLS. That is why it can read the true catalog, and it is",
    "      also why nothing below describes what this connection",
    "      experiences. The findings are about what OTHER roles get.",
    "",
    "CRITICAL  ·  9 findings",
    "────────────────────────────────────────────────────────────────────────",
    "",
    "  [critical] rls-disabled  public.authors",
    "      public.authors has row-level security disabled and is granted to",
    "      anon, authenticated and rebase_user",
    "",
    "      Row-level security is not enabled on this table, so Postgres",
    "      applies no per-row filter at all — policies, if any exist, are",
    "      never consulted. anon, authenticated and rebase_user hold DELETE,",
    "      INSERT, SELECT and UPDATE on it.",
    "      Impact  If this table is reachable over an API that connects as",
    "              anon, authenticated and rebase_user, a caller can read",
    "              every row and delete, insert and update any row, with no",
    "              tenant or owner scoping.",
    "      Fix",
    "          ALTER TABLE \"public\".\"authors\" ENABLE ROW LEVEL SECURITY;",
    "          -- Enabling RLS with no policies denies every row to everyone but the owner,",
    "          -- so add the policy you intend in the same migration, for example:",
    "          -- CREATE POLICY \"authors_owner_select\" ON \"public\".\"authors\"",
    "          --     FOR SELECT TO \"anon\" USING (user_id = rebase.uid());",
    "      Docs    https://rebase.pro/docs/rls-check#rls-disabled",
    "",
    "  [critical] rls-disabled  public.customers",
    "      public.customers has row-level security disabled and is granted to",
    "      anon, authenticated and rebase_user",
    "",
    "      Row-level security is not enabled on this table, so Postgres",
    "      applies no per-row filter at all — policies, if any exist, are",
    "      never consulted. anon, authenticated and rebase_user hold DELETE,",
    "      INSERT, SELECT and UPDATE on it.",
    "      Impact  If this table is reachable over an API that connects as",
    "              anon, authenticated and rebase_user, a caller can read",
    "              every row and delete, insert and update any row, with no",
    "              tenant or owner scoping.",
    "      Fix",
    "          ALTER TABLE \"public\".\"customers\" ENABLE ROW LEVEL SECURITY;",
    "          -- Enabling RLS with no policies denies every row to everyone but the owner,",
    "          -- so add the policy you intend in the same migration, for example:",
    "          -- CREATE POLICY \"customers_owner_select\" ON \"public\".\"customers\"",
    "          --     FOR SELECT TO \"anon\" USING (user_id = rebase.uid());",
    "      Docs    https://rebase.pro/docs/rls-check#rls-disabled",
    "",
    "  [critical] rls-disabled  public.order_items",
    "      public.order_items has row-level security disabled and is granted",
    "      to anon, authenticated and rebase_user",
    "",
    "      Row-level security is not enabled on this table, so Postgres",
    "      applies no per-row filter at all — policies, if any exist, are",
    "      never consulted. anon, authenticated and rebase_user hold DELETE,",
    "      INSERT, SELECT and UPDATE on it.",
    "      Impact  If this table is reachable over an API that connects as",
    "              anon, authenticated and rebase_user, a caller can read",
    "              every row and delete, insert and update any row, with no",
    "              tenant or owner scoping.",
    "      Fix",
    "          ALTER TABLE \"public\".\"order_items\" ENABLE ROW LEVEL SECURITY;",
    "          -- Enabling RLS with no policies denies every row to everyone but the owner,",
    "          -- so add the policy you intend in the same migration, for example:",
    "          -- CREATE POLICY \"order_items_owner_select\" ON \"public\".\"order_items\"",
    "          --     FOR SELECT TO \"anon\" USING (user_id = rebase.uid());",
    "      Docs    https://rebase.pro/docs/rls-check#rls-disabled",
    "",
    "  [critical] rls-disabled  public.orders",
    "      public.orders has row-level security disabled and is granted to",
    "      anon, authenticated and rebase_user",
    "",
    "      Row-level security is not enabled on this table, so Postgres",
    "      applies no per-row filter at all — policies, if any exist, are",
    "      never consulted. anon, authenticated and rebase_user hold DELETE,",
    "      INSERT, SELECT and UPDATE on it.",
    "      Impact  If this table is reachable over an API that connects as",
    "              anon, authenticated and rebase_user, a caller can read",
    "              every row and delete, insert and update any row, with no",
    "              tenant or owner scoping.",
    "      Fix",
    "          ALTER TABLE \"public\".\"orders\" ENABLE ROW LEVEL SECURITY;",
    "          -- Enabling RLS with no policies denies every row to everyone but the owner,",
    "          -- so add the policy you intend in the same migration, for example:",
    "          -- CREATE POLICY \"orders_owner_select\" ON \"public\".\"orders\"",
    "          --     FOR SELECT TO \"anon\" USING (user_id = rebase.uid());",
    "      Docs    https://rebase.pro/docs/rls-check#rls-disabled",
    "",
    "  [critical] rls-disabled  public.posts",
    "      public.posts has row-level security disabled and is granted to",
    "      anon, authenticated and rebase_user",
    "",
    "      Row-level security is not enabled on this table, so Postgres",
    "      applies no per-row filter at all — policies, if any exist, are",
    "      never consulted. anon, authenticated and rebase_user hold DELETE,",
    "      INSERT, SELECT and UPDATE on it.",
    "      Impact  If this table is reachable over an API that connects as",
    "              anon, authenticated and rebase_user, a caller can read",
    "              every row and delete, insert and update any row, with no",
    "              tenant or owner scoping.",
    "      Fix",
    "          ALTER TABLE \"public\".\"posts\" ENABLE ROW LEVEL SECURITY;",
    "          -- Enabling RLS with no policies denies every row to everyone but the owner,",
    "          -- so add the policy you intend in the same migration, for example:",
    "          -- CREATE POLICY \"posts_owner_select\" ON \"public\".\"posts\"",
    "          --     FOR SELECT TO \"anon\" USING (user_id = rebase.uid());",
    "      Docs    https://rebase.pro/docs/rls-check#rls-disabled",
    "",
    "  [critical] rls-disabled  public.products",
    "      public.products has row-level security disabled and is granted to",
    "      anon, authenticated and rebase_user",
    "",
    "      Row-level security is not enabled on this table, so Postgres",
    "      applies no per-row filter at all — policies, if any exist, are",
    "      never consulted. anon, authenticated and rebase_user hold DELETE,",
    "      INSERT, SELECT and UPDATE on it.",
    "      Impact  If this table is reachable over an API that connects as",
    "              anon, authenticated and rebase_user, a caller can read",
    "              every row and delete, insert and update any row, with no",
    "              tenant or owner scoping.",
    "      Fix",
    "          ALTER TABLE \"public\".\"products\" ENABLE ROW LEVEL SECURITY;",
    "          -- Enabling RLS with no policies denies every row to everyone but the owner,",
    "          -- so add the policy you intend in the same migration, for example:",
    "          -- CREATE POLICY \"products_owner_select\" ON \"public\".\"products\"",
    "          --     FOR SELECT TO \"anon\" USING (user_id = rebase.uid());",
    "      Docs    https://rebase.pro/docs/rls-check#rls-disabled",
    "",
    "  [critical] rls-disabled  public.tags",
    "      public.tags has row-level security disabled and is granted to",
    "      anon, authenticated and rebase_user",
    "",
    "      Row-level security is not enabled on this table, so Postgres",
    "      applies no per-row filter at all — policies, if any exist, are",
    "      never consulted. anon, authenticated and rebase_user hold DELETE,",
    "      INSERT, SELECT and UPDATE on it.",
    "      Impact  If this table is reachable over an API that connects as",
    "              anon, authenticated and rebase_user, a caller can read",
    "              every row and delete, insert and update any row, with no",
    "              tenant or owner scoping.",
    "      Fix",
    "          ALTER TABLE \"public\".\"tags\" ENABLE ROW LEVEL SECURITY;",
    "          -- Enabling RLS with no policies denies every row to everyone but the owner,",
    "          -- so add the policy you intend in the same migration, for example:",
    "          -- CREATE POLICY \"tags_owner_select\" ON \"public\".\"tags\"",
    "          --     FOR SELECT TO \"anon\" USING (user_id = rebase.uid());",
    "      Docs    https://rebase.pro/docs/rls-check#rls-disabled",
    "",
    "  [critical] rls-disabled  public.tickets",
    "      public.tickets has row-level security disabled and is granted to",
    "      anon, authenticated and rebase_user",
    "",
    "      Row-level security is not enabled on this table, so Postgres",
    "      applies no per-row filter at all — policies, if any exist, are",
    "      never consulted. anon, authenticated and rebase_user hold DELETE,",
    "      INSERT, SELECT and UPDATE on it.",
    "      Impact  If this table is reachable over an API that connects as",
    "              anon, authenticated and rebase_user, a caller can read",
    "              every row and delete, insert and update any row, with no",
    "              tenant or owner scoping.",
    "      Fix",
    "          ALTER TABLE \"public\".\"tickets\" ENABLE ROW LEVEL SECURITY;",
    "          -- Enabling RLS with no policies denies every row to everyone but the owner,",
    "          -- so add the policy you intend in the same migration, for example:",
    "          -- CREATE POLICY \"tickets_owner_select\" ON \"public\".\"tickets\"",
    "          --     FOR SELECT TO \"anon\" USING (user_id = rebase.uid());",
    "      Docs    https://rebase.pro/docs/rls-check#rls-disabled",
    "",
    "  [critical] rls-disabled  public.users",
    "      public.users has row-level security disabled and is granted to",
    "      anon, authenticated and rebase_user",
    "",
    "      Row-level security is not enabled on this table, so Postgres",
    "      applies no per-row filter at all — policies, if any exist, are",
    "      never consulted. anon, authenticated and rebase_user hold DELETE,",
    "      INSERT, SELECT and UPDATE on it.",
    "      Impact  If this table is reachable over an API that connects as",
    "              anon, authenticated and rebase_user, a caller can read",
    "              every row and delete, insert and update any row, with no",
    "              tenant or owner scoping.",
    "      Fix",
    "          ALTER TABLE \"public\".\"users\" ENABLE ROW LEVEL SECURITY;",
    "          -- Enabling RLS with no policies denies every row to everyone but the owner,",
    "          -- so add the policy you intend in the same migration, for example:",
    "          -- CREATE POLICY \"users_owner_select\" ON \"public\".\"users\"",
    "          --     FOR SELECT TO \"anon\" USING (user_id = rebase.uid());",
    "      Docs    https://rebase.pro/docs/rls-check#rls-disabled",
    "",
    "────────────────────────────────────────────────────────────────────────",
    "Summary",
    "",
    "  critical 9   high 0   medium 0   low 0   info 0",
    "  9 confirmed · 0 worth checking · 15 checks run against 9 tables in 2 schemas",
    "  9 of 9 tables have row-level security disabled",
    "",
    "  Exit code 1 — at least one finding is \"high\" or worse (--fail-on high)."
    ];

export const SCAN_AFTER: string[] = [
    "rls-check 0.18.1  ·  read-only Row-Level Security audit",
    "────────────────────────────────────────────────────────────────────────",
    "",
    "Database  localhost:5432/acme",
    "Server    PostgreSQL 18.4 (Homebrew)",
    "Platform  Rebase",
    "Exposed   PUBLIC, anon, authenticated, rebase_user (add yours with --role)",
    "Scanned   2 schemas · 9 tables · 37 policies · 15 checks",
    "",
    "Note  This scan connected as a role that row-level security cannot",
    "      constrain — a superuser, a table owner, or a role with",
    "      BYPASSRLS. That is why it can read the true catalog, and it is",
    "      also why nothing below describes what this connection",
    "      experiences. The findings are about what OTHER roles get.",
    "",
    "No findings. Every table, view and policy in scope passed all checks.",
    "",
    "────────────────────────────────────────────────────────────────────────",
    "Summary",
    "",
    "  critical 0   high 0   medium 0   low 0   info 0",
    "  0 confirmed · 0 worth checking · 15 checks run against 9 tables in 2 schemas",
    "",
    "  Exit code 0 — nothing at or above \"high\" (--fail-on high)."
    ];
