// This file is auto-generated by the Rebase Drizzle generator. Do not edit manually.

import { primaryKey, pgTable, integer, varchar, text, char, boolean, timestamp, date, time, jsonb, json, pgEnum, numeric, real, doublePrecision, bigint, serial, bigserial, pgPolicy, uuid, pgSchema } from 'drizzle-orm/pg-core';
import { relations as drizzleRelations, sql } from 'drizzle-orm';

export const rebaseSchema = pgSchema("rebase");

export const exercisesDifficulty = pgEnum("exercises_difficulty", ['beginner', 'intermediate', 'advanced']);
export const exercisesCategory = pgEnum("exercises_category", ['strength', 'cardio', 'flexibility', 'balance', 'plyometrics', 'calisthenics']);
export const exercisesStatus = pgEnum("exercises_status", ['draft', 'published', 'archived']);
export const ordersStatus = pgEnum("orders_status", ['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded']);
export const ordersPayment_status = pgEnum("orders_payment_status", ['unpaid', 'paid', 'partially_refunded', 'refunded']);
export const ordersCurrency = pgEnum("orders_currency", ['USD', 'EUR', 'GBP', 'CAD', 'AUD']);
export const postsStatus = pgEnum("posts_status", ['draft', 'needs_review', 'published', 'archived']);
export const productsCategory = pgEnum("products_category", ['electronics', 'clothing', 'home_garden', 'sports', 'books', 'food_beverage', 'health_beauty', 'toys']);
export const productsStatus = pgEnum("products_status", ['draft', 'active', 'archived']);
export const ticketsStatus = pgEnum("tickets_status", ['open', 'in_progress', 'waiting', 'resolved', 'closed']);
export const ticketsPriority = pgEnum("tickets_priority", ['low', 'medium', 'high', 'urgent']);
export const ticketsCategory = pgEnum("tickets_category", ['bug', 'feature_request', 'question', 'billing', 'account', 'other']);

export const authors = pgTable("authors", {
    id: uuid("id").primaryKey().defaultRandom(),
    name: varchar("name").notNull(),
    email: varchar("email").notNull(),
    picture: varchar("picture"),
    bio: text("bio"),
    twitter: varchar("twitter"),
    github: varchar("github"),
    website: varchar("website"),
    userId: varchar("user_id")
}, (table) => ([
    pgPolicy("authors_public_access", { as: "permissive", for: "all", to: ["public"], using: sql`true`, withCheck: sql`true` }),
])).enableRLS();

export const customers = pgTable("customers", {
    id: uuid("id").primaryKey().defaultRandom(),
    first_name: varchar("first_name").notNull(),
    last_name: varchar("last_name").notNull(),
    email: varchar("email").unique().notNull(),
    phone: varchar("phone"),
    avatar: varchar("avatar"),
    company: varchar("company"),
    is_vip: boolean("is_vip"),
    lifetime_value: numeric("lifetime_value"),
    total_orders: numeric("total_orders"),
    shipping_address: text("shipping_address"),
    billing_address: text("billing_address"),
    notes: text("notes"),
    created_at: timestamp("created_at", { withTimezone: true, mode: 'string' }).default(sql`now()`),
    updated_at: timestamp("updated_at", { withTimezone: true, mode: 'string' }).default(sql`now()`)
}, (table) => ([
    pgPolicy("test_policy", { as: "permissive", for: "all", to: ["authenticated"], using: sql`true`, withCheck: sql`true` }),
])).enableRLS();

export const exercises = pgTable("exercises", {
    id: uuid("id").primaryKey().defaultRandom(),
    name: varchar("name").notNull(),
    description: text("description"),
    images: text("images").array(),
    video_url: varchar("video_url"),
    difficulty: exercisesDifficulty("difficulty").notNull(),
    category: exercisesCategory("category").notNull(),
    equipment: text("equipment").array(),
    body_parts: text("body_parts").array(),
    instructions: text("instructions"),
    default_reps: numeric("default_reps"),
    default_sets: numeric("default_sets"),
    rest_seconds: numeric("rest_seconds"),
    calories_per_minute: numeric("calories_per_minute"),
    is_compound: boolean("is_compound"),
    is_featured: boolean("is_featured"),
    status: exercisesStatus("status").notNull(),
    created_at: timestamp("created_at", { withTimezone: true, mode: 'string' }).default(sql`now()`),
    updated_at: timestamp("updated_at", { withTimezone: true, mode: 'string' }).default(sql`now()`)
}, (table) => ([
    pgPolicy("test_policy", { as: "permissive", for: "all", to: ["authenticated"], using: sql`true`, withCheck: sql`true` }),
])).enableRLS();

export const orderItems = pgTable("order_items", {
    id: uuid("id").primaryKey().defaultRandom(),
    order_id: uuid("order_id").references(() => orders.id, { onDelete: "cascade" }),
    product_id: uuid("product_id").references(() => products.id, { onDelete: "restrict" }),
    product_name: varchar("product_name"),
    sku: varchar("sku"),
    quantity: numeric("quantity").notNull(),
    unit_price: numeric("unit_price"),
    line_total: numeric("line_total")
}, (table) => ([
    pgPolicy("test_policy", { as: "permissive", for: "all", to: ["authenticated"], using: sql`true`, withCheck: sql`true` }),
])).enableRLS();

export const orders = pgTable("orders", {
    id: uuid("id").primaryKey().defaultRandom(),
    order_number: varchar("order_number").unique().notNull(),
    customer_id: uuid("customer_id").references(() => customers.id, { onDelete: "cascade" }).notNull(),
    status: ordersStatus("status").notNull(),
    payment_status: ordersPayment_status("payment_status").notNull(),
    subtotal: numeric("subtotal"),
    tax_amount: numeric("tax_amount"),
    shipping_cost: numeric("shipping_cost"),
    discount_amount: numeric("discount_amount"),
    total: numeric("total"),
    currency: ordersCurrency("currency"),
    shipping_address: text("shipping_address"),
    tracking_number: varchar("tracking_number"),
    notes: text("notes"),
    order_date: timestamp("order_date", { withTimezone: true, mode: 'string' }).notNull(),
    shipped_date: timestamp("shipped_date", { withTimezone: true, mode: 'string' }),
    delivered_date: timestamp("delivered_date", { withTimezone: true, mode: 'string' }),
    created_at: timestamp("created_at", { withTimezone: true, mode: 'string' }).default(sql`now()`),
    updated_at: timestamp("updated_at", { withTimezone: true, mode: 'string' }).default(sql`now()`)
}, (table) => ([
    pgPolicy("test_policy", { as: "permissive", for: "all", to: ["authenticated"], using: sql`true`, withCheck: sql`true` }),
])).enableRLS();

export const posts = pgTable("posts", {
    id: uuid("id").primaryKey().defaultRandom(),
    title: varchar("title").notNull(),
    slug: varchar("slug").unique().notNull(),
    hero_image: varchar("hero_image"),
    excerpt: text("excerpt"),
    content: jsonb("content"),
    status: postsStatus("status").notNull(),
    publish_date: timestamp("publish_date", { withTimezone: true, mode: 'string' }),
    created_at: timestamp("created_at", { withTimezone: true, mode: 'string' }).default(sql`now()`),
    updated_at: timestamp("updated_at", { withTimezone: true, mode: 'string' }).default(sql`now()`),
    author_id: uuid("author_id").references(() => authors.id, { onDelete: "set null" })
}, (table) => ([
    pgPolicy("test_policy", { as: "permissive", for: "all", to: ["public"], using: sql`true`, withCheck: sql`true` }),
])).enableRLS();

export const postsTags = pgTable("posts_tags", {
    post_id: uuid("post_id").notNull().references(() => posts.id, { onDelete: "cascade" }),
    tag_id: uuid("tag_id").notNull().references(() => tags.id, { onDelete: "cascade" }),
}, (table) => ({
    pk: primaryKey({ columns: [table.post_id, table.tag_id] })
}));

export const productLocales = pgTable("product_locales", {
    id: uuid("id").primaryKey().defaultRandom().notNull(),
    product_id: uuid("product_id").references(() => products.id, { onDelete: "set null" }),
    locale: varchar("locale").notNull(),
    name: varchar("name"),
    description: text("description")
}, (table) => ([
    pgPolicy("product_locales_public_access", { as: "permissive", for: "all", to: ["authenticated"], using: sql`true`, withCheck: sql`true` }),
])).enableRLS();

export const products = pgTable("products", {
    id: uuid("id").primaryKey().defaultRandom(),
    name: varchar("name").notNull(),
    sku: varchar("sku").unique().notNull(),
    description: text("description"),
    images: text("images").array(),
    available_locales: text("available_locales").array(),
    brand: varchar("brand"),
    category: productsCategory("category").notNull(),
    price: numeric("price").notNull(),
    compare_at_price: numeric("compare_at_price"),
    cost: numeric("cost"),
    stock_quantity: numeric("stock_quantity").notNull(),
    low_stock_threshold: numeric("low_stock_threshold"),
    weight_grams: numeric("weight_grams"),
    rating: numeric("rating"),
    review_count: numeric("review_count"),
    status: productsStatus("status").notNull(),
    is_featured: boolean("is_featured"),
    created_at: timestamp("created_at", { withTimezone: true, mode: 'string' }).default(sql`now()`),
    updated_at: timestamp("updated_at", { withTimezone: true, mode: 'string' }).default(sql`now()`)
}, (table) => ([
    pgPolicy("test_policy", { as: "permissive", for: "all", to: ["authenticated"], using: sql`true`, withCheck: sql`true` }),
])).enableRLS();

export const tags = pgTable("tags", {
    id: uuid("id").primaryKey().defaultRandom().notNull(),
    name: varchar("name").notNull()
}, (table) => ([
    pgPolicy("tags_public_access", { as: "permissive", for: "all", to: ["authenticated"], using: sql`true`, withCheck: sql`true` }),
])).enableRLS();

export const tickets = pgTable("tickets", {
    id: uuid("id").primaryKey().defaultRandom(),
    ticket_number: varchar("ticket_number").unique().notNull(),
    subject: varchar("subject").notNull(),
    description: text("description"),
    resolution_notes: text("resolution_notes"),
    status: ticketsStatus("status").notNull(),
    priority: ticketsPriority("priority").notNull(),
    category: ticketsCategory("category"),
    customer_id: uuid("customer_id").references(() => customers.id, { onDelete: "set null" }),
    assigned_to: varchar("assigned_to"),
    created_at: timestamp("created_at", { withTimezone: true, mode: 'string' }).default(sql`now()`),
    updated_at: timestamp("updated_at", { withTimezone: true, mode: 'string' }).default(sql`now()`),
    __order: varchar("order")
}, (table) => ([
    pgPolicy("test_policy", { as: "permissive", for: "all", to: ["authenticated"], using: sql`true`, withCheck: sql`true` }),
])).enableRLS();

export const users = rebaseSchema.table("users", {
    id: uuid("id").primaryKey().defaultRandom(),
    email: varchar("email").unique().notNull(),
    displayName: varchar("display_name"),
    photoURL: varchar("photo_url"),
    roles: text("roles").array(),
    passwordHash: varchar("password_hash"),
    emailVerified: boolean("email_verified"),
    emailVerificationToken: varchar("email_verification_token"),
    emailVerificationSentAt: timestamp("email_verification_sent_at", { withTimezone: true, mode: 'string' }),
    metadata: jsonb("metadata"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).default(sql`now()`)
}, (table) => ([
    pgPolicy("users_read_policy", { as: "permissive", for: "select", to: ["public"], using: sql`auth.uid() IS NULL OR id = auth.uid()::uuid OR string_to_array(auth.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("users_write_policy_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("users_write_policy_update", { as: "permissive", for: "update", to: ["public"], using: sql`auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']`, withCheck: sql`auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("users_write_policy_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("users_default_admin_write_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("users_default_admin_write_update", { as: "permissive", for: "update", to: ["public"], using: sql`auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']`, withCheck: sql`auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("users_default_admin_write_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("users_require_admin_write_insert", { as: "restrictive", for: "insert", to: ["public"], withCheck: sql`auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("users_require_admin_write_update", { as: "restrictive", for: "update", to: ["public"], using: sql`auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']`, withCheck: sql`auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("users_require_admin_write_delete", { as: "restrictive", for: "delete", to: ["public"], using: sql`auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']` }),
])).enableRLS();

export const authorsRelations = drizzleRelations(authors, ({ one, many }) => ({
    "posts": many(posts, { relationName: "posts_author_id" })
}));

export const customersRelations = drizzleRelations(customers, ({ one, many }) => ({
    "orders": many(orders, { relationName: "orders_customer_id" })
}));

export const orderItemsRelations = drizzleRelations(orderItems, ({ one, many }) => ({
    "order": one(orders, {
        fields: [orderItems.order_id],
        references: [orders.id],
        relationName: "order_items_order_id"
    }),
    "product": one(products, {
        fields: [orderItems.product_id],
        references: [products.id],
        relationName: "order_items_product_id"
    })
}));

export const ordersRelations = drizzleRelations(orders, ({ one, many }) => ({
    "order_items": many(orderItems, { relationName: "order_items_order_id" }),
    "customer": one(customers, {
        fields: [orders.customer_id],
        references: [customers.id],
        relationName: "orders_customer_id"
    })
}));

export const postsRelations = drizzleRelations(posts, ({ one, many }) => ({
    "author": one(authors, {
        fields: [posts.author_id],
        references: [authors.id],
        relationName: "posts_author_id"
    }),
    "tags": many(postsTags, { relationName: "tags" })
}));

export const postsTagsRelations = drizzleRelations(postsTags, ({ one, many }) => ({
    "post_id": one(posts, {
        fields: [postsTags.post_id],
        references: [posts.id],
        relationName: "tags"
    }),
    "tag_id": one(tags, {
        fields: [postsTags.tag_id],
        references: [tags.id],
        relationName: "posts"
    })
}));

export const productLocalesRelations = drizzleRelations(productLocales, ({ one, many }) => ({
    "product": one(products, {
        fields: [productLocales.product_id],
        references: [products.id],
        relationName: "product_locales_product_id"
    })
}));

export const productsRelations = drizzleRelations(products, ({ one, many }) => ({
    "product_locales": many(productLocales, { relationName: "product_locales_product_id" })
}));

export const tagsRelations = drizzleRelations(tags, ({ one, many }) => ({
    "posts": many(postsTags, { relationName: "posts" })
}));

export const ticketsRelations = drizzleRelations(tickets, ({ one, many }) => ({
    "customer": one(customers, {
        fields: [tickets.customer_id],
        references: [customers.id],
        relationName: "tickets_customer_id"
    })
}));

export const tables = { authors, customers, exercises, orderItems, orders, posts, postsTags, productLocales, products, tags, tickets, users };
export const enums = { exercisesDifficulty, exercisesCategory, exercisesStatus, ordersStatus, ordersPayment_status, ordersCurrency, postsStatus, productsCategory, productsStatus, ticketsStatus, ticketsPriority, ticketsCategory };
export const relations = { authorsRelations, customersRelations, orderItemsRelations, ordersRelations, postsRelations, postsTagsRelations, productLocalesRelations, productsRelations, tagsRelations, ticketsRelations };

