// This file is auto-generated by the Rebase Drizzle generator. Do not edit manually.

import { primaryKey, pgTable, integer, varchar, text, char, boolean, timestamp, date, time, jsonb, json, pgEnum, numeric, real, doublePrecision, bigint, serial, bigserial, pgPolicy, uuid } from 'drizzle-orm/pg-core';
import { relations as drizzleRelations, sql } from 'drizzle-orm';

export const postsStatus = pgEnum("posts_status", ['draft', 'review', 'published', 'archived']);
export const testEntitiesString_enum = pgEnum("test_entities_string_enum", ['opt_a', 'opt_b']);
export const testEntitiesNumber_enum = pgEnum("test_entities_number_enum", ['10', '20']);

export const authors = pgTable("authors", {
    id: integer("id").generatedByDefaultAsIdentity().primaryKey(),
    name: varchar("name").notNull(),
    email: varchar("email").notNull(),
    picture: varchar("picture"),
    userId: varchar("user_id")
}).enableRLS();

export const posts = pgTable("posts", {
    id: integer("id").primaryKey().notNull(),
    title: varchar("title").notNull(),
    content: varchar("content"),
    status: postsStatus("status"),
    author_id: integer("author_id").references(() => authors.id, { onDelete: "set null" })
}).enableRLS();

export const postsTags = pgTable("posts_tags", {
    post_id: integer("post_id").notNull().references(() => posts.id, { onDelete: "cascade" }),
    tag_id: integer("tag_id").notNull().references(() => tags.id, { onDelete: "cascade" }),
}, (table) => ({
    pk: primaryKey({ columns: [table.post_id, table.tag_id] })
}));

export const privateNotes = pgTable("private_notes", {
    id: uuid("id").primaryKey().defaultRandom(),
    title: varchar("title").notNull(),
    content: varchar("content"),
    user_id: varchar("user_id"),
    is_locked: boolean("is_locked")
}).enableRLS();

export const profiles = pgTable("profiles", {
    id: integer("id").primaryKey().notNull(),
    bio: varchar("bio"),
    website: varchar("website"),
    author_id: integer("author_id").references(() => authors.id, { onDelete: "set null" })
}).enableRLS();

export const tags = pgTable("tags", {
    id: integer("id").primaryKey().notNull(),
    name: varchar("name").notNull()
}).enableRLS();

export const testEntities = pgTable("test_entities", {
    id: integer("id").primaryKey(),
    string_plain: varchar("string_plain"),
    string_multiline: varchar("string_multiline"),
    string_markdown: varchar("string_markdown"),
    string_url: varchar("string_url"),
    string_email: varchar("string_email"),
    string_enum: testEntitiesString_enum("string_enum").notNull(),
    number_plain: numeric("number_plain"),
    number_enum: numeric("number_enum"),
    boolean_plain: boolean("boolean_plain"),
    date_plain: timestamp("date_plain", { withTimezone: true, mode: 'string' }),
    date_time: timestamp("date_time", { withTimezone: true, mode: 'string' }),
    map_plain: jsonb("map_plain"),
    array_string: jsonb("array_string"),
    array_enum: jsonb("array_enum"),
    reference_tags: integer("reference_tags").references(() => tags.id, { onDelete: "set null" })
}).enableRLS();

export const tagsTestEntities = pgTable("tags_test_entities", {
    test_entitie_id: integer("test_entitie_id").notNull().references(() => testEntities.id, { onDelete: "cascade" }),
    test_entity_tag_id: integer("test_entity_tag_id").notNull().references(() => tags.id, { onDelete: "cascade" }),
}, (table) => ({
    pk: primaryKey({ columns: [table.test_entitie_id, table.test_entity_tag_id] })
}));

export const authorsRelations = drizzleRelations(authors, ({ one, many }) => ({
    "profile": one(profiles, {
        fields: [authors.id],
        references: [profiles.author_id],
        relationName: "profiles_author_id"
    }),
    "posts": many(posts, { relationName: "posts_author_id" })
}));

export const postsRelations = drizzleRelations(posts, ({ one, many }) => ({
    "author": one(authors, {
        fields: [posts.author_id],
        references: [authors.id],
        relationName: "posts_author_id"
    }),
    "tags": many(postsTags, { relationName: "tags" })
}));

export const postsTagsRelations = drizzleRelations(postsTags, ({ one, many }) => ({
    "post_id": one(posts, {
        fields: [postsTags.post_id],
        references: [posts.id],
        relationName: "tags"
    }),
    "tag_id": one(tags, {
        fields: [postsTags.tag_id],
        references: [tags.id],
        relationName: "posts"
    })
}));

export const profilesRelations = drizzleRelations(profiles, ({ one, many }) => ({
    "author": one(authors, {
        fields: [profiles.author_id],
        references: [authors.id],
        relationName: "profiles_author_id"
    })
}));

export const tagsRelations = drizzleRelations(tags, ({ one, many }) => ({
    "posts": many(postsTags, { relationName: "posts" })
}));

export const testEntitiesRelations = drizzleRelations(testEntities, ({ one, many }) => ({
    "test_entity_tags": many(tagsTestEntities, { relationName: "test_entity_tags" }),
    "test-entity-tags": many(tagsTestEntities, { relationName: "test_entity_tags" }),
    "relation_tags": many(tagsTestEntities, { relationName: "test_entity_tags" }),
    "relation-tags": many(tagsTestEntities, { relationName: "test_entity_tags" })
}));

export const tagsTestEntitiesRelations = drizzleRelations(tagsTestEntities, ({ one, many }) => ({
    "test_entitie_id": one(testEntities, {
        fields: [tagsTestEntities.test_entitie_id],
        references: [testEntities.id],
        relationName: "test_entity_tags"
    }),
    "test_entity_tag_id": one(tags, {
        fields: [tagsTestEntities.test_entity_tag_id],
        references: [tags.id],
        relationName: "test_entity_tags"
    })
}));

export const tables = { authors, posts, postsTags, privateNotes, profiles, tags, testEntities, tagsTestEntities };
export const enums = { postsStatus, testEntitiesString_enum, testEntitiesNumber_enum };
export const relations = { authorsRelations, postsRelations, postsTagsRelations, profilesRelations, tagsRelations, testEntitiesRelations, tagsTestEntitiesRelations };

