// This file is auto-generated by the Rebase Drizzle generator. Do not edit manually.

import { primaryKey, pgTable, integer, varchar, text, char, boolean, timestamp, date, time, jsonb, json, pgEnum, numeric, real, doublePrecision, bigint, serial, bigserial, pgPolicy, uuid, customType, pgSchema } from 'drizzle-orm/pg-core';
import { relations as drizzleRelations, sql } from 'drizzle-orm';

export const rebaseSchema = pgSchema("rebase");

export const exercisesDifficulty = pgEnum("exercises_difficulty", ['beginner', 'intermediate', 'advanced']);
export const exercisesCategory = pgEnum("exercises_category", ['strength', 'cardio', 'flexibility', 'balance', 'plyometrics', 'calisthenics']);
export const exercisesStatus = pgEnum("exercises_status", ['draft', 'published', 'archived']);
export const ordersStatus = pgEnum("orders_status", ['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded']);
export const ordersPayment_status = pgEnum("orders_payment_status", ['unpaid', 'paid', 'partially_refunded', 'refunded']);
export const ordersCurrency = pgEnum("orders_currency", ['USD', 'EUR', 'GBP', 'CAD', 'AUD']);
export const postsStatus = pgEnum("posts_status", ['draft', 'needs_review', 'published', 'archived']);
export const productLocalesLocale = pgEnum("product_locales_locale", ['en', 'es', 'fr', 'de', 'it']);
export const productsCategory = pgEnum("products_category", ['electronics', 'clothing', 'home_garden', 'sports', 'books', 'food_beverage', 'health_beauty', 'toys']);
export const productsStatus = pgEnum("products_status", ['draft', 'active', 'archived']);
export const ticketsStatus = pgEnum("tickets_status", ['open', 'in_progress', 'waiting', 'resolved', 'closed']);
export const ticketsPriority = pgEnum("tickets_priority", ['low', 'medium', 'high', 'urgent']);
export const ticketsCategory = pgEnum("tickets_category", ['bug', 'feature_request', 'question', 'billing', 'account', 'other']);

export const authors = pgTable("authors", {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    email: text("email").notNull(),
    picture: text("picture"),
    bio: text("bio"),
    twitter: text("twitter"),
    github: text("github"),
    website: text("website"),
    userId: text("user_id")
}, (table) => ([
    pgPolicy("authors_select_841c287", { as: "permissive", for: "select", to: ["public"], using: sql`true` }),
    pgPolicy("authors_insert_3561e70_0", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("authors_update_3561e70_1", { as: "permissive", for: "update", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']`, withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("authors_delete_3561e70_2", { as: "permissive", for: "delete", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("authors_default_admin_read", { as: "permissive", for: "select", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("authors_default_admin_write_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("authors_default_admin_write_update", { as: "permissive", for: "update", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])`, withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("authors_default_admin_write_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
])).enableRLS();

export const customers = pgTable("customers", {
    id: uuid("id").primaryKey().defaultRandom(),
    first_name: text("first_name").notNull(),
    last_name: text("last_name").notNull(),
    email: text("email").unique().notNull(),
    phone: text("phone"),
    avatar: text("avatar"),
    company: text("company"),
    is_vip: boolean("is_vip"),
    lifetime_value: numeric("lifetime_value"),
    total_orders: numeric("total_orders"),
    shipping_address: text("shipping_address"),
    billing_address: text("billing_address"),
    notes: text("notes"),
    created_at: timestamp("created_at", { withTimezone: true, mode: 'string' }).default(sql`now()`),
    updated_at: timestamp("updated_at", { withTimezone: true, mode: 'string' }).default(sql`now()`)
}, (table) => ([
    pgPolicy("customers_select_841c287", { as: "permissive", for: "select", to: ["public"], using: sql`true` }),
    pgPolicy("customers_insert_3561e70_0", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("customers_update_3561e70_1", { as: "permissive", for: "update", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']`, withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("customers_delete_3561e70_2", { as: "permissive", for: "delete", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("customers_default_admin_read", { as: "permissive", for: "select", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("customers_default_admin_write_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("customers_default_admin_write_update", { as: "permissive", for: "update", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])`, withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("customers_default_admin_write_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
])).enableRLS();

export const exercises = pgTable("exercises", {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    description: text("description"),
    images: text("images").array(),
    video_url: text("video_url"),
    difficulty: exercisesDifficulty("difficulty").notNull(),
    category: exercisesCategory("category").notNull(),
    equipment: text("equipment").array(),
    body_parts: text("body_parts").array(),
    instructions: text("instructions"),
    default_reps: numeric("default_reps"),
    default_sets: numeric("default_sets"),
    rest_seconds: numeric("rest_seconds"),
    calories_per_minute: numeric("calories_per_minute"),
    is_compound: boolean("is_compound"),
    is_featured: boolean("is_featured"),
    status: exercisesStatus("status").notNull(),
    created_at: timestamp("created_at", { withTimezone: true, mode: 'string' }).default(sql`now()`),
    updated_at: timestamp("updated_at", { withTimezone: true, mode: 'string' }).default(sql`now()`)
}, (table) => ([
    pgPolicy("exercises_select_841c287", { as: "permissive", for: "select", to: ["public"], using: sql`true` }),
    pgPolicy("exercises_insert_3561e70_0", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("exercises_update_3561e70_1", { as: "permissive", for: "update", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']`, withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("exercises_delete_3561e70_2", { as: "permissive", for: "delete", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("exercises_default_admin_read", { as: "permissive", for: "select", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("exercises_default_admin_write_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("exercises_default_admin_write_update", { as: "permissive", for: "update", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])`, withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("exercises_default_admin_write_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
])).enableRLS();

export const orderItems = pgTable("order_items", {
    id: uuid("id").primaryKey().defaultRandom(),
    order_id: uuid("order_id").references(() => orders.id, { onDelete: "cascade" }),
    product_id: uuid("product_id").references(() => products.id, { onDelete: "restrict" }),
    product_name: text("product_name"),
    sku: text("sku"),
    quantity: numeric("quantity").notNull(),
    unit_price: numeric("unit_price"),
    line_total: numeric("line_total")
}, (table) => ([
    pgPolicy("order_items_select_841c287", { as: "permissive", for: "select", to: ["public"], using: sql`true` }),
    pgPolicy("order_items_insert_3561e70_0", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("order_items_update_3561e70_1", { as: "permissive", for: "update", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']`, withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("order_items_delete_3561e70_2", { as: "permissive", for: "delete", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("order_items_default_admin_read", { as: "permissive", for: "select", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("order_items_default_admin_write_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("order_items_default_admin_write_update", { as: "permissive", for: "update", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])`, withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("order_items_default_admin_write_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
])).enableRLS();

export const orders = pgTable("orders", {
    id: uuid("id").primaryKey().defaultRandom(),
    order_number: text("order_number").unique().notNull(),
    customer_id: uuid("customer_id").references(() => customers.id, { onDelete: "cascade" }).notNull(),
    status: ordersStatus("status").notNull(),
    payment_status: ordersPayment_status("payment_status").notNull(),
    subtotal: numeric("subtotal"),
    tax_amount: numeric("tax_amount"),
    shipping_cost: numeric("shipping_cost"),
    discount_amount: numeric("discount_amount"),
    total: numeric("total"),
    currency: ordersCurrency("currency"),
    shipping_address: text("shipping_address"),
    tracking_number: text("tracking_number"),
    notes: text("notes"),
    order_date: timestamp("order_date", { withTimezone: true, mode: 'string' }).notNull(),
    shipped_date: timestamp("shipped_date", { withTimezone: true, mode: 'string' }),
    delivered_date: timestamp("delivered_date", { withTimezone: true, mode: 'string' }),
    created_at: timestamp("created_at", { withTimezone: true, mode: 'string' }).default(sql`now()`),
    updated_at: timestamp("updated_at", { withTimezone: true, mode: 'string' }).default(sql`now()`)
}, (table) => ([
    pgPolicy("orders_select_841c287", { as: "permissive", for: "select", to: ["public"], using: sql`true` }),
    pgPolicy("orders_insert_3561e70_0", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("orders_update_3561e70_1", { as: "permissive", for: "update", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']`, withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("orders_delete_3561e70_2", { as: "permissive", for: "delete", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("orders_default_admin_read", { as: "permissive", for: "select", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("orders_default_admin_write_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("orders_default_admin_write_update", { as: "permissive", for: "update", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])`, withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("orders_default_admin_write_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
])).enableRLS();

export const posts = pgTable("posts", {
    id: uuid("id").primaryKey().defaultRandom(),
    title: text("title").notNull(),
    slug: text("slug").unique().notNull(),
    hero_image: text("hero_image"),
    excerpt: text("excerpt"),
    content: jsonb("content"),
    status: postsStatus("status").notNull(),
    publish_date: timestamp("publish_date", { withTimezone: true, mode: 'string' }),
    created_at: timestamp("created_at", { withTimezone: true, mode: 'string' }).default(sql`now()`),
    updated_at: timestamp("updated_at", { withTimezone: true, mode: 'string' }).default(sql`now()`),
    author_id: uuid("author_id").references(() => authors.id, { onDelete: "set null" }),
    search_vector: customType({ dataType() { return 'tsvector'; } })("search_vector").generatedAlwaysAs(sql`setweight(to_tsvector('english', coalesce("title", '')), 'A') || setweight(to_tsvector('english', coalesce("excerpt", '')), 'C') || setweight(to_tsvector('english', public.rebase_search_text(coalesce("content", '{}'::jsonb))), 'D')`)
}, (table) => ([
    pgPolicy("posts_select_841c287", { as: "permissive", for: "select", to: ["public"], using: sql`true` }),
    pgPolicy("posts_insert_3561e70_0", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("posts_update_3561e70_1", { as: "permissive", for: "update", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']`, withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("posts_delete_3561e70_2", { as: "permissive", for: "delete", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("posts_default_admin_read", { as: "permissive", for: "select", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("posts_default_admin_write_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("posts_default_admin_write_update", { as: "permissive", for: "update", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])`, withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("posts_default_admin_write_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
])).enableRLS();

export const postsTags = pgTable("posts_tags", {
    post_id: uuid("post_id").notNull().references(() => posts.id, { onDelete: "cascade" }),
    tag_id: uuid("tag_id").notNull().references(() => tags.id, { onDelete: "cascade" }),
}, (table) => ([
    primaryKey({ columns: [table.post_id, table.tag_id] }),
    pgPolicy("posts_tags_default_admin_read", { as: "permissive", for: "select", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("posts_tags_default_admin_write_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("posts_tags_default_admin_write_update", { as: "permissive", for: "update", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])`, withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("posts_tags_default_admin_write_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("posts_tags_default_edge_read", { as: "permissive", for: "select", to: ["public"], using: sql`(EXISTS (SELECT 1 FROM "public"."posts" "_ex0" WHERE "_ex0".id = "public"."posts_tags".post_id)) AND (EXISTS (SELECT 1 FROM "public"."tags" "_ex1" WHERE "_ex1".id = "public"."posts_tags".tag_id))` }),
    pgPolicy("posts_tags_default_edge_write_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(EXISTS (SELECT 1 FROM "public"."posts" "_ex0" WHERE ("_ex0".id = "public"."posts_tags".post_id) AND ((string_to_array(rebase.roles(), ',') && ARRAY['admin'])))) OR (EXISTS (SELECT 1 FROM "public"."tags" "_ex1" WHERE ("_ex1".id = "public"."posts_tags".tag_id) AND ((string_to_array(rebase.roles(), ',') && ARRAY['admin']))))` }),
    pgPolicy("posts_tags_default_edge_write_update", { as: "permissive", for: "update", to: ["public"], using: sql`(EXISTS (SELECT 1 FROM "public"."posts" "_ex0" WHERE ("_ex0".id = "public"."posts_tags".post_id) AND ((string_to_array(rebase.roles(), ',') && ARRAY['admin'])))) OR (EXISTS (SELECT 1 FROM "public"."tags" "_ex1" WHERE ("_ex1".id = "public"."posts_tags".tag_id) AND ((string_to_array(rebase.roles(), ',') && ARRAY['admin']))))`, withCheck: sql`(EXISTS (SELECT 1 FROM "public"."posts" "_ex0" WHERE ("_ex0".id = "public"."posts_tags".post_id) AND ((string_to_array(rebase.roles(), ',') && ARRAY['admin'])))) OR (EXISTS (SELECT 1 FROM "public"."tags" "_ex1" WHERE ("_ex1".id = "public"."posts_tags".tag_id) AND ((string_to_array(rebase.roles(), ',') && ARRAY['admin']))))` }),
    pgPolicy("posts_tags_default_edge_write_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`(EXISTS (SELECT 1 FROM "public"."posts" "_ex0" WHERE ("_ex0".id = "public"."posts_tags".post_id) AND ((string_to_array(rebase.roles(), ',') && ARRAY['admin'])))) OR (EXISTS (SELECT 1 FROM "public"."tags" "_ex1" WHERE ("_ex1".id = "public"."posts_tags".tag_id) AND ((string_to_array(rebase.roles(), ',') && ARRAY['admin']))))` }),
])).enableRLS();

export const productLocales = pgTable("product_locales", {
    id: uuid("id").primaryKey().defaultRandom().notNull(),
    product_id: uuid("product_id").references(() => products.id, { onDelete: "set null" }),
    locale: productLocalesLocale("locale").notNull(),
    name: text("name"),
    description: text("description")
}, (table) => ([
    pgPolicy("product_locales_select_841c287", { as: "permissive", for: "select", to: ["public"], using: sql`true` }),
    pgPolicy("product_locales_insert_3561e70_0", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("product_locales_update_3561e70_1", { as: "permissive", for: "update", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']`, withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("product_locales_delete_3561e70_2", { as: "permissive", for: "delete", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("product_locales_default_admin_read", { as: "permissive", for: "select", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("product_locales_default_admin_write_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("product_locales_default_admin_write_update", { as: "permissive", for: "update", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])`, withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("product_locales_default_admin_write_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
])).enableRLS();

export const products = pgTable("products", {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    sku: text("sku").unique().notNull(),
    description: text("description"),
    images: text("images").array(),
    available_locales: text("available_locales").array(),
    brand: text("brand"),
    category: productsCategory("category").notNull(),
    price: numeric("price").notNull(),
    compare_at_price: numeric("compare_at_price"),
    cost: numeric("cost"),
    stock_quantity: numeric("stock_quantity").notNull(),
    low_stock_threshold: numeric("low_stock_threshold"),
    weight_grams: numeric("weight_grams"),
    rating: numeric("rating"),
    review_count: numeric("review_count"),
    status: productsStatus("status").notNull(),
    is_featured: boolean("is_featured"),
    created_at: timestamp("created_at", { withTimezone: true, mode: 'string' }).default(sql`now()`),
    updated_at: timestamp("updated_at", { withTimezone: true, mode: 'string' }).default(sql`now()`)
}, (table) => ([
    pgPolicy("products_select_841c287", { as: "permissive", for: "select", to: ["public"], using: sql`true` }),
    pgPolicy("products_insert_3561e70_0", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("products_update_3561e70_1", { as: "permissive", for: "update", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']`, withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("products_delete_3561e70_2", { as: "permissive", for: "delete", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("products_default_admin_read", { as: "permissive", for: "select", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("products_default_admin_write_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("products_default_admin_write_update", { as: "permissive", for: "update", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])`, withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("products_default_admin_write_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
])).enableRLS();

export const tags = pgTable("tags", {
    id: uuid("id").primaryKey().defaultRandom().notNull(),
    name: text("name").notNull()
}, (table) => ([
    pgPolicy("tags_select_841c287", { as: "permissive", for: "select", to: ["public"], using: sql`true` }),
    pgPolicy("tags_insert_3561e70_0", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("tags_update_3561e70_1", { as: "permissive", for: "update", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']`, withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("tags_delete_3561e70_2", { as: "permissive", for: "delete", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("tags_default_admin_read", { as: "permissive", for: "select", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("tags_default_admin_write_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("tags_default_admin_write_update", { as: "permissive", for: "update", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])`, withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("tags_default_admin_write_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
])).enableRLS();

export const tickets = pgTable("tickets", {
    id: uuid("id").primaryKey().defaultRandom(),
    ticket_number: text("ticket_number").unique().notNull(),
    subject: text("subject").notNull(),
    description: text("description"),
    resolution_notes: text("resolution_notes"),
    status: ticketsStatus("status").notNull(),
    priority: ticketsPriority("priority").notNull(),
    category: ticketsCategory("category"),
    customer_id: uuid("customer_id").references(() => customers.id, { onDelete: "set null" }),
    assigned_to: text("assigned_to"),
    created_at: timestamp("created_at", { withTimezone: true, mode: 'string' }).default(sql`now()`),
    updated_at: timestamp("updated_at", { withTimezone: true, mode: 'string' }).default(sql`now()`),
    __order: text("order")
}, (table) => ([
    pgPolicy("tickets_select_841c287", { as: "permissive", for: "select", to: ["public"], using: sql`true` }),
    pgPolicy("tickets_insert_3561e70_0", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("tickets_update_3561e70_1", { as: "permissive", for: "update", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']`, withCheck: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("tickets_delete_3561e70_2", { as: "permissive", for: "delete", to: ["public"], using: sql`string_to_array(rebase.roles(), ',') && ARRAY['admin']` }),
    pgPolicy("tickets_default_admin_read", { as: "permissive", for: "select", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("tickets_default_admin_write_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("tickets_default_admin_write_update", { as: "permissive", for: "update", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])`, withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("tickets_default_admin_write_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
])).enableRLS();

export const users = rebaseSchema.table("users", {
    id: uuid("id").primaryKey().defaultRandom(),
    email: text("email").unique().notNull(),
    displayName: text("display_name"),
    photoURL: text("photo_url"),
    roles: text("roles").array(),
    passwordHash: text("password_hash"),
    emailVerified: boolean("email_verified"),
    emailVerificationToken: text("email_verification_token"),
    emailVerificationSentAt: timestamp("email_verification_sent_at", { withTimezone: true, mode: 'string' }),
    metadata: jsonb("metadata"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).default(sql`now()`)
}, (table) => ([
    pgPolicy("users_read_policy", { as: "permissive", for: "select", to: ["public"], using: sql`(rebase.uid() IS NULL) OR ((id)::text = rebase.uid()) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("users_write_policy_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("users_write_policy_update", { as: "permissive", for: "update", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])`, withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("users_write_policy_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("users_default_admin_read", { as: "permissive", for: "select", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("users_default_admin_write_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("users_default_admin_write_update", { as: "permissive", for: "update", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])`, withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("users_default_admin_write_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("users_default_self_read", { as: "permissive", for: "select", to: ["public"], using: sql`(id)::text = rebase.uid()` }),
    pgPolicy("users_require_admin_write_insert", { as: "restrictive", for: "insert", to: ["public"], withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("users_require_admin_write_update", { as: "restrictive", for: "update", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])`, withCheck: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
    pgPolicy("users_require_admin_write_delete", { as: "restrictive", for: "delete", to: ["public"], using: sql`(rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ',') && ARRAY['admin'])` }),
])).enableRLS();

export const authorsRelations = drizzleRelations(authors, ({ one, many }) => ({
    "posts": many(posts, { relationName: "posts_author_id" })
}));

export const customersRelations = drizzleRelations(customers, ({ one, many }) => ({
    "orders": many(orders, { relationName: "orders_customer_id" })
}));

export const orderItemsRelations = drizzleRelations(orderItems, ({ one, many }) => ({
    "order": one(orders, {
        fields: [orderItems.order_id],
        references: [orders.id],
        relationName: "order_items_order_id"
    }),
    "product": one(products, {
        fields: [orderItems.product_id],
        references: [products.id],
        relationName: "order_items_product_id"
    })
}));

export const ordersRelations = drizzleRelations(orders, ({ one, many }) => ({
    "order_items": many(orderItems, { relationName: "order_items_order_id" }),
    "customer": one(customers, {
        fields: [orders.customer_id],
        references: [customers.id],
        relationName: "orders_customer_id"
    })
}));

export const postsRelations = drizzleRelations(posts, ({ one, many }) => ({
    "author": one(authors, {
        fields: [posts.author_id],
        references: [authors.id],
        relationName: "posts_author_id"
    }),
    "tags": many(postsTags, { relationName: "tags" })
}));

export const postsTagsRelations = drizzleRelations(postsTags, ({ one, many }) => ({
    "post_id": one(posts, {
        fields: [postsTags.post_id],
        references: [posts.id],
        relationName: "tags"
    }),
    "tag_id": one(tags, {
        fields: [postsTags.tag_id],
        references: [tags.id],
        relationName: "posts_tags_tag_id"
    })
}));

export const productLocalesRelations = drizzleRelations(productLocales, ({ one, many }) => ({
    "product": one(products, {
        fields: [productLocales.product_id],
        references: [products.id],
        relationName: "product_locales_product_id"
    })
}));

export const productsRelations = drizzleRelations(products, ({ one, many }) => ({
    "product_locales": many(productLocales, { relationName: "product_locales_product_id" })
}));

export const tagsRelations = drizzleRelations(tags, ({ one, many }) => ({
    "posts": many(postsTags, { relationName: "posts" })
}));

export const ticketsRelations = drizzleRelations(tickets, ({ one, many }) => ({
    "customer": one(customers, {
        fields: [tickets.customer_id],
        references: [customers.id],
        relationName: "tickets_customer_id"
    })
}));

export const tables = { authors, customers, exercises, orderItems, orders, posts, postsTags, productLocales, products, tags, tickets, users };
export const enums = { exercisesDifficulty, exercisesCategory, exercisesStatus, ordersStatus, ordersPayment_status, ordersCurrency, postsStatus, productLocalesLocale, productsCategory, productsStatus, ticketsStatus, ticketsPriority, ticketsCategory };
export const relations = { authorsRelations, customersRelations, orderItemsRelations, ordersRelations, postsRelations, postsTagsRelations, productLocalesRelations, productsRelations, tagsRelations, ticketsRelations };

