{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rebase.fullname" . }}-config
  labels:
    {{- include "rebase.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
  JWT_SECRET: {{ .Values.config.jwtSecret | quote }}
  REBASE_SERVICE_KEY: {{ .Values.config.serviceKey | quote }}
  {{- if .Values.bundle.token }}
  REBASE_BUNDLE_TOKEN: {{ .Values.bundle.token | quote }}
  {{- end }}
{{- end }}
