CREATE TYPE "public"."posts_status" AS ENUM('draft', 'review', 'published', 'archived');--> statement-breakpoint
CREATE TYPE "public"."test_entities_number_enum" AS ENUM('10', '20');--> statement-breakpoint
CREATE TYPE "public"."test_entities_string_enum" AS ENUM('opt_a', 'opt_b');--> statement-breakpoint
CREATE TABLE "authors" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "authors_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar NOT NULL,
	"email" varchar NOT NULL,
	"picture" varchar,
	"user_id" varchar
);
--> statement-breakpoint
ALTER TABLE "authors" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "posts" (
	"id" integer PRIMARY KEY NOT NULL,
	"title" varchar NOT NULL,
	"content" varchar,
	"status" "posts_status",
	"author_id" integer
);
--> statement-breakpoint
ALTER TABLE "posts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "posts_tags" (
	"post_id" integer NOT NULL,
	"tag_id" integer NOT NULL,
	CONSTRAINT "posts_tags_post_id_tag_id_pk" PRIMARY KEY("post_id","tag_id")
);
--> statement-breakpoint
CREATE TABLE "private_notes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" varchar NOT NULL,
	"content" varchar,
	"user_id" varchar,
	"is_locked" boolean
);
--> statement-breakpoint
ALTER TABLE "private_notes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "profiles" (
	"id" integer PRIMARY KEY NOT NULL,
	"bio" varchar,
	"website" varchar,
	"author_id" integer
);
--> statement-breakpoint
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "tags" (
	"id" integer PRIMARY KEY NOT NULL,
	"name" varchar NOT NULL
);
--> statement-breakpoint
ALTER TABLE "tags" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "tags_test_entities" (
	"test_entitie_id" integer NOT NULL,
	"test_entity_tag_id" integer NOT NULL,
	CONSTRAINT "tags_test_entities_test_entitie_id_test_entity_tag_id_pk" PRIMARY KEY("test_entitie_id","test_entity_tag_id")
);
--> statement-breakpoint
CREATE TABLE "test_entities" (
	"id" integer PRIMARY KEY NOT NULL,
	"string_plain" varchar,
	"string_multiline" varchar,
	"string_markdown" varchar,
	"string_url" varchar,
	"string_email" varchar,
	"string_enum" "test_entities_string_enum" NOT NULL,
	"number_plain" numeric,
	"number_enum" numeric,
	"boolean_plain" boolean,
	"date_plain" timestamp with time zone,
	"date_time" timestamp with time zone,
	"map_plain" jsonb,
	"array_string" jsonb,
	"array_enum" jsonb,
	"reference_tags" integer
);
--> statement-breakpoint
ALTER TABLE "test_entities" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "posts_author_id_authors_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."authors"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "posts_tags" ADD CONSTRAINT "posts_tags_post_id_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "posts_tags" ADD CONSTRAINT "posts_tags_tag_id_tags_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_author_id_authors_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."authors"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tags_test_entities" ADD CONSTRAINT "tags_test_entities_test_entitie_id_test_entities_id_fk" FOREIGN KEY ("test_entitie_id") REFERENCES "public"."test_entities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tags_test_entities" ADD CONSTRAINT "tags_test_entities_test_entity_tag_id_tags_id_fk" FOREIGN KEY ("test_entity_tag_id") REFERENCES "public"."tags"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "test_entities" ADD CONSTRAINT "test_entities_reference_tags_tags_id_fk" FOREIGN KEY ("reference_tags") REFERENCES "public"."tags"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE POLICY "admin_bypass" ON "private_notes" AS PERMISSIVE FOR ALL TO public USING ((true) AND (string_to_array(auth.roles(), ',') @> ARRAY['admin'])) WITH CHECK ((true) AND (string_to_array(auth.roles(), ',') @> ARRAY['admin']));--> statement-breakpoint
CREATE POLICY "owner_access" ON "private_notes" AS PERMISSIVE FOR ALL TO public USING ("private_notes"."user_id" = auth.uid()) WITH CHECK ("private_notes"."user_id" = auth.uid());--> statement-breakpoint
CREATE POLICY "no_update_locked" ON "private_notes" AS RESTRICTIVE FOR UPDATE TO public USING ("private_notes"."is_locked" = false) WITH CHECK ("private_notes"."is_locked" = false);