-- This file contains RLS policies generated by Rebase. Applied separately from migrations.

ALTER TABLE "public"."authors" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "authors_public_access" ON "public"."authors";
CREATE POLICY "authors_public_access" ON "public"."authors" AS PERMISSIVE FOR ALL TO "public" USING (true) WITH CHECK (true);

ALTER TABLE "public"."customers" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "test_policy" ON "public"."customers";
CREATE POLICY "test_policy" ON "public"."customers" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);

ALTER TABLE "public"."exercises" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "test_policy" ON "public"."exercises";
CREATE POLICY "test_policy" ON "public"."exercises" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);

ALTER TABLE "public"."order_items" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "test_policy" ON "public"."order_items";
CREATE POLICY "test_policy" ON "public"."order_items" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);

ALTER TABLE "public"."orders" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "test_policy" ON "public"."orders";
CREATE POLICY "test_policy" ON "public"."orders" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);

ALTER TABLE "public"."posts" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "test_policy" ON "public"."posts";
CREATE POLICY "test_policy" ON "public"."posts" AS PERMISSIVE FOR ALL TO "public" USING (true) WITH CHECK (true);

ALTER TABLE "public"."product_locales" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "product_locales_public_access" ON "public"."product_locales";
CREATE POLICY "product_locales_public_access" ON "public"."product_locales" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);

ALTER TABLE "public"."products" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "test_policy" ON "public"."products";
CREATE POLICY "test_policy" ON "public"."products" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);

ALTER TABLE "public"."tags" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tags_public_access" ON "public"."tags";
CREATE POLICY "tags_public_access" ON "public"."tags" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);

ALTER TABLE "public"."tickets" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "test_policy" ON "public"."tickets";
CREATE POLICY "test_policy" ON "public"."tickets" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);

ALTER TABLE "rebase"."users" ENABLE ROW LEVEL SECURITY;

