-- This file contains RLS policies generated by Rebase. Applied separately from migrations.

ALTER TABLE "public"."authors" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "authors_public_access" ON "public"."authors";
CREATE POLICY "authors_public_access" ON "public"."authors" AS PERMISSIVE FOR ALL TO "public" USING (true) WITH CHECK (true);

ALTER TABLE "public"."customers" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "test_policy" ON "public"."customers";
CREATE POLICY "test_policy" ON "public"."customers" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);

ALTER TABLE "public"."exercises" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "test_policy" ON "public"."exercises";
CREATE POLICY "test_policy" ON "public"."exercises" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);

ALTER TABLE "public"."order_items" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "test_policy" ON "public"."order_items";
CREATE POLICY "test_policy" ON "public"."order_items" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);

ALTER TABLE "public"."orders" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "test_policy" ON "public"."orders";
CREATE POLICY "test_policy" ON "public"."orders" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);

ALTER TABLE "public"."posts" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "test_policy" ON "public"."posts";
CREATE POLICY "test_policy" ON "public"."posts" AS PERMISSIVE FOR ALL TO "public" USING (true) WITH CHECK (true);

ALTER TABLE "public"."product_locales" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "product_locales_public_access" ON "public"."product_locales";
CREATE POLICY "product_locales_public_access" ON "public"."product_locales" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);

ALTER TABLE "public"."products" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "test_policy" ON "public"."products";
CREATE POLICY "test_policy" ON "public"."products" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);

ALTER TABLE "public"."tags" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tags_public_access" ON "public"."tags";
CREATE POLICY "tags_public_access" ON "public"."tags" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);

ALTER TABLE "public"."tickets" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "test_policy" ON "public"."tickets";
CREATE POLICY "test_policy" ON "public"."tickets" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);

ALTER TABLE "rebase"."users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "rebase"."users" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users_read_policy" ON "rebase"."users";
CREATE POLICY "users_read_policy" ON "rebase"."users" AS PERMISSIVE FOR SELECT TO "public" USING (auth.uid() IS NULL OR id = auth.uid()::uuid OR string_to_array(auth.roles(), ',') && ARRAY['admin']);
DROP POLICY IF EXISTS "users_write_policy_insert" ON "rebase"."users";
CREATE POLICY "users_write_policy_insert" ON "rebase"."users" AS PERMISSIVE FOR INSERT TO "public" WITH CHECK (auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']);
DROP POLICY IF EXISTS "users_write_policy_update" ON "rebase"."users";
CREATE POLICY "users_write_policy_update" ON "rebase"."users" AS PERMISSIVE FOR UPDATE TO "public" USING (auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']) WITH CHECK (auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']);
DROP POLICY IF EXISTS "users_write_policy_delete" ON "rebase"."users";
CREATE POLICY "users_write_policy_delete" ON "rebase"."users" AS PERMISSIVE FOR DELETE TO "public" USING (auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']);
DROP POLICY IF EXISTS "users_default_admin_write_insert" ON "rebase"."users";
CREATE POLICY "users_default_admin_write_insert" ON "rebase"."users" AS PERMISSIVE FOR INSERT TO "public" WITH CHECK (auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']);
DROP POLICY IF EXISTS "users_default_admin_write_update" ON "rebase"."users";
CREATE POLICY "users_default_admin_write_update" ON "rebase"."users" AS PERMISSIVE FOR UPDATE TO "public" USING (auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']) WITH CHECK (auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']);
DROP POLICY IF EXISTS "users_default_admin_write_delete" ON "rebase"."users";
CREATE POLICY "users_default_admin_write_delete" ON "rebase"."users" AS PERMISSIVE FOR DELETE TO "public" USING (auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']);
DROP POLICY IF EXISTS "users_require_admin_write_insert" ON "rebase"."users";
CREATE POLICY "users_require_admin_write_insert" ON "rebase"."users" AS RESTRICTIVE FOR INSERT TO "public" WITH CHECK (auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']);
DROP POLICY IF EXISTS "users_require_admin_write_update" ON "rebase"."users";
CREATE POLICY "users_require_admin_write_update" ON "rebase"."users" AS RESTRICTIVE FOR UPDATE TO "public" USING (auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']) WITH CHECK (auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']);
DROP POLICY IF EXISTS "users_require_admin_write_delete" ON "rebase"."users";
CREATE POLICY "users_require_admin_write_delete" ON "rebase"."users" AS RESTRICTIVE FOR DELETE TO "public" USING (auth.uid() IS NULL OR string_to_array(auth.roles(), ',') && ARRAY['admin']);

