-- This file is auto-generated by the Rebase DDL generator. Do not edit manually.

CREATE SCHEMA IF NOT EXISTS "auth";
CREATE SCHEMA IF NOT EXISTS "rebase";

CREATE TYPE "public"."exercises_difficulty" AS ENUM ('beginner', 'intermediate', 'advanced');
CREATE TYPE "public"."exercises_category" AS ENUM ('strength', 'cardio', 'flexibility', 'balance', 'plyometrics', 'calisthenics');
CREATE TYPE "public"."exercises_status" AS ENUM ('draft', 'published', 'archived');
CREATE TYPE "public"."orders_status" AS ENUM ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded');
CREATE TYPE "public"."orders_payment_status" AS ENUM ('unpaid', 'paid', 'partially_refunded', 'refunded');
CREATE TYPE "public"."orders_currency" AS ENUM ('USD', 'EUR', 'GBP', 'CAD', 'AUD');
CREATE TYPE "public"."posts_status" AS ENUM ('draft', 'needs_review', 'published', 'archived');
CREATE TYPE "public"."product_locales_locale" AS ENUM ('en', 'es', 'fr', 'de', 'it');
CREATE TYPE "public"."products_category" AS ENUM ('electronics', 'clothing', 'home_garden', 'sports', 'books', 'food_beverage', 'health_beauty', 'toys');
CREATE TYPE "public"."products_status" AS ENUM ('draft', 'active', 'archived');
CREATE TYPE "public"."tickets_status" AS ENUM ('open', 'in_progress', 'waiting', 'resolved', 'closed');
CREATE TYPE "public"."tickets_priority" AS ENUM ('low', 'medium', 'high', 'urgent');
CREATE TYPE "public"."tickets_category" AS ENUM ('bug', 'feature_request', 'question', 'billing', 'account', 'other');

CREATE TABLE "public"."authors" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "picture" TEXT,
  "bio" TEXT,
  "twitter" TEXT,
  "github" TEXT,
  "website" TEXT,
  "user_id" TEXT
);

CREATE TABLE "public"."customers" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "first_name" TEXT NOT NULL,
  "last_name" TEXT NOT NULL,
  "email" TEXT UNIQUE NOT NULL,
  "phone" TEXT,
  "avatar" TEXT,
  "company" TEXT,
  "is_vip" BOOLEAN,
  "lifetime_value" NUMERIC,
  "total_orders" NUMERIC,
  "shipping_address" TEXT,
  "billing_address" TEXT,
  "notes" TEXT,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE "public"."exercises" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" TEXT NOT NULL,
  "description" TEXT,
  "images" TEXT[],
  "video_url" TEXT,
  "difficulty" "public"."exercises_difficulty" NOT NULL,
  "category" "public"."exercises_category" NOT NULL,
  "equipment" TEXT[],
  "body_parts" TEXT[],
  "instructions" TEXT,
  "default_reps" NUMERIC,
  "default_sets" NUMERIC,
  "rest_seconds" NUMERIC,
  "calories_per_minute" NUMERIC,
  "is_compound" BOOLEAN,
  "is_featured" BOOLEAN,
  "status" "public"."exercises_status" NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE "public"."order_items" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "order_id" UUID,
  "product_id" UUID,
  "product_name" TEXT,
  "sku" TEXT,
  "quantity" NUMERIC NOT NULL,
  "unit_price" NUMERIC,
  "line_total" NUMERIC
);

CREATE TABLE "public"."orders" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "order_number" TEXT UNIQUE NOT NULL,
  "customer_id" UUID NOT NULL,
  "status" "public"."orders_status" NOT NULL,
  "payment_status" "public"."orders_payment_status" NOT NULL,
  "subtotal" NUMERIC,
  "tax_amount" NUMERIC,
  "shipping_cost" NUMERIC,
  "discount_amount" NUMERIC,
  "total" NUMERIC,
  "currency" "public"."orders_currency",
  "shipping_address" TEXT,
  "tracking_number" TEXT,
  "notes" TEXT,
  "order_date" TIMESTAMP WITH TIME ZONE NOT NULL,
  "shipped_date" TIMESTAMP WITH TIME ZONE,
  "delivered_date" TIMESTAMP WITH TIME ZONE,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE "public"."posts" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "title" TEXT NOT NULL,
  "slug" TEXT UNIQUE NOT NULL,
  "hero_image" TEXT,
  "excerpt" TEXT,
  "content" JSONB,
  "status" "public"."posts_status" NOT NULL,
  "publish_date" TIMESTAMP WITH TIME ZONE,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "author_id" UUID
);

CREATE TABLE "public"."posts_tags" (
  "post_id" UUID NOT NULL,
  "tag_id" UUID NOT NULL,
  PRIMARY KEY ("post_id", "tag_id")
);

CREATE TABLE "public"."product_locales" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "product_id" UUID,
  "locale" "public"."product_locales_locale" NOT NULL,
  "name" TEXT,
  "description" TEXT
);

CREATE TABLE "public"."products" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" TEXT NOT NULL,
  "sku" TEXT UNIQUE NOT NULL,
  "description" TEXT,
  "images" TEXT[],
  "available_locales" TEXT[],
  "brand" TEXT,
  "category" "public"."products_category" NOT NULL,
  "price" NUMERIC NOT NULL,
  "compare_at_price" NUMERIC,
  "cost" NUMERIC,
  "stock_quantity" NUMERIC NOT NULL,
  "low_stock_threshold" NUMERIC,
  "weight_grams" NUMERIC,
  "rating" NUMERIC,
  "review_count" NUMERIC,
  "status" "public"."products_status" NOT NULL,
  "is_featured" BOOLEAN,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE "public"."tags" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" TEXT NOT NULL
);

CREATE TABLE "public"."tickets" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "ticket_number" TEXT UNIQUE NOT NULL,
  "subject" TEXT NOT NULL,
  "description" TEXT,
  "resolution_notes" TEXT,
  "status" "public"."tickets_status" NOT NULL,
  "priority" "public"."tickets_priority" NOT NULL,
  "category" "public"."tickets_category",
  "customer_id" UUID,
  "assigned_to" TEXT,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "order" TEXT
);

CREATE TABLE "rebase"."users" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "email" TEXT UNIQUE NOT NULL,
  "display_name" TEXT,
  "photo_url" TEXT,
  "roles" TEXT[],
  "password_hash" TEXT,
  "email_verified" BOOLEAN,
  "email_verification_token" TEXT,
  "email_verification_sent_at" TIMESTAMP WITH TIME ZONE,
  "metadata" JSONB,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Foreign Key Constraints
ALTER TABLE "public"."order_items" ADD CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders" ("id") ON DELETE CASCADE;
ALTER TABLE "public"."order_items" ADD CONSTRAINT "order_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products" ("id") ON DELETE RESTRICT;
ALTER TABLE "public"."orders" ADD CONSTRAINT "orders_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers" ("id") ON DELETE CASCADE;
ALTER TABLE "public"."posts" ADD CONSTRAINT "posts_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "public"."authors" ("id") ON DELETE SET NULL;
ALTER TABLE "public"."posts_tags" ADD CONSTRAINT "posts_tags_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts" ("id") ON DELETE CASCADE;
ALTER TABLE "public"."posts_tags" ADD CONSTRAINT "posts_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags" ("id") ON DELETE CASCADE;
ALTER TABLE "public"."product_locales" ADD CONSTRAINT "product_locales_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products" ("id") ON DELETE SET NULL;
ALTER TABLE "public"."tickets" ADD CONSTRAINT "tickets_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers" ("id") ON DELETE SET NULL;

