-- This file is auto-generated by the Rebase DDL generator. Do not edit manually.
--
-- Full-text search for the collections declaring a `search` block.
-- Applied by Rebase, not by Atlas — see generatePostgresSearchDdl.

CREATE OR REPLACE FUNCTION public.rebase_search_text(text[]) RETURNS text
    LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS
    $$ SELECT array_to_string($1, ' ') $$;

CREATE OR REPLACE FUNCTION public.rebase_search_text(jsonb) RETURNS text
    LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS
    $$ SELECT coalesce(string_agg(v, ' '), '')
       FROM jsonb_array_elements_text(jsonb_path_query_array($1, 'strict $.**?(@.type() == "string")')) AS v $$;

ALTER TABLE "public"."posts" ADD COLUMN IF NOT EXISTS "search_vector" tsvector GENERATED ALWAYS AS (setweight(to_tsvector('english', coalesce("title", '')), 'A') || setweight(to_tsvector('english', coalesce("excerpt", '')), 'C') || setweight(to_tsvector('english', public.rebase_search_text(coalesce("content", '{}'::jsonb))), 'D')) STORED;
CREATE INDEX IF NOT EXISTS "posts_search_vector_gin" ON "public"."posts" USING GIN ("search_vector");

