-- This file is auto-generated by the Rebase DDL generator. Do not edit manually.
--
-- `updated_at` triggers, for the properties declaring `autoValue: "on_update"`.
-- Applied by Rebase, not by Atlas — a trigger is a function plus a binding,
-- and Atlas's free tier refuses to parse a desired state containing one.

CREATE OR REPLACE FUNCTION rebase.set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], now()));
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "customers_updated_at_touch" ON "public"."customers";
CREATE TRIGGER "customers_updated_at_touch" BEFORE UPDATE ON "public"."customers" FOR EACH ROW EXECUTE FUNCTION rebase.set_updated_at('updated_at');

DROP TRIGGER IF EXISTS "exercises_updated_at_touch" ON "public"."exercises";
CREATE TRIGGER "exercises_updated_at_touch" BEFORE UPDATE ON "public"."exercises" FOR EACH ROW EXECUTE FUNCTION rebase.set_updated_at('updated_at');

DROP TRIGGER IF EXISTS "orders_updated_at_touch" ON "public"."orders";
CREATE TRIGGER "orders_updated_at_touch" BEFORE UPDATE ON "public"."orders" FOR EACH ROW EXECUTE FUNCTION rebase.set_updated_at('updated_at');

DROP TRIGGER IF EXISTS "posts_updated_at_touch" ON "public"."posts";
CREATE TRIGGER "posts_updated_at_touch" BEFORE UPDATE ON "public"."posts" FOR EACH ROW EXECUTE FUNCTION rebase.set_updated_at('updated_at');

DROP TRIGGER IF EXISTS "products_updated_at_touch" ON "public"."products";
CREATE TRIGGER "products_updated_at_touch" BEFORE UPDATE ON "public"."products" FOR EACH ROW EXECUTE FUNCTION rebase.set_updated_at('updated_at');

DROP TRIGGER IF EXISTS "tickets_updated_at_touch" ON "public"."tickets";
CREATE TRIGGER "tickets_updated_at_touch" BEFORE UPDATE ON "public"."tickets" FOR EACH ROW EXECUTE FUNCTION rebase.set_updated_at('updated_at');

DROP TRIGGER IF EXISTS "users_updated_at_touch" ON "rebase"."users";
CREATE TRIGGER "users_updated_at_touch" BEFORE UPDATE ON "rebase"."users" FOR EACH ROW EXECUTE FUNCTION rebase.set_updated_at('updated_at');

