/**
 * `ipVersion` is `net.isIP`.
 *
 * The SSRF guard decides whether to resolve a host by asking whether it is
 * already a literal address, and then judges the bytes it gets back. Both
 * halves depend on that question being answered the way the platform answers
 * it: a validator that is *stricter* than `net.isIP` sends a literal down the
 * resolution path, and one that is *looser* accepts a string as an address and
 * judges the wrong bytes — `blockedAddressReason` would then approve a
 * destination on the strength of a parse nobody else agrees with.
 *
 * `ipVersion` exists because `node:net` does not, on the runtimes this is
 * eventually meant to run on (see `contracts/portable-core.txt`). It is a
 * transcription of Node's own grammar, and a transcription is worth exactly
 * what its check is worth — so this compares the two directly, over addresses
 * generated to sit on the boundaries where a hand-written grammar goes wrong:
 * the `::` elision at every position, embedded dotted quads, zone ids, and
 * near-misses like `256`, a fifth octet, or two elisions in one address.
 */

import fc from "fast-check";
import net from "node:net";
import { ipVersion } from "../../src/utils/ip-address";

const RUNS = Number(process.env.FC_RUNS ?? 5000);

/** Hex groups, weighted so short and boundary-length groups dominate. */
const group = fc.oneof(
    { arbitrary: fc.constantFrom("0", "1", "a", "ff", "abcd", "0000", "ffff"), weight: 6 },
    { arbitrary: fc.stringMatching(/^[0-9a-fA-F]{1,5}$/), weight: 2 }
);

/** Octet-ish strings, including the ones that are one past the edge. */
const octet = fc.oneof(
    { arbitrary: fc.constantFrom("0", "1", "9", "10", "99", "100", "199", "200", "249", "255"), weight: 6 },
    { arbitrary: fc.constantFrom("256", "300", "999", "01", "00", "", "1e2", "-1"), weight: 4 }
);

const dottedQuad = fc.array(octet, { minLength: 3, maxLength: 5 }).map(parts => parts.join("."));

/**
 * Address-shaped strings. Assembled rather than listed, so a spelling nobody
 * thought of is generated by composition — which is the only way this catches
 * the branch of the grammar that was mistyped.
 */
const addressLike = fc.oneof(
    dottedQuad,
    fc.array(group, { minLength: 0, maxLength: 9 }).map(parts => parts.join(":")),
    // `::` at an arbitrary position, which is the whole difficulty of the grammar.
    fc.tuple(
        fc.array(group, { maxLength: 4 }),
        fc.array(group, { maxLength: 4 })
    ).map(([head, tail]) => `${head.join(":")}::${tail.join(":")}`),
    // A trailing embedded IPv4, legal only in the last 32 bits.
    fc.tuple(fc.array(group, { maxLength: 6 }), dottedQuad)
        .map(([head, quad]) => `${head.join(":")}${head.length ? ":" : "::"}${quad}`),
    // Zone ids, two elisions, brackets, whitespace: all near-misses.
    fc.tuple(fc.array(group, { maxLength: 3 }), fc.constantFrom("%eth0", "%1", "::", " ", "[", "]", "/64"))
        .map(([head, suffix]) => `${head.join(":")}::1${suffix}`),
    fc.string({ maxLength: 20 })
);

describe("ipVersion", () => {
    it("answers exactly what net.isIP answers", () => {
        fc.assert(fc.property(addressLike, (address) => {
            expect(ipVersion(address)).toBe(net.isIP(address));
        }), { numRuns: RUNS });
    });

    it("agrees on the addresses the guard actually reasons about", () => {
        // The literals `blockedAddressReason` has branches for. Generated
        // coverage is the point above; these are here so a regression names
        // itself rather than arriving as a shrunk random string.
        const cases = [
            "127.0.0.1", "10.0.0.1", "169.254.169.254", "192.168.1.1", "172.16.0.1",
            "0.0.0.0", "255.255.255.255", "8.8.8.8",
            "::1", "::", "::ffff:127.0.0.1", "::ffff:7f00:1", "64:ff9b::127.0.0.1",
            "fe80::1", "fe80::1%eth0", "fc00::1", "2001:db8::1",
            "2001:0db8:0000:0000:0000:0000:0000:0001",
            "256.1.1.1", "1.2.3", "1.2.3.4.5", "localhost", "", "::1::2", "1:2:3:4:5:6:7:8:9"
        ];
        for (const address of cases) {
            expect([address, ipVersion(address)]).toEqual([address, net.isIP(address)]);
        }
    });
});
