import fs from "fs";
import path from "path";

/**
 * The English documentation slugs the sidebar publishes, in sidebar order.
 *
 * Both LLM mirrors and the Markdown sitemap read the sidebar out of
 * `astro.config.mjs` as text, because importing it would pull in the whole Astro
 * config. Reading it as text is fine; reading only `slug:` was not.
 *
 * Starlight has a second way to list pages — `{ autogenerate: { directory } }`
 * — and it is the one the UI component reference uses. A `slug:`-only scan
 * cannot see it, so all 99 pages under `docs/ui/**` were missing from
 * `llms.txt`, `llms-full.txt` and `sitemap.md` while `llms-full.txt` itself told
 * the agent reading it to "check there before hand-rolling". The mirror
 * contradicted its own advice and `check:generated` could not notice, because
 * it regenerates the file and diffs it against itself.
 *
 * So the scan walks the sidebar in document order and expands an autogenerated
 * directory in place, the way Starlight does: every page under it, sorted by
 * path, `index` first because that is the directory's own page.
 */

/** The sidebar array of `astro.config.mjs`, as text. */
function readSidebarSource(configPath) {
    const configContent = fs.readFileSync(configPath, "utf-8");
    const sidebarMatch = configContent.match(/sidebar:\s*\[([\s\S]*?)\],?\s*components:/);
    if (!sidebarMatch) return null;
    return sidebarMatch[1];
}

/**
 * Slug for a content file, the way Starlight derives it: the path under the
 * content root, without the extension, with a trailing `/index` dropped.
 *
 * @param {string} contentRoot
 * @param {string} fullPath
 */
export function slugForFile(contentRoot, fullPath) {
    return path
        .relative(contentRoot, fullPath)
        .split(path.sep)
        .join("/")
        .replace(/\.(mdx|md)$/, "")
        .replace(/\/index$/, "")
        // Astro lowercases a slug it derives from a filename, so `Card.mdx` is
        // served at `/docs/ui/components/card`. The expansion below is the only
        // place a slug comes from a filename rather than from an explicit
        // `slug:` in the sidebar, and every one of the 99 UI reference pages is
        // named for its component — so without this the mirrors advertise 95
        // URLs the host answers with a redirect at best.
        .toLowerCase();
}

/** Every `.md`/`.mdx` under `dir`, recursively, as absolute paths. */
function walkPages(dir) {
    /** @type {string[]} */
    const out = [];
    let entries;
    try {
        entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
        return out;
    }
    for (const entry of entries) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) out.push(...walkPages(full));
        else if (/\.(mdx|md)$/.test(entry.name)) out.push(full);
    }
    return out;
}

/**
 * @param {string} configPath   absolute path to astro.config.mjs
 * @param {string} contentRoot  absolute path to src/content/docs
 * @returns {string[]} slugs, in sidebar order, with autogenerated directories expanded
 */
export function extractSidebarSlugs(configPath, contentRoot) {
    const sidebarContent = readSidebarSource(configPath);
    if (sidebarContent === null) return null;

    /** @type {string[]} */
    const slugs = [];
    // One pass, both shapes, so the expansion lands where the entry sits.
    const entry = /slug:\s*["']([^"']+)["']|autogenerate:\s*\{\s*directory:\s*["']([^"']+)["']/g;
    let match;
    while ((match = entry.exec(sidebarContent)) !== null) {
        if (match[1] !== undefined) {
            slugs.push(match[1]);
            continue;
        }
        const dir = match[2];
        const pages = walkPages(path.join(contentRoot, dir))
            .map(p => slugForFile(contentRoot, p))
            .sort((a, b) => {
                // The directory's own `index` page comes first; Starlight puts
                // it at the top of the group rather than under "i".
                if (a === dir) return -1;
                if (b === dir) return 1;
                return a.localeCompare(b);
            });
        slugs.push(...pages);
    }
    return slugs;
}
