/**
 * The bundle corpus: every shape of bundle we have ever shipped, booted on the
 * runtime as it is today.
 *
 * The managed tier moves projects onto new runtime images automatically, in
 * waves, without anyone rebuilding the project. That is the whole promise, and
 * the thing standing behind it has until now been a health gate watching request
 * rates and error rates — which can see a crash loop and cannot see a bundle
 * that quietly stopped loading its collections, a schema version that changed
 * identity under a deployed project, or an old manifest shape that now parses to
 * something subtly different. Those are exactly the regressions a fleet-wide
 * auto-upgrade turns into an outage for everyone at once.
 *
 * So: frozen bundles, checked into `fixtures/bundles/`, booted for real against
 * a real Postgres. They are hand-authored, not generated by `rebase build`, and
 * that is deliberate — a fixture the builder regenerates moves whenever the
 * builder moves, which is the one thing a regression corpus must not do. A
 * fixture here is a historical artifact. When one stops working, the finding is
 * that a bundle already deployed would stop working.
 *
 *     createdb rebase_corpus
 *     node --import tsx tooling/scripts/verify-bundle-corpus.mts
 *
 * Override the database with CORPUS_DATABASE_URL.
 *
 * Adding a bundle: copy the closest existing directory, change `table` in its
 * collections so it owns its own tables, and add an entry to CORPUS below. Record
 * one per release — the value is entirely in how far back the oldest one goes.
 *
 * Like `verify-selfhost.mts`, this imports runtime source BY PATH rather than by
 * package name: in a git worktree `@rebasepro/*` resolves through node_modules
 * into the primary checkout, so a package-name import would verify the wrong code.
 */
import fs from "fs";
import os from "os";
import path from "path";
import { execFileSync } from "child_process";
import { createRequire } from "module";
import { fileURLToPath } from "url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const CORPUS_DIR = path.join(ROOT, "tests", "fixtures", "bundles");

const DATABASE_URL = process.env.CORPUS_DATABASE_URL
    ?? `postgres://${os.userInfo().username}@localhost:5432/rebase_corpus`;

interface CorpusEntry {
    /** Directory under fixtures/bundles. */
    dir: string;
    /** What this bundle is a specimen of — printed, so a failure names the era. */
    describe: string;
    kind: "backend" | "static";
    /** Marker text the bundle's index.html contains, when it serves one. */
    indexMarker?: string;
}

const CORPUS: CorpusEntry[] = [
    {
        dir: "format1-cms",
        describe: "bundle format 1 — `mode: cms`, a bundled admin at entry.admin",
        kind: "backend",
        indexMarker: "CORPUS_FORMAT1_ADMIN_INDEX"
    },
    {
        dir: "format2-backend",
        describe: "bundle format 2 — `kind: backend`, entry.static as a list",
        kind: "backend",
        indexMarker: "CORPUS_FORMAT2_SITE_INDEX"
    },
    {
        dir: "format2-static",
        describe: "bundle format 2 — `kind: static`, no database at all",
        kind: "static",
        indexMarker: "CORPUS_STATIC_INDEX"
    }
];

let failures = 0;
function check(label: string, ok: boolean, detail = ""): void {
    console.log(`${ok ? "  \x1b[32m✓\x1b[0m" : "  \x1b[31m✗\x1b[0m"} ${label}${detail ? ` \x1b[2m— ${detail}\x1b[0m` : ""}`);
    if (!ok) failures++;
}

const { bootFromBundle } = await import(`${ROOT}/packages/server/src/boot/boot.ts`);
const { readBundleManifest } = await import(`${ROOT}/packages/server/src/boot/bundle.ts`);
const { loadCollectionsFromDirectory } = await import(`${ROOT}/packages/server/src/collections/loader.ts`);
const { computeSchemaVersion } = await import(`${ROOT}/packages/types/src/types/schema_version.ts`);

// One database, many bundles. Each fixture's collections own distinct tables, so
// they can share it without colliding — and sharing is closer to the truth than
// a pristine database per bundle would be, because a runtime upgrade always
// lands on a database some earlier runtime already wrote to.
process.env.DATABASE_URL = DATABASE_URL;
process.env.JWT_SECRET ??= "bundle-corpus-jwt-secret-at-least-32-chars";
process.env.REBASE_SERVICE_KEY ??= "bundle-corpus-service-key-at-least-32-chars";
process.env.NODE_ENV = "development";
process.env.REBASE_SERVE_STATIC = "true";
process.env.PORT = "0";
// The managed path, stated rather than inherited: the runtime image's entrypoint
// defaults to `ensure`, and boot-time provisioning is precisely what a fleet
// upgrade relies on — an old bundle landing on a new runtime has to arrive at
// its own tables and policies without anyone running a migration.
process.env.REBASE_MIGRATE_ON_BOOT = "ensure";

const asService = { authorization: `Bearer ${process.env.REBASE_SERVICE_KEY}` };

/**
 * A deployable copy of a fixture.
 *
 * A checked-in bundle has no `node_modules`; a deployed one does, because the
 * container npm-installs the bundle's dependencies into it on first start and
 * `rebase start` links already-installed ones in. Booting the fixture in place
 * would therefore be testing something no deployment ever looks like — and would
 * also mean writing symlinks into the corpus, which must stay pristine.
 *
 * So each fixture is copied to a scratch directory and given the modules a
 * deployment would have. `app/backend` is the borrowed tree: it is the reference
 * project, so it carries exactly the packages a real bundle's install produces.
 */
const DONOR_MODULES = [
    path.join(ROOT, "app", "backend", "node_modules"),
    path.join(ROOT, "app", "node_modules"),
    path.join(ROOT, "node_modules")
];

function stage(bundleDir: string, name: string): string {
    const staged = fs.mkdtempSync(path.join(os.tmpdir(), `rebase-corpus-${name}-`));
    fs.cpSync(bundleDir, staged, { recursive: true });

    const donor = DONOR_MODULES.find(d => fs.existsSync(path.join(d, "@rebasepro", "server-postgres")));
    if (!donor) {
        // Loudly, rather than booting without a driver and reporting the
        // resulting failure as if the BUNDLE were broken. A missing install is
        // an environment problem and has to read as one.
        throw new Error(
            "No node_modules containing @rebasepro/server-postgres was found to lend the staged bundle.\n" +
            `Looked in:\n${DONOR_MODULES.map(d => `  ${d}`).join("\n")}\n` +
            "Run an install first (and in a git worktree, symlink app/backend/node_modules from the primary checkout)."
        );
    }
    fs.symlinkSync(donor, path.join(staged, "node_modules"), "dir");
    return staged;
}

const staged: string[] = [];

/**
 * Driver versions a deployed bundle may still be carrying.
 *
 * Pinned, not discovered from npm: a corpus whose inputs move is not a corpus.
 * Add a version when one ships; remove one only when no deployed project can
 * still be on it, which is a decision about the fleet and not about this file.
 */
const DRIVER_SKEW = ["0.10.0", "0.11.0", "0.12.0", "0.13.0", "0.14.0", "0.14.1", "0.15.0", "0.16.0", "0.17.3"];

/** The fixture the skew pass exercises — current format, real collections, real writes. */
const SKEW_FIXTURE = "format2-backend";

/**
 * The oldest driver that can still build its own collection tables at boot.
 *
 * Two different things break with an old driver, and only one of them is what a
 * fleet rollout does. Serving tables that already exist is the rollout case, and
 * every driver back to 0.10.0 manages it — that is what the pass below asserts.
 * CREATING them is a different capability, and drivers before this floor simply
 * do not expose it: the runtime logs "Collection schema: skipped … Collection
 * tables will NOT be created" and every /api/data route 500s on a missing
 * relation the moment a project adds a collection or deploys fresh.
 *
 * Pinned here so the number is measured rather than assumed. It is the value
 * `minimumFrameworkVersion` on a runtime release should carry — the column that
 * exists precisely to refuse a bundle whose driver is too old, and that is NULL
 * on every release ever registered. Nothing enforces it today, so this constant
 * is currently the only written-down statement of where the floor actually is.
 *
 * If a runtime change moves it, the assertion below fails in both directions:
 * a driver that could provision and now cannot, and a floor that quietly slid.
 */
const PROVISIONING_FLOOR = "0.13.0";

/** Numeric-segment compare, enough for the pinned `x.y.z` list above. */
function gte(a: string, b: string): boolean {
    const pa = a.split(".").map(Number);
    const pb = b.split(".").map(Number);
    for (let i = 0; i < 3; i++) {
        if ((pa[i] ?? 0) !== (pb[i] ?? 0)) return (pa[i] ?? 0) > (pb[i] ?? 0);
    }
    return true;
}

/**
 * Stage a fixture carrying a SPECIFIC published driver, stitched the way a
 * deployed pod is stitched.
 *
 * This is the axis the corpus could not see. `stage()` above lends the whole
 * donor `node_modules`, so both halves come from this checkout and every run
 * boots current-driver + current-server — a pairing that exists on no tenant
 * anywhere. Production is the opposite: `infra/docker/entrypoint.mjs` collapses
 * the packages in its `RUNTIME_PROVIDED` list — the framework and `zod`, never
 * the driver — onto the image's copies, so a project runs today's runtime
 * against whatever driver it was built with, possibly years old.
 *
 * The list is mirrored here as `RUNTIME_PROVIDED` and held to the entrypoint's
 * by `tooling/scripts/test/runtime-provided.test.mjs`. It used to be
 * hand-written as "only `@rebasepro/server`", which was true once and then
 * silently wasn't: the driver's own `@rebasepro/types` stayed in place beside
 * the checkout's, two resource-kind registries met, and the corpus failed a
 * pairing production had stopped producing.
 *
 * That combination has already taken production down once — a driver too old to
 * have the `refresh_tokens` constraint the newer runtime assumed, which is why
 * `minimumFrameworkVersion` exists on a runtime release. It is NULL on every
 * release ever registered, so nothing has ever enforced it. This is the thing
 * that would have caught it.
 *
 * `npm install` rather than a donor symlink, because the point is to get the
 * driver's own dependency closure as npm would resolve it for a real project.
 */
function stageWithDriver(fixtureDir: string, name: string, driverVersion: string): string {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), `rebase-corpus-${name}-d${driverVersion}-`));
    fs.cpSync(fixtureDir, dir, { recursive: true });

    // npm needs something to install into; the fixture has no package.json
    // because a bundle is not a package.
    fs.writeFileSync(
        path.join(dir, "package.json"),
        JSON.stringify({ name: `corpus-${name}`, version: "0.0.0", private: true, type: "module" }, null, 2)
    );

    execFileSync(
        "npm",
        ["install", "--no-save", "--no-audit", "--no-fund", "--loglevel=error",
            `@rebasepro/server-postgres@${driverVersion}`],
        { cwd: dir, stdio: "pipe", encoding: "utf8" }
    );

    // The entrypoint's RUNTIME_PROVIDED, reproduced: the image's copy of each
    // listed package wins over whatever the bundle installed, and nothing else
    // is touched — the driver in particular stays the version npm resolved, which
    // is the whole point of this axis. Framework packages come from this
    // checkout's `packages/`; `zod` is whichever copy `@rebasepro/server` itself
    // resolves, because that is the one the image ships beside it.
    for (const pkg of RUNTIME_PROVIDED) {
        const target = path.join(dir, "node_modules", pkg);
        const source = pkg.startsWith("@rebasepro/")
            ? path.join(ROOT, "packages", pkg.slice("@rebasepro/".length))
            : path.dirname(createRequire(path.join(ROOT, "packages", "server", "package.json"))
                .resolve(`${pkg}/package.json`));
        if (!fs.existsSync(source)) {
            throw new Error(`RUNTIME_PROVIDED names ${pkg}, but this checkout has nothing at ${source} to stitch in.`);
        }
        fs.rmSync(target, { recursive: true, force: true });
        fs.mkdirSync(path.dirname(target), { recursive: true });
        fs.symlinkSync(source, target, "dir");
    }

    return dir;
}

/**
 * What the image supplies on top of a bundle — the entrypoint's list, verbatim.
 * `runtime-provided.test.mjs` fails if this drifts from `infra/docker/entrypoint.mjs`.
 */
const RUNTIME_PROVIDED = [
    "@rebasepro/server",
    "@rebasepro/types",
    "@rebasepro/client",
    "@rebasepro/common",
    "@rebasepro/utils",
    "zod"
];

/**
 * An empty database for one skew run, dropped and recreated so a rerun starts
 * where a fresh deployment starts: with nothing, and a driver that has to build
 * its own tables or fail trying.
 */
async function freshDatabase(baseUrl: string, driverVersion: string): Promise<string> {
    // Resolved from a package that actually depends on `pg`, rather than from
    // `tooling/scripts/` which does not — same reason the runtime imports above go by
    // path. `createRequire` rather than a directory import, because `pg` is CJS
    // and ESM will not read `main` out of a directory.
    const anchors = [
        path.join(ROOT, "packages", "server-postgres", "package.json"),
        path.join(ROOT, "app", "backend", "package.json")
    ].filter(p => fs.existsSync(p));

    let pg: any;
    for (const anchor of anchors) {
        try {
            pg = createRequire(anchor)("pg");
            break;
        } catch { /* try the next anchor */ }
    }
    if (!pg) throw new Error("No `pg` package found to create the skew database with — run an install first.");

    const name = `rebase_corpus_skew_${driverVersion.replace(/[^a-zA-Z0-9]/g, "_")}`;

    const admin = new pg.Client({ connectionString: baseUrl });
    await admin.connect();
    try {
        // Identifiers cannot be bind parameters; the name is built from a
        // version string this file pins, and non-alphanumerics are stripped above.
        await admin.query(`DROP DATABASE IF EXISTS "${name}"`);
        await admin.query(`CREATE DATABASE "${name}"`);
    } finally {
        await admin.end();
    }

    const url = new URL(baseUrl);
    url.pathname = `/${name}`;
    return url.toString();
}

/**
 * Boot a staged bundle against the empty database and report whether its
 * collection tables ended up there.
 *
 * Deliberately quiet: a driver that cannot provision is an expected outcome
 * below the floor, not a failure, so this returns a boolean instead of calling
 * `check`. The caller decides what the answer should have been.
 */
async function provisionsFromEmpty(bundleDir: string): Promise<boolean> {
    let booted: any;
    try {
        booted = await bootFromBundle({ bundleDir, listen: false, handleSignals: false });
        const res = await booted.app.fetch(
            new Request("http://localhost/api/data/notes?limit=1", { headers: asService })
        );
        return res.status === 200;
    } catch {
        return false;
    } finally {
        await booted?.shutdown?.().catch(() => {});
    }
}

/**
 * Boot the representative fixture once per historical driver.
 *
 * Needs the network. Skipped rather than failed when `CORPUS_SKIP_SKEW` is set,
 * so an offline local run still exercises the format axis — but it announces the
 * skip, because a silently narrowed gate is the failure mode this whole file
 * exists to prevent.
 */
async function runSkewPass(): Promise<void> {
    const fixtureDir = path.join(CORPUS_DIR, SKEW_FIXTURE);
    const entry = CORPUS.find(e => e.dir === SKEW_FIXTURE);
    if (!entry) throw new Error(`SKEW_FIXTURE ${SKEW_FIXTURE} is not in CORPUS`);

    const sharedUrl = process.env.DATABASE_URL!;

    if (process.env.CORPUS_SKIP_SKEW) {
        console.log(
            `\n\x1b[33m▸ version skew SKIPPED\x1b[0m \x1b[2m(CORPUS_SKIP_SKEW set) — ` +
            `${DRIVER_SKEW.length} driver version(s) not tested\x1b[0m`
        );
        return;
    }

    for (const driverVersion of DRIVER_SKEW) {
        console.log(
            `\n\x1b[1m▸ ${SKEW_FIXTURE} on driver ${driverVersion}\x1b[0m ` +
            `\x1b[2mtoday's @rebasepro/server over a bundle built with server-postgres ${driverVersion}\x1b[0m`
        );
        let bundleDir: string;
        try {
            bundleDir = stageWithDriver(fixtureDir, SKEW_FIXTURE, driverVersion);
            staged.push(bundleDir);
        } catch (err) {
            check(`installs @rebasepro/server-postgres@${driverVersion}`, false,
                err instanceof Error ? err.message.split("\n")[0] : String(err));
            continue;
        }

        // A database of this driver's own, and the reason is the whole point of
        // the pass. The format axis deliberately shares one database because a
        // runtime upgrade lands on a database an earlier runtime wrote to — true
        // there, and wrong here: sharing hands the old driver tables that only a
        // NEWER one could have created.
        //
        // That is not hypothetical. The first version of this pass shared, and
        // every driver went green while the 0.10.0 run was logging "Collection
        // tables will NOT be created, so every /api/data route will fail on a
        // missing relation" — it then read a row the current driver had inserted
        // minutes earlier, same id in all four runs. A gate that reports success
        // over a log line saying the opposite is worse than no gate.
        try {
            process.env.DATABASE_URL = await freshDatabase(sharedUrl, driverVersion);
        } catch (err) {
            check(`provisions a database for driver ${driverVersion}`, false,
                err instanceof Error ? err.message : String(err));
            continue;
        }

        try {
            // Give the database the tables a project of this era would already
            // have, by booting the current driver over it once and shutting it
            // down. Without this the pass answers the wrong question.
            //
            // Two different things can go wrong with an old driver, and only one
            // of them is what a fleet upgrade does:
            //
            //   * it cannot CREATE collection tables at boot — true of every
            //     driver before 0.13, and it matters when a project adds a
            //     collection, not when the platform moves it to a new image.
            //   * it cannot SERVE tables that already exist — this is the fleet
            //     case, because every project being moved has been running.
            //
            // Testing on an empty database only ever measures the first, and
            // reddens permanently for every historical driver, which is how a
            // gate gets switched off. The seed makes the assertions below
            // measure the second.
            const seedDir = stage(fixtureDir, `${SKEW_FIXTURE}-seed`);
            staged.push(seedDir);
            // Before seeding, while the database is still empty: can this driver
            // stand a project up from nothing? That is the capability
            // `minimumFrameworkVersion` is meant to gate, and asserting it here
            // turns "we noticed once" into a fact CI re-derives every run.
            const canProvision = await provisionsFromEmpty(bundleDir);
            const shouldProvision = gte(driverVersion, PROVISIONING_FLOOR);
            check(
                `self-provisions from an empty database: ${shouldProvision ? "yes" : "no"} (floor ${PROVISIONING_FLOOR})`,
                canProvision === shouldProvision,
                canProvision === shouldProvision
                    ? ""
                    : canProvision
                        ? `${driverVersion} provisioned but the floor says it cannot — the floor moved DOWN, lower PROVISIONING_FLOOR`
                        : `${driverVersion} did NOT provision though the floor says it should — a runtime change removed the capability`
            );

            const seed = await bootFromBundle({ bundleDir: seedDir, listen: false, handleSignals: false });
            await seed.shutdown?.().catch(() => {});

            await verifyBundle(entry, bundleDir);
        } catch (err) {
            check(`seeds a database for driver ${driverVersion}`, false,
                err instanceof Error ? err.message : String(err));
        } finally {
            process.env.DATABASE_URL = sharedUrl;
        }
    }
}

/**
 * Boot one staged bundle and assert everything a deployed project depends on.
 *
 * Factored out because the same assertions have to run twice over: once per
 * bundle *shape* (the format axis, below) and once per *driver version* the
 * bundle might be carrying (the skew axis, further down). Both are ways a
 * deployed project can stop working under a runtime it did not choose, and a
 * check that only proves one of them is a check that reads as coverage it does
 * not have.
 */
async function verifyBundle(entry: CorpusEntry, bundleDir: string): Promise<void> {
    // Read the manifest before booting: a format the runtime refuses is a
    // different (and much louder) failure than one that boots and misbehaves,
    // and the corpus should tell them apart.
    let manifest: Record<string, unknown>;
    try {
        manifest = readBundleManifest(bundleDir) as Record<string, unknown>;
        check("manifest reads on this runtime", true);
    } catch (err) {
        check("manifest reads on this runtime", false, err instanceof Error ? err.message : String(err));
        return;
    }

    // Format 1 said `mode`; format 2 says `kind`. An old bundle must arrive at
    // the same meaning, and this is the direction with no version gate behind it
    // — a renamed field simply reads as absent, and every gate keyed on it skips
    // in silence. Nothing else in the suite proves the normalisation ran.
    check(`normalises to kind: ${entry.kind}`, manifest.kind === entry.kind, String(manifest.kind));

    let booted: any;
    try {
        booted = await bootFromBundle({ bundleDir, listen: false, handleSignals: false });
        check("boots", true);
    } catch (err) {
        check("boots", false, err instanceof Error ? err.message : String(err));
        return;
    }

    const get = async (url: string, headers: Record<string, string> = {}) => {
        const res = await booted.app.fetch(new Request(`http://localhost${url}`, { headers }));
        return { status: res.status, body: await res.text() };
    };

    try {
        // Liveness must never touch the database, on any bundle era — an
        // orchestrator killing healthy pods during a database blip is how one
        // slow query becomes a fleet outage.
        check("GET /livez", (await get("/livez")).status === 200);

        if (entry.kind === "backend") {
            check("GET /health", (await get("/health")).status === 200, "a real database round-trip");

            // The identity of a deployed project's schema must not drift under
            // it, and proving that takes an INDEPENDENT computation.
            //
            // `GET /api/meta/schema-version` cannot supply one: `schemaVersionOf`
            // returns the manifest's value verbatim whenever the bundle declares
            // it, and only computes from collections when it does not. Comparing
            // the endpoint to the manifest therefore compares the manifest to
            // itself and passes on a bundle whose declared version is nonsense —
            // which is exactly what it did here until a deliberately corrupted
            // fixture still went green.
            //
            // So the hash is recomputed from the bundle's own collections with
            // the same function the CLI used at build time. The manifest's value
            // is the CLI's answer, frozen; this is the runtime's answer, now. If
            // they part company, every deployed bundle's declared schemaVersion
            // is wrong and SDK drift detection has quietly stopped meaning
            // anything.
            const declared = String(manifest.schemaVersion ?? "");
            const collectionsDir = path.join(bundleDir, String((manifest.entry as any)?.collections));
            const loaded = await loadCollectionsFromDirectory(collectionsDir);
            const recomputed = computeSchemaVersion(loaded);
            check("collections load from the bundle", loaded.length > 0, `${loaded.length} collection(s)`);
            check("schema-version recomputes to the frozen value", recomputed === declared,
                `manifest ${declared || "(none)"} vs recomputed ${recomputed}`);

            // And the endpoint still serves the stamp, which is what an SDK polls.
            const reported = (await get("/api/meta/schema-version")).body;
            check("schema-version endpoint serves it", reported.includes(declared), reported.slice(0, 60));

            // The collections actually loaded, and their tables actually exist —
            // boot creates them additively. A bundle whose collections silently
            // failed to load looks perfectly healthy right up to the first query.
            const slug = entry.dir === "format1-cms" ? "notes" : "notes";
            const authed = await get(`/api/data/${slug}?limit=1`, asService);
            check(`GET /api/data/${slug} as a service`, authed.status === 200,
                `${authed.status} ${authed.body.slice(0, 70)}`);

            // Writes go through the same policy path reads do; a read-only check
            // would miss an INSERT policy that boot failed to create.
            const created = await booted.app.fetch(new Request("http://localhost/api/data/" + slug, {
                method: "POST",
                headers: { ...asService, "content-type": "application/json" },
                body: JSON.stringify({ title: "corpus write", body: "written by verify-bundle-corpus" })
            }));
            check(`POST /api/data/${slug} as a service`, created.status === 200 || created.status === 201,
                String(created.status));

            // RLS is on and callers are authenticated: an anonymous read is 401
            // regardless of how permissive the row policy is. If this ever
            // returns 200, a runtime upgrade has opened every deployed bundle.
            check(`GET /api/data/${slug} unauthenticated is refused`,
                (await get(`/api/data/${slug}?limit=1`)).status === 401);
        }

        if (entry.indexMarker) {
            const index = await get("/");
            check("serves its index.html", index.body.includes(entry.indexMarker), `${index.status}`);
            // A deep path falls back to the SPA index rather than 404ing, which
            // is what makes client-side routing work at all.
            check("SPA fallback on a deep path",
                (await get("/some/client/route")).body.includes(entry.indexMarker));
        }
    } finally {
        await booted.shutdown?.().catch(() => {});
    }
}

// ── Axis 1: bundle shape ─────────────────────────────────────────────────────
// Every format we have ever shipped, on the driver this checkout has.
for (const entry of CORPUS) {
    const fixtureDir = path.join(CORPUS_DIR, entry.dir);
    console.log(`\n\x1b[1m▸ ${entry.dir}\x1b[0m \x1b[2m${entry.describe}\x1b[0m`);

    if (!fs.existsSync(fixtureDir)) {
        check("fixture exists", false, fixtureDir);
        continue;
    }

    const bundleDir = stage(fixtureDir, entry.dir);
    staged.push(bundleDir);
    await verifyBundle(entry, bundleDir);
}

// ── Axis 2: version skew ─────────────────────────────────────────────────────
await runSkewPass();

for (const dir of staged) fs.rmSync(dir, { recursive: true, force: true });

console.log(failures === 0
    ? `\n\x1b[32m✓ Bundle corpus passed — every shipped bundle shape still boots, and ` +
      `today's runtime still serves a project carrying any of ${DRIVER_SKEW.join(", ")}.\x1b[0m\n`
    : `\n\x1b[31m✗ ${failures} check(s) failed.\x1b[0m\n`);
process.exit(failures === 0 ? 0 : 1);
