// GENERATED by scripts/extract-neat-config.mjs — do not edit by hand.
// Source: website/src/components/NeatBackground.tsx (NEAT_BASE_CONFIG).
//
// Everything the site's hero renders with, including the licence key.
//
// The key is not a secret and copying it here leaks nothing: Neat verifies it
// client-side (ECDSA P-256 over a payload naming the domain), so it already
// ships in the public JS bundle of rebase.pro and is readable with view-source.
// It is domain-locked to rebase.pro, and isDomainMatch() in the library allows
// localhost unconditionally — which is what a Remotion render is. An invalid or
// missing key does not fail the render; it draws a watermark into the canvas.
//
// One thing the site has that this does NOT: a seed. The site never sets one,
// so Neat falls back to "seconds elapsed in the current hour" and the animation
// starts at a different phase on every load. Harmless on a web page, fatal in a
// renderer. See NeatCanvas for how time is pinned instead.
//
// Note `resolution: 0.05`. That is MESH resolution, not pixel resolution:
// the ribbon geometry is built at `240 * resolution` segments a side, so 0.05
// means a 12x12 quad ribbon. The large flat facets ARE the geometry, which is
// why they stay crisp at any output size.

export const NEAT_BASE_CONFIG = {
    // A WebGL context flag, read once when the instance is built — Neat warns
    // and ignores it if set later. Off, every facet edge of the ribbon is a
    // staircase, which the subtle register hid under 0.55 opacity and the
    // loud one puts in plain view (Francesco, 2026-09-10: "some shapes are
    // visibly pixelated"). Multisampling on the default framebuffer; the cost
    // is fill rate on the four canvases the home page mounts, and the frames
    // still come in well under budget on a throttled phone.
    antialias: true,
    // Multisampling only covers the facet edges. The stripes and bars ACROSS
    // a facet are Neat's procedural texture, which `bitmap` (the default)
    // draws through Canvas2D into a fixed 1024px square and then magnifies
    // across a full-viewport ribbon — so every band edge is a coarse grid no
    // amount of MSAA touches. `baked` rasterises the same shapes analytically
    // on the GPU at a resolution derived from the canvas: exact edge
    // coverage, the same mipmapped texture afterwards, the same per-frame
    // cost. Needs WebGL2 and falls back to `bitmap` (with a console warning)
    // without it; does not do squiggles, and this config draws none. Landed in
    // @firecms/neat 1.0.3-canary.20260731173236, which is why the site is on
    // that build rather than 1.0.2.
    textureMode: "baked",
    licenseKey: "NEAT-eyJkb21haW4iOiJyZWJhc2UucHJvIiwiZW1haWwiOiJmcmFuY2VzY29AZmlyZWNtcy5jbyIsImlhdCI6MTc4MTQ4MTE5NX0.0gblm3vGqyk_e9WJ8OTO5SHQ8qF8HmgJQkt_qElKskW5YqOiHPc24ppKmpI6utufEtqbyJ58Vt_uAB2HNtprFQ",
    colors: [
        { color: "#FB5066", enabled: true },
        { color: "#36CCD6", enabled: true },
        { color: "#FFC600", enabled: true },
        { color: "#8B6AE6", enabled: true },
        { color: "#2E0EC7", enabled: true },
        { color: "#FF9A9E", enabled: true },
    ],
    speed: 0.3,
    horizontalPressure: 3,
    verticalPressure: 3,
    waveFrequencyX: 3,
    waveFrequencyY: 5,
    waveAmplitude: 10,
    shadows: 2,
    highlights: 6,
    colorBrightness: 0.25,
    colorSaturation: 1,
    wireframe: false,
    colorBlending: 3,
    backgroundColor: "#000000",
    backgroundAlpha: 0,
    grainScale: 0,
    grainSparsity: 0,
    grainIntensity: 0,
    grainSpeed: 2.4,
    resolution: 0.05,
    yOffset: 0,
    yOffsetWaveMultiplier: 7.2,
    yOffsetColorMultiplier: 6.8,
    yOffsetFlowMultiplier: 7.7,
    flowDistortionA: 0.4,
    flowDistortionB: 2.6,
    flowScale: 1.9,
    flowEase: 0.94,
    flowEnabled: true,
    enableProceduralTexture: true,
    transparentTextureVoid: false,
    textureVoidLikelihood: 0.59,
    textureVoidWidthMin: 120,
    textureVoidWidthMax: 330,
    textureBandDensity: 0.1,
    textureColorBlending: 0,
    textureSeed: 478,
    textureEase: 0.86,
    proceduralBackgroundColor: "#000000",
    textureShapeTriangles: 51,
    textureShapeCircles: 0,
    textureShapeBars: 15,
    textureShapeSquiggles: 0,
    domainWarpEnabled: false,
    domainWarpIntensity: 0,
    domainWarpScale: 3,
    vignetteIntensity: 0,
    vignetteRadius: 0.8,
    fresnelEnabled: false,
    fresnelPower: 2,
    fresnelIntensity: 0.5,
    fresnelColor: "#FFFFFF",
    iridescenceEnabled: false,
    iridescenceIntensity: 0.5,
    iridescenceSpeed: 1,
    bloomIntensity: 0,
    bloomThreshold: 0.7,
    chromaticAberration: 0,
    shapeType: "ribbon",
    shapeRotationX: 0,
    shapeRotationY: 0,
    shapeRotationZ: 0,
    shapeAutoRotateSpeedX: 0,
    shapeAutoRotateSpeedY: 0,
    sphereRadius: 30,
    torusRadius: 15,
    torusTube: 5,
    cylinderRadius: 10,
    cylinderHeight: 40,
    planeBend: -0.7,
    planeTwist: 1,
    silhouetteFade: 0,
    cylinderFade: 0.08,
    // NOT 0. On a `shapeType: "ribbon"` — which this is — a `ribbonFade` of
    // exactly 0 draws nothing at all: the canvas comes back as a flat fill of
    // `backgroundColor`, with no error, no warning and no watermark. It sat at
    // 0 for as long as this file has existed, so every hero on the site was
    // rendering an empty canvas, and nothing looked broken because the canvas is
    // held at `opacity: 0.55` over a near-black page — "no gradient" and "a very
    // dim gradient" are the same picture. Found 2026-09-07 when the blog cards,
    // which are the same component at full opacity, came up black.
    ribbonFade: 0.08,
    flatShading: true,
    cameraLock: false,
    cameraX: 0,
    cameraY: -9.5,
    cameraZ: 0,
    cameraRotationX: 0.8310000000000001,
    cameraRotationY: 0.483,
    cameraRotationZ: 0,
    cameraZoom: 2.3,
} as const;

/** The site's two registers (HERO_TONES in NeatBackground.tsx): the light,
 *  never the shape. */
export const HERO_TONES = {
    subtle: { colorBrightness: 0.25, colorSaturation: 1, opacity: 0.55 },
    loud: { colorBrightness: 0.85, colorSaturation: 1.2, opacity: 1 },
} as const;
