-- ─────────────────────────────────────────────────────────────────────────────
-- Recorded snapshot — @rebasepro/server-postgres v0.17.3, auth schema version 2.
--
-- Generated by tooling/scripts/record-schema-snapshot.mts from a database this release
-- provisioned. Do not hand-edit: it is a record of a schema that shipped, and
-- editing it to make a test pass un-tests every upgrade path through it.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE SCHEMA rebase;

CREATE FUNCTION rebase.jwt() RETURNS jsonb
    LANGUAGE sql STABLE
    AS $$
    SELECT COALESCE(
        NULLIF(current_setting('app.jwt', true), ''),
        '{}'
    )::jsonb;
$$;

CREATE FUNCTION rebase.rebase_cdc_notify() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    rec     jsonb;
    payload text;
BEGIN
    IF (TG_OP = 'DELETE') THEN
        rec := to_jsonb(OLD);
    ELSE
        rec := to_jsonb(NEW);
    END IF;

    payload := json_build_object(
        'schema', TG_TABLE_SCHEMA,
        'table',  TG_TABLE_NAME,
        'op',     TG_OP,
        'row',    rec
    )::text;

    -- Never let CDC abort the write: if the full row overflows the pg_notify
    -- 8000-byte cap, emit an identity-only payload the consumer can still route
    -- (and refetch the authoritative row from).
    IF (octet_length(payload) > 7900) THEN
        payload := json_build_object(
            'schema',    TG_TABLE_SCHEMA,
            'table',     TG_TABLE_NAME,
            'op',        TG_OP,
            'row',       CASE WHEN rec ? 'id' THEN jsonb_build_object('id', rec->'id') ELSE '{}'::jsonb END,
            'truncated', true
        )::text;
    END IF;

    PERFORM pg_notify('rebase_cdc', payload);
    RETURN NULL;
END;
$$;

CREATE FUNCTION rebase.roles() RETURNS text
    LANGUAGE sql STABLE
    AS $$
    SELECT COALESCE(NULLIF(current_setting('app.user_roles', true), ''), '');
$$;

CREATE FUNCTION rebase.uid() RETURNS text
    LANGUAGE sql STABLE
    AS $$
    SELECT COALESCE(
        NULLIF(current_setting('app.uid', true), ''),
        NULLIF(current_setting('app.user_id', true), '')
    );
$$;

CREATE TABLE rebase.api_keys (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    name text NOT NULL,
    key_prefix text NOT NULL,
    key_hash text NOT NULL,
    permissions jsonb DEFAULT '[]'::jsonb NOT NULL,
    admin boolean DEFAULT false NOT NULL,
    rate_limit integer,
    created_by text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    last_used_at timestamp with time zone,
    expires_at timestamp with time zone,
    revoked_at timestamp with time zone
);

CREATE TABLE rebase.app_config (
    key text NOT NULL,
    value jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE rebase.branches (
    name text NOT NULL,
    db_name text NOT NULL,
    parent_db text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE rebase.entity_history (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    table_name text NOT NULL,
    entity_id text NOT NULL,
    action text NOT NULL,
    changed_fields text[],
    "values" jsonb,
    previous_values jsonb,
    updated_by text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE rebase.magic_link_tokens (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid uuid NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE rebase.metric_samples (
    at timestamp with time zone NOT NULL,
    series text NOT NULL,
    instance text NOT NULL,
    value double precision NOT NULL
);

CREATE TABLE rebase.mfa_challenges (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    factor_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    verified_at timestamp with time zone,
    ip_address text,
    attempts integer DEFAULT 0 NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

CREATE TABLE rebase.mfa_factors (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid uuid NOT NULL,
    factor_type text DEFAULT 'totp'::text NOT NULL,
    secret_encrypted text NOT NULL,
    friendly_name text,
    verified boolean DEFAULT false,
    last_used_counter bigint,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE rebase.password_reset_tokens (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid uuid NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE rebase.recovery_codes (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid uuid NOT NULL,
    code_hash text NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE rebase.refresh_tokens (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid uuid NOT NULL,
    session_id text DEFAULT (gen_random_uuid())::text NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked boolean DEFAULT false NOT NULL,
    rotated_at timestamp with time zone,
    session_started_at timestamp with time zone DEFAULT now() NOT NULL,
    user_agent text,
    ip_address text,
    created_at timestamp with time zone DEFAULT now(),
    aal text
);

CREATE TABLE rebase.schema_meta (
    key text NOT NULL,
    value text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE rebase.user_identities (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    uid uuid NOT NULL,
    provider text NOT NULL,
    provider_id text NOT NULL,
    profile_data jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE rebase.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    display_name text,
    photo_url text,
    roles text[] DEFAULT '{}'::text[] NOT NULL,
    password_hash text,
    email_verified boolean DEFAULT false NOT NULL,
    email_verification_token text,
    email_verification_sent_at timestamp with time zone,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    is_anonymous boolean DEFAULT false NOT NULL,
    tokens_valid_after timestamp with time zone
);

ALTER TABLE ONLY rebase.api_keys
    ADD CONSTRAINT api_keys_key_hash_key UNIQUE (key_hash);

ALTER TABLE ONLY rebase.api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rebase.app_config
    ADD CONSTRAINT app_config_pkey PRIMARY KEY (key);

ALTER TABLE ONLY rebase.branches
    ADD CONSTRAINT branches_db_name_key UNIQUE (db_name);

ALTER TABLE ONLY rebase.branches
    ADD CONSTRAINT branches_pkey PRIMARY KEY (name);

ALTER TABLE ONLY rebase.entity_history
    ADD CONSTRAINT entity_history_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rebase.magic_link_tokens
    ADD CONSTRAINT magic_link_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rebase.magic_link_tokens
    ADD CONSTRAINT magic_link_tokens_token_hash_key UNIQUE (token_hash);

ALTER TABLE ONLY rebase.metric_samples
    ADD CONSTRAINT metric_samples_pkey PRIMARY KEY (series, instance, at);

ALTER TABLE ONLY rebase.mfa_challenges
    ADD CONSTRAINT mfa_challenges_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rebase.mfa_factors
    ADD CONSTRAINT mfa_factors_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rebase.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rebase.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_token_hash_key UNIQUE (token_hash);

ALTER TABLE ONLY rebase.recovery_codes
    ADD CONSTRAINT recovery_codes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rebase.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rebase.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash);

ALTER TABLE ONLY rebase.schema_meta
    ADD CONSTRAINT schema_meta_pkey PRIMARY KEY (key);

ALTER TABLE ONLY rebase.user_identities
    ADD CONSTRAINT user_identities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rebase.user_identities
    ADD CONSTRAINT user_identities_provider_provider_id_key UNIQUE (provider, provider_id);

ALTER TABLE rebase.users
    ADD CONSTRAINT users_email_length_check CHECK ((length(email) <= 320)) NOT VALID;

ALTER TABLE ONLY rebase.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

CREATE INDEX idx_api_keys_hash ON rebase.api_keys USING btree (key_hash);

CREATE INDEX idx_api_keys_prefix ON rebase.api_keys USING btree (key_prefix);

CREATE INDEX idx_history_entity ON rebase.entity_history USING btree (table_name, entity_id);

CREATE INDEX idx_history_time ON rebase.entity_history USING btree (table_name, entity_id, updated_at DESC);

CREATE INDEX idx_magic_link_tokens_hash ON rebase.magic_link_tokens USING btree (token_hash);

CREATE INDEX idx_magic_link_tokens_user ON rebase.magic_link_tokens USING btree (uid);

CREATE INDEX idx_mfa_challenges_factor ON rebase.mfa_challenges USING btree (factor_id);

CREATE INDEX idx_mfa_factors_user ON rebase.mfa_factors USING btree (uid);

CREATE INDEX idx_password_reset_tokens_hash ON rebase.password_reset_tokens USING btree (token_hash);

CREATE INDEX idx_password_reset_tokens_user ON rebase.password_reset_tokens USING btree (uid);

CREATE INDEX idx_recovery_codes_user ON rebase.recovery_codes USING btree (uid);

CREATE INDEX idx_refresh_tokens_hash ON rebase.refresh_tokens USING btree (token_hash);

CREATE INDEX idx_refresh_tokens_session ON rebase.refresh_tokens USING btree (session_id);

CREATE INDEX idx_refresh_tokens_user ON rebase.refresh_tokens USING btree (uid);

CREATE INDEX idx_user_identities_user ON rebase.user_identities USING btree (uid);

CREATE INDEX metric_samples_series_recent ON rebase.metric_samples USING btree (series, at DESC);

CREATE UNIQUE INDEX users_email_lower_key ON rebase.users USING btree (lower(email));

CREATE INDEX users_email_verification_token_idx ON rebase.users USING btree (email_verification_token) WHERE (email_verification_token IS NOT NULL);

CREATE TRIGGER rebase_cdc_trigger AFTER INSERT OR DELETE OR UPDATE ON rebase.users FOR EACH ROW EXECUTE FUNCTION rebase.rebase_cdc_notify();

ALTER TABLE ONLY rebase.magic_link_tokens
    ADD CONSTRAINT magic_link_tokens_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY rebase.mfa_challenges
    ADD CONSTRAINT mfa_challenges_factor_id_fkey FOREIGN KEY (factor_id) REFERENCES rebase.mfa_factors(id) ON DELETE CASCADE;

ALTER TABLE ONLY rebase.mfa_factors
    ADD CONSTRAINT mfa_factors_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY rebase.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY rebase.recovery_codes
    ADD CONSTRAINT recovery_codes_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY rebase.refresh_tokens
    ADD CONSTRAINT refresh_tokens_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY rebase.user_identities
    ADD CONSTRAINT user_identities_uid_fkey FOREIGN KEY (uid) REFERENCES rebase.users(id) ON DELETE CASCADE;

ALTER TABLE rebase.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY users_default_admin_read ON rebase.users FOR SELECT USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY users_default_admin_write_delete ON rebase.users FOR DELETE USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY users_default_admin_write_insert ON rebase.users FOR INSERT WITH CHECK (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY users_default_admin_write_update ON rebase.users FOR UPDATE USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY users_default_self_read ON rebase.users FOR SELECT USING (((id)::text = rebase.uid()));

CREATE POLICY users_delete_3561e70_2 ON rebase.users FOR DELETE USING ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]));

CREATE POLICY users_insert_3561e70_0 ON rebase.users FOR INSERT WITH CHECK ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]));

CREATE POLICY users_require_admin_write_delete ON rebase.users AS RESTRICTIVE FOR DELETE USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY users_require_admin_write_insert ON rebase.users AS RESTRICTIVE FOR INSERT WITH CHECK (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY users_require_admin_write_update ON rebase.users AS RESTRICTIVE FOR UPDATE USING (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]))) WITH CHECK (((rebase.uid() IS NULL) OR (string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])));

CREATE POLICY users_select_5f32f06 ON rebase.users FOR SELECT USING ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]));

CREATE POLICY users_update_3561e70_1 ON rebase.users FOR UPDATE USING ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text])) WITH CHECK ((string_to_array(rebase.roles(), ','::text) && ARRAY['admin'::text]));

-- ── Seed ─────────────────────────────────────────────────────────────────────
-- Synthetic, and required: see schema-snapshots/README.md. One user and two live
-- sessions on one device tuple, which is the shape every rotation migration has
-- to preserve.

INSERT INTO rebase.users (id, email, display_name, roles, email_verified)
VALUES ('fc338d58-76a8-4697-a851-d6abe82a8e2c', 'recorded@recorded-v0-17-3-auth2-sql.test', 'Recorded User', ARRAY['admin'], TRUE);

-- session_started_at is set explicitly, and to the same instant as created_at,
-- because the column already exists in every era this script can record from —
-- it is added by the very migration that the older snapshots exist to test.
-- Leaving it to its DEFAULT now() would seed a row whose session apparently
-- began two days after its token was created, and upgrade-e2e.test.ts would
-- read that as the migration having back-filled from NOW(). Setting it turns
-- that assertion into the one worth making about a modern era: an existing
-- session start survives the upgrade untouched.
INSERT INTO rebase.refresh_tokens (uid, token_hash, expires_at, user_agent, ip_address, created_at, session_started_at)
VALUES
    ('fc338d58-76a8-4697-a851-d6abe82a8e2c', 'recorded-v0-17-3-auth2-sql-token-a', NOW() + INTERVAL '30 days',
     'Mozilla/5.0 (recorded)', '203.0.113.20', NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days'),
    ('fc338d58-76a8-4697-a851-d6abe82a8e2c', 'recorded-v0-17-3-auth2-sql-token-b', NOW() + INTERVAL '30 days',
     'Mozilla/5.0 (recorded)', '203.0.113.21', NOW() - INTERVAL '6 hours', NOW() - INTERVAL '6 hours');
