import { CollectionConfig, PostgresCollectionConfig, Property, Properties, MapProperty, ArrayProperty, Relation, RelationProperty, StringProperty, NumberProperty, ResolvedRelation } from "@rebasepro/types";
import { resolveCollectionRelations } from "@rebasepro/common";
import { toPascalCase, toSafeIdentifier } from "./utils";

function propertyToTypeScriptType(prop: Property): string {
    switch (prop.type) {
        case "string": {
            const sp = prop as StringProperty;
            if (sp.enum) {
                const ids = Array.isArray(sp.enum)
                    ? sp.enum.map((e: string | number | { id: string | number }) => typeof e === "object" ? String(e.id) : String(e))
                    : Object.keys(sp.enum);
                return ids.map(v => `"${v}"`).join(" | ");
            }
            return "string";
        }
        case "number": {
            const np = prop as NumberProperty;
            if (np.enum) {
                const ids = Array.isArray(np.enum)
                    ? np.enum.map((e: string | number | { id: string | number }) => typeof e === "object" ? String(e.id) : String(e))
                    : Object.keys(np.enum);
                return ids.join(" | ");
            }
            return "number";
        }
        case "boolean":
            return "boolean";
        case "date":
            return "string"; // ISO 8601 string over the wire
        case "geopoint":
            return "{ latitude: number; longitude: number; }";
        case "reference":
            return "string | number";
        case "relation":
            return "string | number";
        case "map": {
            const mapProp = prop as MapProperty;
            if (mapProp.properties) {
                const inner = Object.entries(mapProp.properties)
                    .map(([k, v]) => `${toSafeIdentifier(k)}: ${propertyToTypeScriptType(v as Property)};`)
                    .join(" ");
                return `{ ${inner} }`;
            }
            return "Record<string, unknown>";
        }
        case "array": {
            const arrProp = prop as ArrayProperty;
            if (arrProp.of) {
                return `Array<${propertyToTypeScriptType(arrProp.of as Property)}>`;
            }
            return "Array<unknown>";
        }
        case "vector":
            return "number[]";
        case "binary":
            return "string";
        default:
            return "unknown";
    }
}

/**
 * Unwrap a relation target that arrived as a module namespace rather than the
 * collection itself — `target: () => import("./authors")` is a common slip.
 */
function resolveTargetCollection(relation: ResolvedRelation): CollectionConfig | undefined {
    try {
        let target = relation.target() as CollectionConfig & { default?: CollectionConfig; __esModule?: boolean };
        if (target && (target.default || target.__esModule)) {
            target = (target.default ?? target) as typeof target;
        }
        return target;
    } catch {
        return undefined;
    }
}

/** The TypeScript type of a foreign key: whatever the target's primary key is. */
function foreignKeyType(relation: ResolvedRelation): string {
    const target = resolveTargetCollection(relation);
    if (!target?.properties) return "string | number";
    const idProp = Object.entries(target.properties).find(([_, p]) => (p as Record<string, unknown>).isId);
    if (!idProp) return "string | number";
    return (idProp[1] as Property).type === "number" ? "number" : "string";
}

/**
 * The type an *included* relation arrives as: the target's own row, inlined.
 *
 * This is what the read pipeline actually serves — `toRestRow` puts the
 * target's flat columns where the relation was, and the SDK and the HTTP API
 * both go through it. It is deliberately *not* a `{ __type: "relation" }`
 * envelope: that shape is the admin's view-model and never reaches a
 * developer's `find()`.
 *
 * Falls back to an open record when the target is not part of this generation
 * run, since there is no `Row` to point at.
 */
function includedRelationType(relation: ResolvedRelation, knownSlugs: Set<string>): string {
    const target = resolveTargetCollection(relation);
    const slug = target?.slug ?? relation.targetSlug;
    const rowType = slug && knownSlugs.has(slug)
        ? `Database[${JSON.stringify(toSafeIdentifier(slug))}]["Row"]`
        : "Record<string, unknown>";
    return relation.cardinality === "many" ? `Array<${rowType}>` : rowType;
}

export function generateTypedefs(collections: CollectionConfig[]): string {
    const knownSlugs = new Set(collections.map(c => c.slug).filter(Boolean) as string[]);
    const lines: string[] = [
        "/**",
        " * This file was auto-generated by Rebase.",
        " * Do not make direct changes to the file.",
        " */",
        "",
        "export interface Database {"
    ];

    for (const collection of collections) {
        const typeName = toPascalCase(collection.slug);
        const properties = (collection.properties ?? {}) as Properties;

        // Resolve relations
        let resolvedRelations: Record<string, ResolvedRelation> = {};
        try {
            resolvedRelations = resolveCollectionRelations(collection);
        } catch (e) {
            // Swallowed before, which made this the quietest way to ship a
            // wrong type. The foreign-key columns are emitted from the resolved
            // relations rather than from the properties, so losing them drops
            // both the relation fields *and* columns that exist in the
            // database — and the resulting error surfaces in the user's code,
            // typechecking against a `Database` that is missing `author_id`,
            // with nothing pointing back at generation.
            //
            // A target thunk usually throws because of a circular import; the
            // boot-time relation validator names the same cause.
            console.warn(
                `[rebase] Could not resolve the relations of "${collection.slug}", so its generated ` +
                "type has no relation fields and none of their foreign-key columns. This is usually a " +
                "circular import in the collection files — make sure the target is `() => otherCollection` " +
                `and not evaluated at module load.\n  ${e instanceof Error ? e.message : String(e)}`
            );
        }

        lines.push(`  ${toSafeIdentifier(collection.slug)}: {`);

        // ── Row Type ──
        lines.push("    Row: {");
        const emittedKeys = new Set<string>();

        // 1. Direct properties
        for (const [key, rawProp] of Object.entries(properties)) {
            const prop = rawProp as Property;
            if (prop.type === "relation") continue;

            const tsType = propertyToTypeScriptType(prop);
            const isRequired = prop.validation?.required;
            lines.push(`      ${toSafeIdentifier(key)}${isRequired ? "" : "?"}: ${tsType};`);
            emittedKeys.add(key);
        }

        // 2. FK columns from relations
        for (const [relKey, relation] of Object.entries(resolvedRelations)) {
            if (relation.kind === "belongsTo" && relation.localKey) {
                const fkKey = relation.localKey;
                if (emittedKeys.has(fkKey)) continue;

                const fkType = foreignKeyType(relation);

                // A relation addressed by the same name as its own foreign key
                // is served *over* that column when the read includes it: the
                // query nests the target under the relation name, and the
                // scalar it shadows is gone. Both outcomes are real, so the
                // column is typed as both — which is what stops a plain
                // `const id: string = row.author_id` from compiling.
                const shadowedByInclude = relKey === fkKey;
                const tsType = shadowedByInclude
                    ? `${fkType} | ${includedRelationType(relation, knownSlugs)}`
                    : fkType;

                const isRequired = relation.validation?.required && !shadowedByInclude;
                lines.push(`      ${toSafeIdentifier(fkKey)}${isRequired ? "" : "?"}: ${tsType};`);
                emittedKeys.add(fkKey);
            }
        }

        // 3. Relation fields — the target's own row, inlined.
        //
        // Optional throughout: a relation is only loaded when the read names it
        // in `include`, so it is absent from every other read.
        for (const [key, relation] of Object.entries(resolvedRelations)) {
            if (emittedKeys.has(key)) continue;
            lines.push(`      ${toSafeIdentifier(key)}?: ${includedRelationType(relation, knownSlugs)};`);
            emittedKeys.add(key);
        }

        // A `relation` property whose relation could not be resolved — an
        // engine without relation support, or a target that did not load. It is
        // still a column on the row, so it is still typed, just not precisely.
        for (const [key, rawProp] of Object.entries(properties)) {
            if ((rawProp as Property).type !== "relation") continue;
            if (emittedKeys.has(key)) continue;
            lines.push(`      ${toSafeIdentifier(key)}?: Record<string, unknown>;`);
            emittedKeys.add(key);
        }
        lines.push("    };");

        // ── Insert Type ──
        lines.push("    Insert: {");
        emittedKeys.clear();

        for (const [key, rawProp] of Object.entries(properties)) {
            const prop = rawProp as Property;
            if (prop.type === "relation") continue;
            const tsType = propertyToTypeScriptType(prop);
            const isRequired = prop.validation?.required;
            const typedProp = prop as StringProperty | NumberProperty;
            const isAutoId = "isId" in prop && typedProp.isId && typedProp.isId !== "manual" && typedProp.isId !== true;
            const isOptional = !isRequired || isAutoId;
            lines.push(`      ${toSafeIdentifier(key)}${isOptional ? "?" : ""}: ${tsType};`);
            emittedKeys.add(key);
        }

        for (const [relKey, relation] of Object.entries(resolvedRelations)) {
            if (relation.kind === "belongsTo" && relation.localKey) {
                const fkKey = relation.localKey;
                if (emittedKeys.has(fkKey)) continue;
                const fkType = "string | number";
                // simple fallback
                const isRequired = relation.validation?.required;
                lines.push(`      ${toSafeIdentifier(fkKey)}${isRequired ? "" : "?"}: ${fkType};`);
                emittedKeys.add(fkKey);
            }
        }
        lines.push("    };");

        // ── Update Type ──
        lines.push("    Update: {");
        emittedKeys.clear();
        for (const [key, rawProp] of Object.entries(properties)) {
            const prop = rawProp as Property;
            if (prop.type === "relation") continue;
            const tsType = propertyToTypeScriptType(prop);
            lines.push(`      ${toSafeIdentifier(key)}?: ${tsType};`);
            emittedKeys.add(key);
        }
        for (const [relKey, relation] of Object.entries(resolvedRelations)) {
            if (relation.kind === "belongsTo" && relation.localKey) {
                const fkKey = relation.localKey;
                if (emittedKeys.has(fkKey)) continue;
                lines.push(`      ${toSafeIdentifier(fkKey)}?: string | number;`);
                emittedKeys.add(fkKey);
            }
        }
        lines.push("    };");

        lines.push("  };");
    }

    lines.push("}");
    lines.push("");
    lines.push("export type CollectionName = keyof Database;");
    lines.push("export type CollectionsDictionary = { [K in CollectionName]: K };");
    lines.push("");
    lines.push("export const collectionsDictionary = {");
    for (const collection of collections) {
        lines.push(`  ${toSafeIdentifier(collection.slug)}: "${collection.slug}",`);
    }
    lines.push("} as const;");
    lines.push("");

    return lines.join("\n");
}
