/**
 * @rebasepro/codegen
 *
 * Generates a purely typed Typescript database definition.
 */

import { CollectionConfig } from "@rebasepro/types";
import { generateTypedefs } from "./generate-types";

export { generateTypedefs } from "./generate-types";
export { toPascalCase, toCamelCase, toSafeIdentifier, indent } from "./utils";

// ─── Public API ────────────────────────────────────────────────────

export interface GeneratedFile {
    /** Relative file path within the output directory */
    path: string;
    /** File content */
    content: string;
}

export interface GenerateSDKOptions {
    /** Whether to include a README file (default: true) */
    includeReadme?: boolean;
}

export function generateSDK(
    collections: CollectionConfig[],
    options: GenerateSDKOptions = {}
): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    files.push({
        path: "database.types.ts",
        content: generateTypedefs(collections)
    });

    if (options.includeReadme !== false) {
        files.push({
            path: "README.md",
            content: `# Rebase SDK

> Auto-generated by \`rebase generate-sdk\`. Do not edit manually.

## Usage

1. Install the client package:
   \`\`\`bash
   npm install @rebasepro/client
   \`\`\`

2. Initialize with your generated types:
   \`\`\`typescript
    import { createRebaseClient } from '@rebasepro/client';
    import { Database, collectionsDictionary } from './database.types';

    const rebase = createRebaseClient<Database>({
        baseUrl: 'http://localhost:3001',
        collections: collectionsDictionary,
    });

   // Both syntax styles are fully typed!
   const { data: users } = await rebase.data.users.find();
   console.log(users[0].email); // flat access — no .values wrapper

   const { data: posts } = await rebase.data.collection('posts').find();
   console.log(posts[0].title); // just post.title, not post.values.title
   \`\`\`
`
        });
    }

    return files;
}
