/**
 * A row of a two-column key, addressed through every read and write a caller
 * reaches — against a real Postgres, built the way boot builds it.
 *
 * `company_translation (id integer, locale varchar, PRIMARY KEY (id, locale))`
 * holds `1:::de_DE` and `1:::en_US`, which share their first key column. Writes
 * matched on the whole key; reads matched on `id` alone, so `GET 1:::en_US`
 * answered with the de_DE row, and so did the response to `PATCH 1:::en_US`
 * and to the `POST` that created `1:::it_IT` — the read-back of a write is the
 * same single-row read. Every case below names the row that shares the first
 * column, because a table with one row per `id` would pass all of them either
 * way.
 *
 * PGlite, a real Postgres compiled to WASM, rather than a mocked `db`: the
 * claims are about which row a statement returns.
 */
import { afterAll, beforeAll, describe, expect, it } from "@jest/globals";
import { PGlite } from "@electric-sql/pglite";
import { drizzle } from "drizzle-orm/pglite";
import type { CollectionConfig, OrderByTuple } from "@rebasepro/types";
import { cursorToStartAfter, decodeCursor } from "@rebasepro/common";

import { readCatalogueSchema } from "../src/schema/catalogue-schema";
import type { Queryable } from "../src/schema/introspect-runtime";
import { buildCollectionRegistry } from "../src/collections/buildRegistry";
import { DataService } from "../src/services/dataService";
import { RelationService } from "../src/services/RelationService";
import { DrizzleClient } from "../src/interfaces";

const companies = {
    slug: "companies",
    table: "companies",
    name: "Companies",
    properties: {
        id: { name: "ID", type: "number", isId: "increment" },
        name: { name: "Name", type: "string" }
    }
} as unknown as CollectionConfig;

/**
 * Notes on one translation, reached from it by a `via` whose step joins on both
 * key columns — the link the boot check recommends into a composite key.
 */
const notes = {
    slug: "translation_notes",
    table: "translation_notes",
    name: "Translation notes",
    properties: {
        id: { name: "ID", type: "number", isId: "increment" },
        // Declared under their column names, which is what a join step names.
        translation_id: { name: "Translation", type: "number" },
        translation_locale: { name: "Translation locale", type: "string" },
        body: { name: "Body", type: "string" }
    }
} as unknown as CollectionConfig;

const translations = {
    slug: "company_translation",
    table: "company_translation",
    name: "Company translations",
    properties: {
        // A number and a string: the address `1:::en_US` is parsed back into an
        // integer and a varchar, not two strings.
        id: { name: "ID", type: "number", isId: true },
        locale: { name: "Locale", type: "string", isId: true },
        name: { name: "Name", type: "string" },
        company: {
            name: "Company",
            type: "relation",
            relation: { kind: "belongsTo", target: () => companies, relationName: "company", localKey: "id" }
        },
        notes: {
            name: "Notes",
            type: "relation",
            relation: {
                kind: "via",
                target: () => notes,
                relationName: "notes",
                cardinality: "many",
                joinPath: [{
                    table: "translation_notes",
                    on: { from: ["id", "locale"], to: ["translation_id", "translation_locale"] }
                }]
            }
        }
    }
} as unknown as CollectionConfig;

const DDL = `
CREATE TABLE companies (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text
);

CREATE TABLE company_translation (
    id integer NOT NULL REFERENCES companies(id),
    locale varchar(10) NOT NULL,
    name text,
    PRIMARY KEY (id, locale)
);

CREATE TABLE translation_notes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    translation_id integer NOT NULL,
    translation_locale varchar(10) NOT NULL,
    body text,
    FOREIGN KEY (translation_id, translation_locale) REFERENCES company_translation (id, locale)
);

INSERT INTO companies (id, name) VALUES (1, 'Acme'), (2, 'Globex');
INSERT INTO company_translation (id, locale, name) VALUES
    (1, 'de_DE', 'Acme GmbH'),
    (1, 'en_US', 'Acme Inc.'),
    (2, 'de_DE', 'Globex GmbH');
INSERT INTO translation_notes (translation_id, translation_locale, body) VALUES
    (1, 'de_DE', 'Umlaute prüfen'),
    (1, 'en_US', 'Check the legal suffix'),
    (1, 'en_US', 'Oxford comma');
`;

const PATH = "company_translation";

describe("a composite primary key, read and written by its whole address", () => {
    let pg: PGlite;
    let data: DataService;
    let db: DrizzleClient;
    let registry: ReturnType<typeof buildCollectionRegistry>;

    /** The key of every row, straight from the table, in key order. */
    const storedKeys = async (): Promise<string[]> => {
        const { rows } = await pg.query<{ id: number; locale: string; name: string }>(
            "SELECT id, locale, name FROM company_translation ORDER BY id, locale"
        );
        return rows.map(row => `${row.id}:::${row.locale}=${row.name}`);
    };

    beforeAll(async () => {
        pg = await PGlite.create();
        await pg.exec(DDL);
        // What boot does: tables from `information_schema`, keyed by wire name,
        // handed to drizzle as its schema so `db.query` exists.
        const catalogue = await readCatalogueSchema({
            client: pg as unknown as Queryable,
            collections: [companies, translations, notes],
            defaultSchema: "public"
        });
        db = drizzle(pg, { schema: { ...catalogue.tables, ...catalogue.relations } }) as unknown as DrizzleClient;
        registry = buildCollectionRegistry({
            collections: [companies, translations, notes],
            tables: catalogue.tables,
            relations: catalogue.relations
        });
        data = new DataService(db, registry);
    }, 60_000);

    afterAll(async () => {
        await pg?.close();
    });

    it("GET by id answers with the row the address names, not the first to share its `id`", async () => {
        const row = await data.fetchOneForRest(PATH, "1:::en_US");
        expect(row).toMatchObject({ id: 1, locale: "en_US", name: "Acme Inc." });

        expect(await data.fetchOneForRest(PATH, "1:::de_DE")).toMatchObject({ locale: "de_DE", name: "Acme GmbH" });
        expect(await data.fetchOneForRest(PATH, "1:::fr_FR")).toBeNull();
    });

    it("the admin's single-row read agrees", async () => {
        const row = await data.fetchOne(PATH, "1:::en_US");
        expect(row).toMatchObject({ id: 1, locale: "en_US", name: "Acme Inc." });
        expect(await data.fetchOne(PATH, "1:::fr_FR")).toBeUndefined();
    });

    it("an update answers with the row it updated", async () => {
        const saved = await data.save(PATH, { name: "Acme Incorporated" }, "1:::en_US");

        expect(saved).toMatchObject({ id: 1, locale: "en_US", name: "Acme Incorporated" });
        expect(await storedKeys()).toEqual([
            "1:::de_DE=Acme GmbH",
            "1:::en_US=Acme Incorporated",
            "2:::de_DE=Globex GmbH"
        ]);
    });

    it("an insert answers with the row it inserted", async () => {
        const saved = await data.save(PATH, { id: 1, locale: "it_IT", name: "Acme S.p.A." });

        expect(saved).toMatchObject({ id: 1, locale: "it_IT", name: "Acme S.p.A." });
        expect(await data.fetchOneForRest(PATH, "1:::it_IT")).toMatchObject({ name: "Acme S.p.A." });
    });

    it("a uniqueness check excludes the row being edited, and only that row", async () => {
        // `Acme GmbH` is held by 1:::de_DE. Editing 1:::en_US to it is a
        // duplicate; excluding the edited row by `id` alone excluded de_DE too.
        expect(await data.checkUniqueField(PATH, "name", "Acme GmbH", "1:::en_US")).toBe(false);
        expect(await data.checkUniqueField(PATH, "name", "Acme GmbH", "1:::de_DE")).toBe(true);
    });

    describe("paging with a cursor", () => {
        /** Every row, one page of one at a time, following `cursorFor`. */
        const walk = async (orderBy?: OrderByTuple[]): Promise<string[]> => {
            const seen: string[] = [];
            let startAfter: Record<string, unknown> | undefined;
            for (let page = 0; page < 10; page++) {
                const rows = await data.fetchCollectionForRest(PATH, { limit: 1, orderBy, startAfter });
                if (rows.length === 0) break;
                const row = rows[0];
                seen.push(`${row.id}:::${row.locale}`);
                const cursor = data.cursorFor(PATH, row, orderBy);
                if (!cursor) throw new Error("no cursor issued for a row with a full key");
                startAfter = cursorToStartAfter(decodeCursor(cursor));
            }
            return seen;
        };

        it("visits every row once when the rows share their first key column", async () => {
            // Ordered by the key, descending. A cursor on `id` alone skipped
            // straight past the other rows of company 1.
            expect(await walk()).toEqual(["2:::de_DE", "1:::it_IT", "1:::en_US", "1:::de_DE"]);
        });

        it("breaks ties on a sort key by the whole key", async () => {
            // Three rows tie on `id = 1`; only the full key orders them.
            expect(await walk([["id", "asc"]])).toEqual(["1:::it_IT", "1:::en_US", "1:::de_DE", "2:::de_DE"]);
        });
    });

    it("a nested path under one row reads that row's link, not its neighbours'", async () => {
        // `company_translation/1:::en_US/company` finds the parent row to read
        // its `id` from; by `id = 1` alone that subquery found three rows.
        const rows = await data.fetchCollectionForRest(`${PATH}/1:::en_US/company`, {});
        expect(rows).toEqual([expect.objectContaining({ id: 1, name: "Acme" })]);
    });

    describe("a `via` out of one row, joined on both key columns", () => {
        // Each step used to be joined on its first column pair and the parent
        // matched on `id`, so 1:::en_US reached the de_DE note too.
        const bodies = (rows: Record<string, unknown>[]) => rows.map(row => row.body).sort();

        it("loads the notes of that row only", async () => {
            expect(bodies(await data.fetchRelatedEntities(PATH, "1:::en_US", "notes")))
                .toEqual(["Check the legal suffix", "Oxford comma"]);
            expect(bodies(await data.fetchRelatedEntities(PATH, "1:::de_DE", "notes")))
                .toEqual(["Umlaute prüfen"]);
        });

        it("lists them under the row's nested path", async () => {
            expect(bodies(await data.fetchCollectionForRest(`${PATH}/1:::en_US/notes`, {})))
                .toEqual(["Check the legal suffix", "Oxford comma"]);
        });

        it("counts them, and a write gated on the count reaches no other row's note", async () => {
            const relations = new RelationService(db, registry);
            expect(await relations.countRelatedEntities(PATH, "1:::en_US", "notes")).toBe(2);
            expect(await relations.countRelatedEntities(PATH, "1:::de_DE", "notes")).toBe(1);

            const { rows } = await pg.query<{ id: number }>("SELECT id FROM translation_notes WHERE translation_locale = 'de_DE'");
            await expect(data.save(`${PATH}/1:::en_US/notes`, { body: "hijacked" }, rows[0].id))
                .rejects.toThrow();
            expect((await pg.query("SELECT body FROM translation_notes WHERE id = $1", [rows[0].id])).rows)
                .toEqual([{ body: "Umlaute prüfen" }]);
        });
    });

    it("a delete removes the row the address names, and no other", async () => {
        await data.delete(PATH, "1:::it_IT");

        expect(await data.fetchOneForRest(PATH, "1:::it_IT")).toBeNull();
        expect(await storedKeys()).toEqual([
            "1:::de_DE=Acme GmbH",
            "1:::en_US=Acme Incorporated",
            "2:::de_DE=Globex GmbH"
        ]);
    });
});
