/**
 * Where `db push` and `db generate` write the SQL they render, and what happens
 * to the copies an older release committed to `drizzle/`.
 *
 * The removal is the part worth pinning. It deletes files in somebody's
 * repository, so it has to take exactly the ones the generator wrote and
 * nothing else — not a migration, and not a hand-written file that happens to
 * share a name.
 */
import fs from "fs";
import os from "os";
import path from "path";

import {
    DESIRED_STATE_URL,
    GENERATED_SQL_DIR,
    GENERATED_SQL_FILES,
    prepareGeneratedSqlDir
} from "../src/generated-sql";

const DDL_HEADER = "-- This file is auto-generated by the Rebase DDL generator. Do not edit manually.\n";
const POLICIES_HEADER = "-- This file contains RLS policies generated by Rebase. Applied separately from migrations.\n";

let cwd: string;

beforeEach(() => {
    cwd = fs.mkdtempSync(path.join(os.tmpdir(), "generated-sql-"));
});

afterEach(() => {
    fs.rmSync(cwd, {
        recursive: true,
        force: true
    });
});

const write = (relative: string, contents: string) => {
    const file = path.join(cwd, relative);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, contents);
};
const exists = (relative: string) => fs.existsSync(path.join(cwd, relative));

describe("the generated SQL directory", () => {
    it("is what Atlas is pointed at, relative like the migrations directory", () => {
        expect(DESIRED_STATE_URL).toBe("file://.rebase/sql/schema.sql");
        expect(GENERATED_SQL_DIR.startsWith(".rebase/")).toBe(true);
    });

    it("is created ignoring itself, so an older project's .gitignore is not needed", () => {
        prepareGeneratedSqlDir(cwd);
        const ignore = fs.readFileSync(path.join(cwd, GENERATED_SQL_DIR, ".gitignore"), "utf-8");
        expect(ignore.split("\n")).toContain("*");
    });

    it("leaves an existing .gitignore there alone", () => {
        write(`${GENERATED_SQL_DIR}/.gitignore`, "schema.sql\n");
        prepareGeneratedSqlDir(cwd);
        expect(fs.readFileSync(path.join(cwd, GENERATED_SQL_DIR, ".gitignore"), "utf-8")).toBe("schema.sql\n");
    });
});

describe("retiring the copies in drizzle/", () => {
    it("removes every file the generator wrote there, and says which", () => {
        write("drizzle/schema.sql", `${DDL_HEADER}\nCREATE TABLE posts ();\n`);
        write("drizzle/policies.sql", `${POLICIES_HEADER}\nALTER TABLE posts ENABLE ROW LEVEL SECURITY;\n`);
        write("drizzle/search.sql", `${DDL_HEADER}--\n-- Full-text search\n`);
        write("drizzle/vector.sql", `${DDL_HEADER}--\n-- Vector columns\n`);
        write("drizzle/triggers.sql", `${DDL_HEADER}--\n-- updated_at triggers\n`);

        const removed = prepareGeneratedSqlDir(cwd);

        expect(removed.sort()).toEqual(GENERATED_SQL_FILES.map(name => `drizzle/${name}`).sort());
        for (const name of GENERATED_SQL_FILES) expect(exists(`drizzle/${name}`)).toBe(false);
    });

    it("never touches the migrations beside them", () => {
        write("drizzle/schema.sql", `${DDL_HEADER}CREATE TABLE posts ();\n`);
        write("drizzle/migrations/20260714000000_init.sql", `${DDL_HEADER}CREATE TABLE posts ();\n`);
        write("drizzle/migrations/atlas.sum", "h1:abc=\n");

        prepareGeneratedSqlDir(cwd);

        expect(exists("drizzle/migrations/20260714000000_init.sql")).toBe(true);
        expect(exists("drizzle/migrations/atlas.sum")).toBe(true);
    });

    it("keeps a file that shares a name but was not generated", () => {
        // Somebody's own `policies.sql`, applied by their own pipeline. Deleting
        // it because of its name would be the one unrecoverable mistake here.
        write("drizzle/policies.sql", "-- our extra grants\nGRANT SELECT ON posts TO reporting;\n");

        expect(prepareGeneratedSqlDir(cwd)).toEqual([]);
        expect(exists("drizzle/policies.sql")).toBe(true);
    });

    it("finds nothing to do the second time", () => {
        write("drizzle/schema.sql", `${DDL_HEADER}CREATE TABLE posts ();\n`);
        prepareGeneratedSqlDir(cwd);
        expect(prepareGeneratedSqlDir(cwd)).toEqual([]);
    });
});
