/**
 * The seam between the two suites that both passed while the upgrade was broken.
 *
 * `legacy-foreign-key-detection.test.ts` proves the ensure *plan* emits a RENAME
 * when a database carries `categorie_id` and the current rule wants
 * `category_id`. `validate-relations.test.ts` proves `assertRelationsResolve`
 * reports a junction column that does not exist. Both are correct. Neither
 * covers the state an upgrade actually produces, because each builds its own
 * input by hand and so never lets the two sources of truth disagree:
 *
 *   * the DATABASE, which boot-ensure has just renamed to `category_id`, and
 *   * the project's checked-in `backend/src/schema.generated.ts`, which was
 *     generated by the previous release and still declares `categorie_id`.
 *
 * `assertRelationsResolve` reads the second — `registry.getTable()` returns a
 * Drizzle table from the generated module, not a catalogue query. So on the
 * first boot after `pnpm install`, the rename succeeds and then the boot dies
 * on a column that does exist, with a message that says "is not a column on the
 * junction table" and advises setting `through.targetColumn` to `categorie_id`
 * — the name that was just migrated away. Following that advice writes a
 * relation pointing at a column that is gone.
 *
 * Restarting does not help: the rename is already applied, so every subsequent
 * boot fails the same way. The project is stuck until the developer guesses
 * `rebase schema generate`, which nothing tells them to run.
 *
 * What this file pins is the diagnosis. A stale generated schema is not the same
 * defect as a typo'd column name, and it does not have the same fix.
 */
import { pgTable, text } from "drizzle-orm/pg-core";
import { CollectionConfig } from "@rebasepro/types";
import { generateForeignKeyName, legacyForeignKeyName } from "@rebasepro/utils";

import { PostgresCollectionRegistry } from "../src/collections/PostgresCollectionRegistry";
import { findRelationDefects, assertRelationsResolve } from "../src/collections/validate-relations";

// ── The collections, as 0.13 reads them ──────────────────────────────────────

const categories: CollectionConfig = {
    slug: "categories",
    table: "categories",
    name: "Categories",
    properties: { id: { name: "ID", type: "string", isId: "uuid" }, name: { type: "string" } }
} as unknown as CollectionConfig;

/**
 * A many-to-many, because that is where the rename lands: a junction column's
 * default name comes from the endpoint collection's *slug*, and slugs are
 * plural. `belongsTo` derives from the relation name, which is normally already
 * singular.
 */
const products: CollectionConfig = {
    slug: "products",
    table: "products",
    name: "Products",
    properties: {
        id: { name: "ID", type: "string", isId: "uuid" },
        title: { type: "string" },
        categories: {
            type: "relation",
            relation: { kind: "manyToMany", target: () => categories, relationName: "categories" }
        }
    }
} as unknown as CollectionConfig;

const collections = [products, categories];

const CURRENT = generateForeignKeyName("categories");   // category_id
const LEGACY = legacyForeignKeyName("categories");      // categorie_id

/**
 * A registry whose junction table is the one the PREVIOUS release generated.
 *
 * This is the whole point of the fixture: the Drizzle module is the stale
 * artifact, and it is what the validator reads.
 */
function registryFromGeneratedSchema(junctionColumn: string): PostgresCollectionRegistry {
    const registry = new PostgresCollectionRegistry();
    registry.registerMultiple(collections);
    registry.registerTable(
        pgTable("products", { id: text("id").primaryKey(), title: text("title") }) as never,
        "products"
    );
    registry.registerTable(
        pgTable("categories", { id: text("id").primaryKey(), name: text("name") }) as never,
        "categories"
    );
    registry.registerTable(
        pgTable("categories_products", {
            product_id: text("product_id"),
            [junctionColumn]: text(junctionColumn)
        }) as never,
        "categories_products"
    );
    return registry;
}

describe("a generated schema left behind by the FK singularization rename", () => {
    it("is a different fixture from the current one — otherwise this file proves nothing", () => {
        // Guards the test, not the product: if `singular()` ever changes so that
        // `categories` no longer moves, every assertion below would pass against
        // an unbroken fixture and report a gate that ran on nothing.
        expect(LEGACY).toBe("categorie_id");
        expect(CURRENT).toBe("category_id");
        expect(LEGACY).not.toBe(CURRENT);
    });

    it("still resolves cleanly once the schema has been regenerated", () => {
        const registry = registryFromGeneratedSchema(CURRENT);
        expect(findRelationDefects(collections, registry)).toEqual([]);
        expect(() => assertRelationsResolve(collections, registry)).not.toThrow();
    });

    describe("while it is still stale", () => {
        const registry = () => registryFromGeneratedSchema(LEGACY);

        it("is reported as stale codegen, not as a bad column name", () => {
            const [defect] = findRelationDefects(collections, registry());

            expect(defect).toBeDefined();
            expect(defect.collection).toBe("products");
            expect(defect.relationName).toBe("categories");
            // The generated schema is the thing that is wrong, and the message
            // has to say so — the database has already been migrated.
            expect(defect.problem).toMatch(/generated/i);
            expect(defect.problem).toContain(LEGACY);
            expect(defect.problem).toContain(CURRENT);
        });

        it("names the command that fixes it", () => {
            const [defect] = findRelationDefects(collections, registry());
            expect(defect.fix).toContain("rebase schema generate");
        });

        it("never advises writing the migrated-away column into the collection", () => {
            const [defect] = findRelationDefects(collections, registry());

            // The old message said: set `through.targetColumn` to one of:
            // `product_id`, `categorie_id`. That column no longer exists in the
            // database, so taking the advice breaks the relation for good.
            expect(defect.fix).not.toMatch(/through\.targetColumn.*categorie_id/s);
            expect(defect.fix).not.toMatch(/set `through\.\w+` to one of/);
        });

        it("does not claim the database lacks a column the database has", () => {
            let message = "";
            try {
                assertRelationsResolve(collections, registry());
            } catch (e) {
                message = (e as Error).message;
            }

            expect(message).not.toBe("");
            // The boot still fails — that part was right, an unresolvable
            // relation must not serve empty results. What it must not do is
            // describe a database it never read.
            expect(message).not.toMatch(new RegExp(`\`through\\.targetColumn: "${CURRENT}"\` is not a column`));
            expect(message).toMatch(/rebase schema generate/);
        });
    });
});
