/**
 * Where `db push` and `db generate` put the SQL they render from the collections.
 *
 * Five files — `schema.sql` (Atlas's desired state), `policies.sql`,
 * `search.sql`, `vector.sql` and `triggers.sql` — and every one of them is
 * scratch. Both commands regenerate all five before reading any of them, and
 * nothing else reads them at all. They used to be written into `drizzle/`, beside
 * the migrations, and committed: a copy nobody read, which every collection
 * change rewrote in the diff and every two branches touching collections
 * conflicted on.
 *
 * Relative to the directory the command runs in (the backend), like the
 * migrations are.
 */
import fs from "fs";
import path from "path";

/** The directory, relative to the working directory. POSIX, because it is also a URL path. */
export const GENERATED_SQL_DIR = ".rebase/sql";

/**
 * `schema.sql` as Atlas takes it. Relative on purpose, like the
 * `file://drizzle/migrations` beside it: Atlas joins the URL's host and path, so
 * `.rebase` is read as the first path segment, measured against the pinned 1.2.3.
 */
export const DESIRED_STATE_URL = `file://${GENERATED_SQL_DIR}/schema.sql`;

/** The files the DDL generator writes, all of them derived from the collections. */
export const GENERATED_SQL_FILES = ["schema.sql", "policies.sql", "search.sql", "vector.sql", "triggers.sql"] as const;

/** The absolute directory, for the working directory the command runs in. */
export function generatedSqlDir(cwd: string = process.cwd()): string {
    return path.resolve(cwd, GENERATED_SQL_DIR);
}

/**
 * The first line of every file the generator writes, in every release that
 * wrote them into `drizzle/`. Matching it is what makes removing the old copy
 * safe: a file there under one of these names that does not open this way was
 * written by a person, and is left alone.
 */
const GENERATED_HEADER = /^-- This file (is auto-generated by the Rebase DDL generator|contains RLS policies generated by Rebase)\./;

/**
 * Get the directory ready to be written, and retire the copies an older release
 * committed.
 *
 * The directory ignores itself, rather than relying on the project's
 * `.gitignore`: a scaffold ignores `.rebase/`, but a project created before it
 * did would otherwise start committing these files from their new home.
 *
 * The old copies in `drizzle/` are deleted, not left behind. Nothing writes them
 * any more, so from the first push after an upgrade they only fall further
 * behind — and a stale `policies.sql` in the repository is exactly what someone
 * reviewing the project's RLS would read.
 *
 * @returns the old files it removed, relative to the working directory.
 */
export function prepareGeneratedSqlDir(cwd: string = process.cwd()): string[] {
    const dir = generatedSqlDir(cwd);
    fs.mkdirSync(dir, { recursive: true });
    const ignore = path.join(dir, ".gitignore");
    if (!fs.existsSync(ignore)) {
        fs.writeFileSync(ignore, "# Generated by `rebase db push` / `rebase db generate` from the collections.\n*\n");
    }

    const removed: string[] = [];
    for (const name of GENERATED_SQL_FILES) {
        const legacy = path.join(cwd, "drizzle", name);
        if (!fs.existsSync(legacy)) continue;
        const firstLine = fs.readFileSync(legacy, "utf-8").split("\n", 1)[0];
        if (!GENERATED_HEADER.test(firstLine)) continue;
        fs.rmSync(legacy);
        removed.push(path.posix.join("drizzle", name));
    }
    return removed;
}
