/**
 * The bundle corpus: every shape of bundle we have ever shipped, booted on the
 * runtime as it is today.
 *
 * The managed tier moves projects onto new runtime images automatically, in
 * waves, without anyone rebuilding the project. That is the whole promise, and
 * the thing standing behind it has until now been a health gate watching request
 * rates and error rates — which can see a crash loop and cannot see a bundle
 * that quietly stopped loading its collections, a schema version that changed
 * identity under a deployed project, or an old manifest shape that now parses to
 * something subtly different. Those are exactly the regressions a fleet-wide
 * auto-upgrade turns into an outage for everyone at once.
 *
 * So: frozen bundles, checked into `fixtures/bundles/`, booted for real against
 * a real Postgres. They are hand-authored, not generated by `rebase build`, and
 * that is deliberate — a fixture the builder regenerates moves whenever the
 * builder moves, which is the one thing a regression corpus must not do. A
 * fixture here is a historical artifact. When one stops working, the finding is
 * that a bundle already deployed would stop working.
 *
 *     createdb rebase_corpus
 *     node --import tsx scripts/verify-bundle-corpus.mts
 *
 * Override the database with CORPUS_DATABASE_URL.
 *
 * Adding a bundle: copy the closest existing directory, change `table` in its
 * collections so it owns its own tables, and add an entry to CORPUS below. Record
 * one per release — the value is entirely in how far back the oldest one goes.
 *
 * Like `verify-selfhost.mts`, this imports runtime source BY PATH rather than by
 * package name: in a git worktree `@rebasepro/*` resolves through node_modules
 * into the primary checkout, so a package-name import would verify the wrong code.
 */
import fs from "fs";
import os from "os";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CORPUS_DIR = path.join(ROOT, "fixtures", "bundles");

const DATABASE_URL = process.env.CORPUS_DATABASE_URL
    ?? `postgres://${os.userInfo().username}@localhost:5432/rebase_corpus`;

interface CorpusEntry {
    /** Directory under fixtures/bundles. */
    dir: string;
    /** What this bundle is a specimen of — printed, so a failure names the era. */
    describe: string;
    kind: "backend" | "static";
    /** Marker text the bundle's index.html contains, when it serves one. */
    indexMarker?: string;
}

const CORPUS: CorpusEntry[] = [
    {
        dir: "v1-format1-cms",
        describe: "bundle format 1 — `mode: cms`, a bundled admin at entry.admin",
        kind: "backend",
        indexMarker: "CORPUS_V1_ADMIN_INDEX"
    },
    {
        dir: "v2-backend",
        describe: "bundle format 2 — `kind: backend`, entry.static as a list",
        kind: "backend",
        indexMarker: "CORPUS_V2_SITE_INDEX"
    },
    {
        dir: "v2-static",
        describe: "bundle format 2 — `kind: static`, no database at all",
        kind: "static",
        indexMarker: "CORPUS_STATIC_INDEX"
    }
];

let failures = 0;
function check(label: string, ok: boolean, detail = ""): void {
    console.log(`${ok ? "  \x1b[32m✓\x1b[0m" : "  \x1b[31m✗\x1b[0m"} ${label}${detail ? ` \x1b[2m— ${detail}\x1b[0m` : ""}`);
    if (!ok) failures++;
}

const { bootFromBundle } = await import(`${ROOT}/packages/server/src/boot/boot.ts`);
const { readBundleManifest } = await import(`${ROOT}/packages/server/src/boot/bundle.ts`);
const { loadCollectionsFromDirectory } = await import(`${ROOT}/packages/server/src/collections/loader.ts`);
const { computeSchemaVersion } = await import(`${ROOT}/packages/types/src/types/schema_version.ts`);

// One database, many bundles. Each fixture's collections own distinct tables, so
// they can share it without colliding — and sharing is closer to the truth than
// a pristine database per bundle would be, because a runtime upgrade always
// lands on a database some earlier runtime already wrote to.
process.env.DATABASE_URL = DATABASE_URL;
process.env.JWT_SECRET ??= "bundle-corpus-jwt-secret-at-least-32-chars";
process.env.REBASE_SERVICE_KEY ??= "bundle-corpus-service-key-at-least-32-chars";
process.env.NODE_ENV = "development";
process.env.REBASE_SERVE_STATIC = "true";
process.env.PORT = "0";
// The managed path, stated rather than inherited: the runtime image's entrypoint
// defaults to `ensure`, and boot-time provisioning is precisely what a fleet
// upgrade relies on — an old bundle landing on a new runtime has to arrive at
// its own tables and policies without anyone running a migration.
process.env.REBASE_MIGRATE_ON_BOOT = "ensure";

const asService = { authorization: `Bearer ${process.env.REBASE_SERVICE_KEY}` };

/**
 * A deployable copy of a fixture.
 *
 * A checked-in bundle has no `node_modules`; a deployed one does, because the
 * container npm-installs the bundle's dependencies into it on first start and
 * `rebase start` links already-installed ones in. Booting the fixture in place
 * would therefore be testing something no deployment ever looks like — and would
 * also mean writing symlinks into the corpus, which must stay pristine.
 *
 * So each fixture is copied to a scratch directory and given the modules a
 * deployment would have. `app/backend` is the borrowed tree: it is the reference
 * project, so it carries exactly the packages a real bundle's install produces.
 */
const DONOR_MODULES = [
    path.join(ROOT, "app", "backend", "node_modules"),
    path.join(ROOT, "app", "node_modules"),
    path.join(ROOT, "node_modules")
];

function stage(bundleDir: string, name: string): string {
    const staged = fs.mkdtempSync(path.join(os.tmpdir(), `rebase-corpus-${name}-`));
    fs.cpSync(bundleDir, staged, { recursive: true });

    const donor = DONOR_MODULES.find(d => fs.existsSync(path.join(d, "@rebasepro", "server-postgres")));
    if (!donor) {
        // Loudly, rather than booting without a driver and reporting the
        // resulting failure as if the BUNDLE were broken. A missing install is
        // an environment problem and has to read as one.
        throw new Error(
            "No node_modules containing @rebasepro/server-postgres was found to lend the staged bundle.\n" +
            `Looked in:\n${DONOR_MODULES.map(d => `  ${d}`).join("\n")}\n` +
            "Run an install first (and in a git worktree, symlink app/backend/node_modules from the primary checkout)."
        );
    }
    fs.symlinkSync(donor, path.join(staged, "node_modules"), "dir");
    return staged;
}

const staged: string[] = [];

for (const entry of CORPUS) {
    const fixtureDir = path.join(CORPUS_DIR, entry.dir);
    console.log(`\n\x1b[1m▸ ${entry.dir}\x1b[0m \x1b[2m${entry.describe}\x1b[0m`);

    if (!fs.existsSync(fixtureDir)) {
        check("fixture exists", false, fixtureDir);
        continue;
    }

    const bundleDir = stage(fixtureDir, entry.dir);
    staged.push(bundleDir);

    // Read the manifest before booting: a format the runtime refuses is a
    // different (and much louder) failure than one that boots and misbehaves,
    // and the corpus should tell them apart.
    let manifest: Record<string, unknown>;
    try {
        manifest = readBundleManifest(bundleDir) as Record<string, unknown>;
        check("manifest reads on this runtime", true);
    } catch (err) {
        check("manifest reads on this runtime", false, err instanceof Error ? err.message : String(err));
        continue;
    }

    // Format 1 said `mode`; format 2 says `kind`. An old bundle must arrive at
    // the same meaning, and this is the direction with no version gate behind it
    // — a renamed field simply reads as absent, and every gate keyed on it skips
    // in silence. Nothing else in the suite proves the normalisation ran.
    check(`normalises to kind: ${entry.kind}`, manifest.kind === entry.kind, String(manifest.kind));

    let booted: any;
    try {
        booted = await bootFromBundle({ bundleDir, listen: false, handleSignals: false });
        check("boots", true);
    } catch (err) {
        check("boots", false, err instanceof Error ? err.message : String(err));
        continue;
    }

    const get = async (url: string, headers: Record<string, string> = {}) => {
        const res = await booted.app.fetch(new Request(`http://localhost${url}`, { headers }));
        return { status: res.status, body: await res.text() };
    };

    try {
        // Liveness must never touch the database, on any bundle era — an
        // orchestrator killing healthy pods during a database blip is how one
        // slow query becomes a fleet outage.
        check("GET /livez", (await get("/livez")).status === 200);

        if (entry.kind === "backend") {
            check("GET /health", (await get("/health")).status === 200, "a real database round-trip");

            // The identity of a deployed project's schema must not drift under
            // it, and proving that takes an INDEPENDENT computation.
            //
            // `GET /api/meta/schema-version` cannot supply one: `schemaVersionOf`
            // returns the manifest's value verbatim whenever the bundle declares
            // it, and only computes from collections when it does not. Comparing
            // the endpoint to the manifest therefore compares the manifest to
            // itself and passes on a bundle whose declared version is nonsense —
            // which is exactly what it did here until a deliberately corrupted
            // fixture still went green.
            //
            // So the hash is recomputed from the bundle's own collections with
            // the same function the CLI used at build time. The manifest's value
            // is the CLI's answer, frozen; this is the runtime's answer, now. If
            // they part company, every deployed bundle's declared schemaVersion
            // is wrong and SDK drift detection has quietly stopped meaning
            // anything.
            const declared = String(manifest.schemaVersion ?? "");
            const collectionsDir = path.join(bundleDir, String((manifest.entry as any)?.collections));
            const loaded = await loadCollectionsFromDirectory(collectionsDir);
            const recomputed = computeSchemaVersion(loaded);
            check("collections load from the bundle", loaded.length > 0, `${loaded.length} collection(s)`);
            check("schema-version recomputes to the frozen value", recomputed === declared,
                `manifest ${declared || "(none)"} vs recomputed ${recomputed}`);

            // And the endpoint still serves the stamp, which is what an SDK polls.
            const reported = (await get("/api/meta/schema-version")).body;
            check("schema-version endpoint serves it", reported.includes(declared), reported.slice(0, 60));

            // The collections actually loaded, and their tables actually exist —
            // boot creates them additively. A bundle whose collections silently
            // failed to load looks perfectly healthy right up to the first query.
            const slug = entry.dir === "v1-format1-cms" ? "notes" : "notes";
            const authed = await get(`/api/data/${slug}?limit=1`, asService);
            check(`GET /api/data/${slug} as a service`, authed.status === 200,
                `${authed.status} ${authed.body.slice(0, 70)}`);

            // Writes go through the same policy path reads do; a read-only check
            // would miss an INSERT policy that boot failed to create.
            const created = await booted.app.fetch(new Request("http://localhost/api/data/" + slug, {
                method: "POST",
                headers: { ...asService, "content-type": "application/json" },
                body: JSON.stringify({ title: "corpus write", body: "written by verify-bundle-corpus" })
            }));
            check(`POST /api/data/${slug} as a service`, created.status === 200 || created.status === 201,
                String(created.status));

            // RLS is on and callers are authenticated: an anonymous read is 401
            // regardless of how permissive the row policy is. If this ever
            // returns 200, a runtime upgrade has opened every deployed bundle.
            check(`GET /api/data/${slug} unauthenticated is refused`,
                (await get(`/api/data/${slug}?limit=1`)).status === 401);
        }

        if (entry.indexMarker) {
            const index = await get("/");
            check("serves its index.html", index.body.includes(entry.indexMarker), `${index.status}`);
            // A deep path falls back to the SPA index rather than 404ing, which
            // is what makes client-side routing work at all.
            check("SPA fallback on a deep path",
                (await get("/some/client/route")).body.includes(entry.indexMarker));
        }
    } finally {
        await booted.shutdown?.().catch(() => {});
    }
}

for (const dir of staged) fs.rmSync(dir, { recursive: true, force: true });

console.log(failures === 0
    ? "\n\x1b[32m✓ Bundle corpus passed — every shipped bundle shape still boots.\x1b[0m\n"
    : `\n\x1b[31m✗ ${failures} check(s) failed.\x1b[0m\n`);
process.exit(failures === 0 ? 0 : 1);
