/**
 * E2E: an aged PROJECT — an old database *and its old artifacts* — meeting the
 * current runtime.
 *
 * `upgrade-e2e.test.ts` covers the aged-database axis for the auth schema, and it
 * is the reason several one-way auth migrations are safe. It could not have
 * caught the upgrade bug that actually shipped in 0.13, and neither could any
 * database-only corpus, because that bug did not live in the database:
 *
 *   * boot-ensure renamed `categorie_id` to `category_id` — correctly, and the
 *     rows came with it;
 *   * `assertRelationsResolve` then read the project's checked-in
 *     `backend/src/schema.generated.ts`, generated by the PREVIOUS release, which
 *     still declared `categorie_id`, and killed the boot;
 *   * restarting could not help, because the rename was already applied.
 *
 * Two artifacts from the same release, disagreeing after only one of them was
 * migrated. Every unit test on both sides passed, because each built its own
 * input and so could never let them disagree.
 *
 * So a snapshot here is a *project*: the database as a release provisioned it,
 * the tables and columns that release's codegen declared, and the collections
 * that produced both. See `project-snapshots/README.md`.
 *
 * What each replay asserts, in the order the failures matter:
 *
 *   1. the upgrade completes — boot-ensure runs to the end against the aged
 *      database, and does not need a second attempt to converge;
 *   2. the rows survive it — a rename that was silently an ADD shows up here as
 *      an empty column, which is what the original bug did before it was fixed;
 *   3. the tables are still locked — RLS on, policies present. An upgrade that
 *      leaves a table readable by every signed-in user is the fail-open case;
 *   4. a stale generated schema is DIAGNOSED — the boot either resolves or fails
 *      naming the generated file and the command that regenerates it, and never
 *      advises pinning a column the migration has just moved away from.
 *
 * Requires Docker.
 */

import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { readdirSync, readFileSync, existsSync, statSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { pgTable, text } from "drizzle-orm/pg-core";
import type { CollectionConfig } from "@rebasepro/types";

import { startPgContainer, stopPgContainer, PGVECTOR_IMAGE, type PgContainer } from "./pg-setup.js";
import { ensureAuthTablesExist } from "../../src/auth/ensure-tables.js";
import { ensureCollectionTables } from "../../src/schema/ensure-collection-tables.js";
import { ensureCollectionPolicies } from "../../src/schema/ensure-collection-policies.js";
import { ensureAppRole } from "../../src/security/rls-enforcement.js";
import { PostgresCollectionRegistry } from "../../src/collections/PostgresCollectionRegistry.js";
import { findRelationDefects, assertRelationsResolve } from "../../src/collections/validate-relations.js";

const SNAPSHOT_DIR = fileURLToPath(new URL("./project-snapshots", import.meta.url));

/**
 * A floor, not an equality — one per release, and the corpus is only as good as
 * how far back the oldest one goes. It exists because this suite's failure mode
 * is silence: `describe.each([])` registers no tests, the file passes in
 * milliseconds, and CI reports a green upgrade gate that ran against nothing.
 */
const MINIMUM_SNAPSHOTS = 1;

interface Snapshot {
    name: string;
    manifest: { frameworkVersion: string; authSchemaVersion: number; seededRows: Record<string, number> };
    collections: CollectionConfig[];
    /** Table (schema-qualified unless public) → the columns that release declared. */
    generatedSchema: Record<string, string[]>;
    sql: string;
}

const snapshots: Snapshot[] = readdirSync(SNAPSHOT_DIR)
    .filter(name => statSync(join(SNAPSHOT_DIR, name)).isDirectory())
    .filter(name => existsSync(join(SNAPSHOT_DIR, name, "manifest.json")))
    .sort()
    .map(name => ({
        name,
        manifest: JSON.parse(readFileSync(join(SNAPSHOT_DIR, name, "manifest.json"), "utf8")),
        collections: JSON.parse(readFileSync(join(SNAPSHOT_DIR, name, "collections.json"), "utf8")),
        generatedSchema: JSON.parse(readFileSync(join(SNAPSHOT_DIR, name, "generated-schema.json"), "utf8")),
        sql: readFileSync(join(SNAPSHOT_DIR, name, "schema.sql"), "utf8")
    }));

/**
 * Re-attach the relation thunks that JSON cannot carry.
 *
 * `relation.target` is a function returning the target collection, so it does not
 * survive `JSON.stringify`. Recording the *slug* it resolved to and rebuilding
 * the thunk here keeps the snapshot declarative — the alternative is recording
 * executable code, which would age into something that cannot be loaded at all.
 */
function rehydrate(collections: CollectionConfig[]): CollectionConfig[] {
    const bySlug = new Map(collections.map(c => [c.slug, c]));
    for (const collection of collections) {
        for (const prop of Object.values(collection.properties ?? {}) as Record<string, unknown>[]) {
            const relation = prop.relation as { target?: unknown; targetSlug?: string } | undefined;
            if (relation?.targetSlug && typeof relation.target !== "function") {
                relation.target = () => bySlug.get(relation.targetSlug!);
            }
        }
    }
    return collections;
}

describe("project snapshot inventory", () => {
    it(`has at least ${MINIMUM_SNAPSHOTS} project snapshot(s) to upgrade from`, () => {
        expect(snapshots.length).toBeGreaterThanOrEqual(MINIMUM_SNAPSHOTS);
    });

    it.each(snapshots)("$name recorded rows, without which the data half is untested", (snapshot) => {
        const total = Object.values(snapshot.manifest.seededRows).reduce((a, b) => a + b, 0);
        expect(total).toBeGreaterThan(0);
        expect(Object.keys(snapshot.generatedSchema).length).toBeGreaterThan(0);
    });
});

describe.each(snapshots)("upgrading a project left by $name", (snapshot) => {
    let container: PgContainer;
    let client: pg.Client;
    let collections: CollectionConfig[];

    /** Row counts per table, read from the aged database before the upgrade. */
    let before: Map<string, number>;

    /**
     * Per relation column, how many rows held a value before the upgrade.
     *
     * Keyed `schema.table` → column → count, because the column NAME is the
     * thing an upgrade is allowed to change. Comparing by name alone would be
     * unable to express the case this suite exists for.
     */
    let beforeKeys: Map<string, Map<string, number>>;

    /** Non-null counts for every `%_id` column of a table, right now. */
    const keyColumnCounts = async (schema: string, name: string): Promise<Map<string, number>> => {
        const keys = await client.query<{ column_name: string }>(
            `SELECT column_name FROM information_schema.columns
             WHERE table_schema = $1 AND table_name = $2 AND column_name LIKE '%\\_id'`,
            [schema, name]
        );
        const counts = new Map<string, number>();
        for (const { column_name } of keys.rows) {
            const populated = await client.query<{ count: string }>(
                `SELECT count(*)::text AS count FROM "${schema}"."${name}" WHERE "${column_name}" IS NOT NULL`
            );
            counts.set(column_name, Number(populated.rows[0].count));
        }
        return counts;
    };

    beforeAll(async () => {
        // pgvector's image: a recorded snapshot carries whatever the release
        // provisioned, and since the reference fixture gained a vector property
        // that includes `CREATE EXTENSION vector` and a `vector(1536)` column.
        // Restoring it on the suites' Alpine default fails at the first line of
        // the dump.
        //
        // Safe here specifically because this suite asserts on schema and rows,
        // never on text ordering — which is why the image is per-caller and this
        // one opts in rather than the default moving. See pg-setup.ts.
        container = await startPgContainer({ image: PGVECTOR_IMAGE });

        const admin = new pg.Client({ connectionString: container.connectionString });
        await admin.connect();
        const dbName = `project_${snapshot.name.replace(/[^a-z0-9]/gi, "_").toLowerCase()}`.slice(0, 60);
        await admin.query(`CREATE DATABASE ${dbName}`);
        await admin.end();

        const dbUrl = container.connectionString.replace(/\/rebase\?/, `/${dbName}?`);
        client = new pg.Client({ connectionString: dbUrl });
        await client.connect();

        // The role the recorded policies name has to exist before they can be
        // restored — it is a cluster object, not a database one, so the dump
        // does not carry it.
        await ensureAppRole(
            async (sqlText: string) => (await client.query(sqlText)).rows as Record<string, unknown>[],
            ["public", "rebase", "shop"]
        );
        await client.query(snapshot.sql);

        collections = rehydrate(snapshot.collections);

        before = new Map();
        beforeKeys = new Map();
        for (const table of Object.keys(snapshot.manifest.seededRows)) {
            const [schema, name] = table.split(".");
            const result = await client.query<{ count: string }>(
                `SELECT count(*)::text AS count FROM "${schema}"."${name}"`
            );
            before.set(table, Number(result.rows[0].count));
            beforeKeys.set(table, await keyColumnCounts(schema, name));
        }

        // ── The upgrade under test ───────────────────────────────────────────
        const pool = new pg.Pool({ connectionString: dbUrl });
        await ensureAuthTablesExist(drizzle(pool));
        await pool.end();

        await ensureCollectionTables(client, collections);
        await ensureCollectionPolicies(client, collections);
    }, 300_000);

    afterAll(async () => {
        await client?.end().catch(() => {});
        if (container) await stopPgContainer(container.containerName);
    });

    it("converges — a second run has nothing left to do", async () => {
        // Not a tautology about idempotence: the ensure paths are guarded by
        // probes rather than by a ledger, so a guard that reads a name the
        // catalogue stores differently re-issues its statement on every boot,
        // forever. That is a real shape — a constraint name past Postgres's
        // 63-byte limit is stored truncated and never matches the derived name
        // it is compared against.
        const second = await ensureCollectionTables(client, collections);

        // Index creations are excluded, and only the ones carrying
        // `IF NOT EXISTS`.
        //
        // They are not probe-guarded and are not meant to be: the planner emits
        // them on every boot and lets Postgres decide, which is the correct
        // shape for a statement that is free when the object is already there
        // and is the only safe way to add one CONCURRENTLY. So they are outside
        // the property this test exists for — "a guard that reads a name the
        // catalogue stores differently re-issues forever" — and asserting on
        // them fails for every project that declares an index, which since 0.14
        // is most of them.
        //
        // An index statement WITHOUT `IF NOT EXISTS` is still asserted, because
        // that one really would fail on the second boot.
        const reissued = second.actions.filter(
            a => !(a.kind === "create-index" && /IF\s+NOT\s+EXISTS/i.test(a.sql))
        );
        expect(reissued.map(a => `${a.kind} ${a.target}`)).toEqual([]);
    });

    it("keeps every row it was given", async () => {
        for (const [table, expected] of before) {
            const [schema, name] = table.split(".");
            const result = await client.query<{ count: string }>(
                `SELECT count(*)::text AS count FROM "${schema}"."${name}"`
            );
            expect({ table, rows: Number(result.rows[0].count) }).toEqual({ table, rows: expected });
        }
    });

    it("carries the data across any relation column it renamed", async () => {
        // The failure a rename exists to prevent: `ADD COLUMN` beside a
        // populated column succeeds, every statement reports success, and the
        // relation then reads the empty one. Nothing errors, and the data is
        // still in the database — just not where the code now looks.
        //
        // Which is why this cannot compare by column name. A renamed column is
        // supposed to have a different name afterwards; what must not change is
        // how many rows have a value in the column the current code reads.
        for (const [table, keysBefore] of beforeKeys) {
            const [schema, name] = table.split(".");
            const keysAfter = await keyColumnCounts(schema, name);

            const disappeared = [...keysBefore.keys()].filter(column => !keysAfter.has(column));

            for (const [column, populated] of keysAfter) {
                const at = `${table}.${column}`;

                if (keysBefore.has(column)) {
                    expect({ column: at, populated }).toEqual({ column: at, populated: keysBefore.get(column) });
                    continue;
                }

                // New to this table since the snapshot. If exactly one column
                // vanished in the same upgrade, this is that column under its
                // new name and it must have brought the rows with it. More than
                // one, and the pairing would be a guess — so assert the weaker
                // true thing rather than a stronger invented one.
                if (disappeared.length === 1) {
                    const from = disappeared[0];
                    expect({ column: `${at} (renamed from ${from})`, populated })
                        .toEqual({ column: `${at} (renamed from ${from})`, populated: keysBefore.get(from) });
                } else if (disappeared.length > 1) {
                    expect(populated).toBeGreaterThan(0);
                }
            }

            // Whatever happened, no column may simply have been dropped with its
            // rows: every one that is gone has to be accounted for by a rename.
            expect({ table, orphaned: disappeared.length > keysAfter.size ? disappeared : [] })
                .toEqual({ table, orphaned: [] });
        }
    });

    it("leaves every collection table locked", async () => {
        for (const table of before.keys()) {
            const [schema, name] = table.split(".");
            const rls = await client.query<{ relrowsecurity: boolean }>(`
                SELECT c.relrowsecurity FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = $1 AND c.relname = $2
            `, [schema, name]);
            expect({ table, rls: rls.rows[0]?.relrowsecurity }).toEqual({ table, rls: true });

            const policies = await client.query<{ count: string }>(
                "SELECT count(*)::text AS count FROM pg_policies WHERE schemaname = $1 AND tablename = $2",
                [schema, name]
            );
            expect(Number(policies.rows[0].count)).toBeGreaterThan(0);
        }
    });

    describe("the project's generated schema, as that release left it", () => {
        /**
         * A registry built from the RECORDED artifact — the stale one, after the
         * database has been migrated out from under it. This is the state a
         * developer's first boot after `pnpm install` is in, and the state no
         * hand-written fixture produces, because a fixture author writes both
         * sides and writes them agreeing.
         */
        const staleRegistry = (): PostgresCollectionRegistry => {
            const registry = new PostgresCollectionRegistry();
            registry.registerMultiple(collections);
            for (const [table, columns] of Object.entries(snapshot.generatedSchema)) {
                const bare = table.includes(".") ? table.split(".")[1] : table;
                const shape = Object.fromEntries(columns.map(column => [column, text(column)]));
                registry.registerTable(pgTable(bare, shape) as never, bare);
            }
            return registry;
        };

        it("either resolves, or says the generated file is what is stale", () => {
            const defects = findRelationDefects(collections, staleRegistry());
            if (defects.length === 0) {
                expect(() => assertRelationsResolve(collections, staleRegistry())).not.toThrow();
                return;
            }

            // It disagreed — which is legitimate, and is exactly the 0.13 state.
            // What is NOT legitimate is the diagnosis blaming the collection.
            let message = "";
            try {
                assertRelationsResolve(collections, staleRegistry());
            } catch (error) {
                message = error instanceof Error ? error.message : String(error);
            }

            expect(message).toMatch(/schema\.generated\.ts/);
            expect(message).toMatch(/rebase schema generate/);
        });

        it("never advises pinning a column the database no longer has", async () => {
            const defects = findRelationDefects(collections, staleRegistry());
            if (defects.length === 0) return;

            const live = await client.query<{ schema: string; table: string; column: string }>(`
                SELECT table_schema AS schema, table_name AS table, column_name AS column
                FROM information_schema.columns
                WHERE table_schema NOT IN ('pg_catalog', 'information_schema', 'rebase')
            `);
            const columnsByTable = new Map<string, Set<string>>();
            for (const row of live.rows) {
                const set = columnsByTable.get(row.table) ?? new Set<string>();
                set.add(row.column);
                columnsByTable.set(row.table, set);
            }

            for (const defect of defects) {
                // Any column name the advice offers has to be one the migrated
                // database actually has. Following advice that names a
                // migrated-away column is how a recoverable state became a
                // broken config.
                const suggested = [...defect.fix.matchAll(/`([a-z_][a-z0-9_]*_id)`/g)].map(m => m[1]);
                for (const column of suggested) {
                    const exists = [...columnsByTable.values()].some(columns => columns.has(column));
                    expect({ suggested: column, existsInDatabase: exists })
                        .toEqual({ suggested: column, existsInDatabase: true });
                }
            }
        });
    });
});
